### ISSUE TITLE
Just hangs on hls frame after certain amount of time 

### ISSUE THREAD

**Issue by rocmail911** [snobu/destreamer#10]
Just hangs on hls after certain amount of time - running on Windows 10

**Comment by snobu** [comment]
Can you paste the logs here? Are you able to complete the log in process in the browser window?

**Comment by snobu** [comment]
Closing for now. Please git pull and transpile for the latest version of the code. We substantially improved the way we get to the video URL and access token.

**Comment by chiragdkothari** [comment]
i am also having the same problem.....

**Comment by chiragdkothari** [comment]
where do i find the logs?

**Comment by snobu** [comment]
It's in the console output. Make sure you're not running destreamer in an elevated (root/Administrator) shell, for reasons we don't yet understand that prevents the puppeteer library to connect to the browser window that pops up for logging in.

**Comment by chiragdkothari** [comment]
i am running it in the npm command prompt .... is it okay? i will try to share a screenshot/gif of it next time ....

**Comment by lukaarma** [comment]
Yeah sure, CMD should be perfectly fine, just don't run it as admin
