### ISSUE TITLE
Folder and URLs text files mismatch

### ISSUE THREAD

**Issue by gelmanovic** [snobu/destreamer#100]
I decided to create a progressive numbered folder for each URL so as not to loose information about video upload date (after having created the URLs file adding them in chronological order), since teams saves them with a timestamp-free name.
The thing is I just found out destreamer won't stick to the order the URLs are typed in the text file, eventually messing all my folders system up.
I would expect that line 1 URL would go into line 1 folder, line 5 URL would go into line 5 folder but that's not happening.

**Comment by gelmanovic** [comment]
I'd welcome as well any other solution allowing me to get the timestamp displayed in the video file name, possibly in a conveniently orderable position.

**Comment by gelmanovic** [comment]
I'm quite sure this was not happening when I didn't use PATHs file

**Comment by gelmanovic** [comment]
Don't actually bother at all, I'm good with older version.

**Comment by snobu** [comment]
Right, i believe we're accidentally going over the video URL array in reverse or (we sort it?). I'll have a look.

**Comment by snobu** [comment]
Feel free to send a PR if you find the root cause there.

**Comment by gelmanovic** [comment]
now im back to latest version run from powershell (still calling git bash though) and it shows token expiry time again

**Comment by gelmanovic** [comment]
> Right, i believe we're accidentally going over the video URL array in reverse or some other order dictated by video metadata. I'll have a look.
> 
> EDIT:
> Looks like it's non-deterministic, we're awaiting a bunch of Promises that return in whatever order they feel like.
> https://github.com/snobu/destreamer/blob/master/src/Metadata.ts#L32
> 
> For performance reasons i'm not going to change the mechanics there but we can think about reordering the metadata array to match the input before we kick off downloading.

It might not be too much of an hassle since in the first video frames of almost all video files there's a kind of timestamp
