### ISSUE TITLE
UnhandledPromiseRejectionWarning: Command Failed

### ISSUE THREAD

**Issue by bwyyoung** [snobu/destreamer#11]
I got the below error.

`ERROR: fixed output name but more than one file to download
(node:35663) UnhandledPromiseRejectionWarning: Error: Command failed: youtube-dl --no-call-home --no-warnings --output "/Users/bwyyoung/Download_HDD//Meeting in "Lecture Room".mp4" --add-header Cookie:"Authorization=eyJUb2tl...........cEFzOGM9In0%3d; Signature=7lWoeLksDjJIzJP1LX7Vxoxh%252bmXr7PTXXFEKvuGtXKk%253d" "https://gkbzua4wayz4evghrorxwmd34a.streaming.mediaservices.windows.net/506e134b-38ff-4f69-8865-7556586f001c/1-5uzexnjuqyxqrzmo2qxxv7ngoc.ism/manifest(format=m3u8-aapl)"
    at checkExecSyncError (child_process.js:629:11)
    at Object.execSync (child_process.js:666:13)
    at rentVideoForLater (/Users/bwyyoung/Desktop/destreamer-dev/destreamer.ts:108:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:35663) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:35663) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by bwyyoung** [comment]
I solved the error. The video title was "/Users/bwyyoung/Download_HDD/Meeting in "Lecture Room".mp4". If there are quotes in title, it messes up the download script. Change the video title to something like "video" in destreamer.ts:

`        const title = "destreamer"
`

**Comment by snobu** [comment]
Thanks for reporting this! I'll try to repro and fix this.

**Comment by snobu** [comment]
Fixed in https://github.com/snobu/destreamer/commit/bf3850753512e0ed14e2ce935f7a04aa8e924ec6 (or a strong sense of hope towards that outcome). Can you `git pull` and try it out?

**Comment by bwyyoung** [comment]
Yes it works. However, you should take other considerations when it comes to the title. If after sanitising, the string becomes empty, or if there are still invalid characters, create a default title instead. This way, it will always work.

For example, the first video can be "destreamer-1", the second can be "destreamer-2" and so on.

It will ensure that batch downloads will always work even with titles in foreign languages like mandarin.

**Comment by snobu** [comment]
Good point. I think it's time we take one more dependency in. What about https://www.npmjs.com/package/sanitize-filename? Is this the "Node" way to do it? Happy to accept a PR if you're interested, i'm also looking for contributors (as in contributor access to the repo), let me know if interested in that as well.

**Comment by snobu** [comment]
Fixed in https://github.com/lukaarma/destreamer/commit/84d4ff10fcddbea2b4b90784a2fe41285e296a2d by @lukaarma lukaarma (Thank you!).
