### ISSUE TITLE
Videos get downloaded twice

### ISSUE THREAD

**Issue by Tinynja** [snobu/destreamer#111]
Hello, first of all I would like to thank you for the amazing work you have done, this piece of software is trully a life saver.

I encountered a small issue when using this. I do not know why it downloads the video twice. See the output here (the same thing happens when using `-f` option):

```
>destreamer.cmd -v -i https://web.microsoftstream.com/video/c4d6f734-6697-4437-b478-360a297754d8 -x
Using ffmpeg version git-2020-04-29-280383a Copyright (c) 2000-2020 the FFmpeg developers
Video URLs:
[
  'https://web.microsoftstream.com/video/c4d6f734-6697-4437-b478-360a297754d8'
]
Creating output directory:
videos
Access token still good for 54 minutes.
Video GUIDs:
[ 'c4d6f734-6697-4437-b478-360a297754d8' ]
Fetching metadata...
Calling https://usea-1.api.microsoftstream.com/api/videos/c4d6f734-6697-4437-b478-360a297754d8?api-version=1.4-private
[ 'videos' ]
Downloading Video: Réunion dans « Groupe Laboratoire 1 »
Spawning ffmpeg with access token and HLS URL. This may take a few seconds...
Using a fresh cookie.
progress [████████████████████████████████████████] 100% 186.8kbits/s 0s
Download finished: videos\Réunion dans « Groupe Laboratoire 1 » - 03-04-2020.mp4
Using ffmpeg version git-2020-04-29-280383a Copyright (c) 2000-2020 the FFmpeg developers
Video URLs:
[
  'https://web.microsoftstream.com/video/c4d6f734-6697-4437-b478-360a297754d8'
]
Access token still good for 54 minutes.
Video GUIDs:
[ 'c4d6f734-6697-4437-b478-360a297754d8' ]
Fetching metadata...
Calling https://usea-1.api.microsoftstream.com/api/videos/c4d6f734-6697-4437-b478-360a297754d8?api-version=1.4-private
[ 'videos' ]
Downloading Video: Réunion dans « Groupe Laboratoire 1 »
Spawning ffmpeg with access token and HLS URL. This may take a few seconds...
Using a fresh cookie.
progress [████████████████████████████████████████] 100% 186.8kbits/s 0s
Download finished: videos\Réunion dans « Groupe Laboratoire 1 » - 03-04-2020 - 1.mp4
>
```

I'm using the latest version of all softwares. Let me know if you need any more informations.

Thanks for your help!

**Comment by lukaarma** [comment]
Ok this is the second report of this problem, I'm trying to replicate it but it's not working.. I'll look into this and will let you know

**Comment by snobu** [comment]
@Tinynja does this happen with any video URL or just one or two from the ones you've tried?

**Comment by Hyedryn** [comment]
I also have the same issue

**Comment by snobu** [comment]
Oh crap, yes that's my bad. Will fix that right away, thanks!

**Comment by snobu** [comment]
Fixed. Thank you all for reporting this bug.

**Comment by lukaarma** [comment]
Oh I didn't think about the CMD script...I went crazy trying to figure it out, I'm so bad sometimes

**Comment by snobu** [comment]
Went the same route :) All credit to @Hyedryn for keeping a clear head and tracking this down.

**Comment by Klimmbimmel** [comment]
The issues occured for me with the addon, trying to download 1080p (Full HD) version of an embedded vimeo video. (Do you need a link? kenmartini DOT com SLASH dance-documentary )
