### ISSUE TITLE
Save credentials...

### ISSUE THREAD

**Issue by chiragdkothari** [snobu/destreamer#119]
is there a place where we can save the credentials so we dont have to type them again?

**Comment by snobu** [comment]
Not at the moment. Since the login could be handled by any identity provider Azure AD can federate with, that would not be easy to implement. As soon as the Microsoft Graph API gets released officially we may be able to do user credentials flow and cache refresh tokens that are good for 90 days+.

**Comment by chiragdkothari** [comment]
i am using that fork atm ... i mean that in the code can we type the value for username somewhere so that it uses that value by default?

**Comment by snobu** [comment]
Yes, just pass `--username user@domain.com` at the command line.

**Comment by snobu** [comment]
Oh, you mean literally *in code*. Sure, add `let username = 'user@domain.com';` right here:
https://github.com/snobu/destreamer/blob/master/src/destreamer.ts#L64 and rebuild (npm run build).
