### ISSUE TITLE
Ok hold on everybody

### ISSUE THREAD

**Issue by gelmanovic** [snobu/destreamer#121]
I read that you're trying to avoid the download of files with the same name but, as i was pointing out earlier when this first came out, on teams, group owners aka professors rarely assign a name to meetings so that goes by default.
There is no sense in skipping same name videos because they all are likely to share the same name.
You should rather address the matter by looking at exact (with milliseconds perhaps?) video duration

**Comment by snobu** [comment]
No, that behavior will be optional via the `--skip` command line parameter. If you don't pass we are simply adding a number to the video title if it's a duplicate.

**Comment by snobu** [comment]
Also you professor should probably enable the download flag on all the videos they publish, you shouldn't need destreamer in a world where education is easy to consume. Should be at least.
