### ISSUE TITLE
Unknown FFmpeg error 

### ISSUE THREAD

**Issue by tulgartarik** [snobu/destreamer#128]
help me pls..
![Ekran Resmi 2020-05-14 11 28 19](https://user-images.githubusercontent.com/22559555/81911590-369cb100-95d6-11ea-9db9-c4203bc89886.png)

**Comment by tulgartarik** [comment]
![image](https://user-images.githubusercontent.com/22559555/81920822-681b7980-95e2-11ea-81be-b9934fee466b.png)
i solved with windows..

**Comment by snobu** [comment]
Should work on the Mac as well, sometimes the MS Stream API is moody and doesn't return the encryption key on the first try. Just give it a few more tries. I have a fix for this ready, just need to clean up the code a bit.

**Comment by snobu** [comment]
I added exponential retry for all API calls. This should be much more stable now. `git pull`, rebuild and try it out.
