### ISSUE TITLE
ERROR: Requested format not available

### ISSUE THREAD

**Issue by jok8** [snobu/destreamer#13]
Hi, anytime I try to download a video I got this error
![image](https://user-images.githubusercontent.com/6472374/77261704-04876680-6c99-11ea-989c-76059d7ec101.png)

Anyone can tell me how to solve this?
thx

**Comment by snobu** [comment]
Fixed. `git pull`, transpile and try again. Looks like there was a bug introduced with `--format` and if you don't pass `--format` it defaults to `best` which confuses `youtube-dl`. All should be good now if you don't specify format.

**Comment by jok8** [comment]
Oh ok, thank you very much, now it works perfectly. This is a great project!

PS. Thank you for editing the post, I didn't know about cookies
