### ISSUE TITLE
npm install problem

### ISSUE THREAD

**Issue by AlexUnise** [snobu/destreamer#131]
hey got an issue and i don't know where it comes from so here's the log: 

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle destreamer@2.0.0~prebuild: destreamer@2.0.0
6 info lifecycle destreamer@2.0.0~build: destreamer@2.0.0
7 verbose lifecycle destreamer@2.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle destreamer@2.0.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\alexo\destreamer\node_modules\.bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\MATLAB\R2019b\bin;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\alexo\AppData\Local\Microsoft\WindowsApps;C:\Users\alexo\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\alexo\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\;C:\Users\alexo\AppData\Roaming\npm;C:\ffmpeg-4.2.2-win64-static\bin;
9 verbose lifecycle destreamer@2.0.0~build: CWD: C:\Users\alexo\destreamer
10 silly lifecycle destreamer@2.0.0~build: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'echo Transpiling TypeScript to JavaScript... && node node_modules/typescript/bin/tsc && echo Destreamer was built successfully.'
10 silly lifecycle ]
11 silly lifecycle destreamer@2.0.0~build: Returned: code: 1  signal: null
12 info lifecycle destreamer@2.0.0~build: Failed to exec build script
13 verbose stack Error: destreamer@2.0.0 build: `echo Transpiling TypeScript to JavaScript... && node node_modules/typescript/bin/tsc && echo Destreamer was built successfully.`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid destreamer@2.0.0
15 verbose cwd C:\Users\alexo\destreamer
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v12.16.3
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error destreamer@2.0.0 build: `echo Transpiling TypeScript to JavaScript... && node node_modules/typescript/bin/tsc && echo Destreamer was built successfully.`
22 error Exit status 1
23 error Failed at the destreamer@2.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by snobu** [comment]
Taking a wild guess you don't have git installed. Check requirements in README and reporr back.

**Comment by AlexUnise** [comment]
alright, i did npm instal typescript and it worked

**Comment by AlexUnise** [comment]
but now when I try to download one video it displays that

Launching headless Chrome to perform the OpenID Connect dance...
Error: Failed to launch the browser process! spawn C:\Users\alexo\destreamer\node_modules\puppeteer\.local-chromium\win64-722234\chrome-win\chrome.exe ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (C:\Users\alexo\destreamer\node_modules\puppeteer\lib\Launcher.js:750:14)
    at ChildProcess.<anonymous> (C:\Users\alexo\destreamer\node_modules\puppeteer\lib\Launcher.js:741:65)
    at ChildProcess.emit (events.js:310:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)


Unhandled error!
Timeout or fatal error, please check your downloads directory and try again

**Comment by snobu** [comment]
I think you missed the `npm install` step. Please go back to the README and follow along.

**Comment by snobu** [comment]
@AlexUnise Can we close this one or are you still unable to install dependencies?

**Comment by AlexUnise** [comment]
still having trouble with that, it seems that there is a problem with tokens

**Comment by snobu** [comment]
I would start over. Clone the repository to a new path, build and try again. Do all that in `cmd.exe`.
https://www.youtube.com/watch?v=bspR2LsNFjk&feature=youtu.be

**Comment by CarterJimmy** [comment]
Hello, I got a different error here. Here's the log file and the screenshot of the error message. I'm sure that I'd followed the instruction. Do anyone have ideas about it? Thank you.
[2020-05-29T10_16_51_370Z-debug.log](https://github.com/snobu/destreamer/files/4701214/2020-05-29T10_16_51_370Z-debug.log)
![Screenshot](https://user-images.githubusercontent.com/7923743/83249772-0c580f80-a1e2-11ea-90ae-9a0bceeee1a2.png)

**Comment by snobu** [comment]
Are you up to date with Node and npm versions?

**Comment by CarterJimmy** [comment]
> 
> 
> Are you up to date with Node and npm versions?

Thanks for reply. The low versions seems to be the reason of getting error messages. The scripts run correctly after I upgrade my node and npm. :)

**Comment by snobu** [comment]
Cool. Happy you got this working.
