### ISSUE TITLE
FFmpeg is missing!

### ISSUE THREAD

**Issue by dimitrijeem** [snobu/destreamer#136]
Hello! I get this message that ffmpeg is missing and I downloaded it, but I still get this message.
![git](https://user-images.githubusercontent.com/53309739/82159646-fd8f6580-988f-11ea-97e5-306cea909a0d.jpg)

**Comment by snobu** [comment]
Did you also put it in PATH or in the destreamer directory?

**Comment by snobu** [comment]
Also please use cmd.exe or PowerShell, don't use the git bash shell on Windows as you won't have a progress bar.

**Comment by snobu** [comment]
It's an easy one, i'm sure you can fix it. Closing.

**Comment by dimitrijeem** [comment]
Thanks!
