### ISSUE TITLE
Download stuck at "Spawning ffmpeg with access token and HLS URL"

### ISSUE THREAD

**Issue by Psycoguana** [snobu/destreamer#139]
Hello, I'm trying to download a video but it always gets stuck. It says "Spawning ffmpeg with access token and HLS URL. This may take a few seconds..." I've waited a few minutes but nothing. Then I kill it with Ctrl+C and it returns "Unknown FFmpeg error ". Adding the -v flag returns a little bit more info, but not always:
`ffmpeg returned an error: [hls @ 0x55a2c7229440] Opening 'crypto+https://someaddress.ism/QualityLevels(298000)/Fragments(video=540000000,format=m3u8-aapl)' for reading
`

I've got the latest npm, Node.js versions and FFMPEG (4.2.2-1), I'm not sure what could be the problem :_

**Comment by snobu** [comment]
Are you using an HTTP proxy to browse the web? Also check your firewall, ffmpeg needs to be able to talk to the outside world.

**Comment by Psycoguana** [comment]
No proxy at all. I did a `sudo ufw disable` and it's still not working. I'm not sure if I should do something else to check the firewall

**Comment by snobu** [comment]
Well, that's strange. Can you watch MS Stream videos in a regular browser window on that machine?

**Comment by Psycoguana** [comment]
> Well, that's strange. Can you watch MS Stream videos in a regular browser window on that machine?

Yeah, no problem at all. Yesterday I tried again but with a `--vcodec libx265`. My CPU usage was really high because of FFMPEG, but it took too long and I had to cancel it. Today I tried again without the `--vcodec flag`, It's been there for an hour and it doesn't seem like it's doing anything. Btw, the program runs normally until the pixelated thumbnail, after that, it just stays there.

The videos are ~2 hours long. Is it normal to take this long to download? If it is, maybe it's just not showing the progress bar?

**Comment by snobu** [comment]
Progress bar should.. progress in all cases. I would swap the ffmpeg binary for a different one, anything above v4 should work.

**Comment by Psycoguana** [comment]
One thing I noticed monitoring the network activity with nethogs is that node and ffmpeg are receiving data, mostly ffmpeg, but after a while none of them show up.

What you mean about changing binaries? Another version? If so, I tried 4.2.2-1 (apt package ) and 4.1.4 (snap store) and the progress bar doesn't show with any of them.

**Comment by Psycoguana** [comment]
I just realized I've got this error: 
`2020/05/21 17:48:45.474097 system_key.go:126: cannot determine nfs usage in generateSystemKey: cannot parse /etc/fstab: expected between 3 and 6 fields, found 13`

I'm not sure what this means or if it matters

**Comment by fehernyul** [comment]
Hi, can you help me in this:
![image](https://user-images.githubusercontent.com/25593792/82649677-e34fe180-9c19-11ea-85ef-0263eb1f1227.png)

**Comment by snobu** [comment]
What's your Node version? You should be on Node 10 or higher, otherwise thing can break.

**Comment by Psycoguana** [comment]
> What's your Node version? You should be on Node 10 or higher, otherwise things can break.

If you're talking to me, I'm currently at Node v12.16.3

**Comment by snobu** [comment]
Sorry, no, the Node question is for @fehernyul. Really no idea what's wrong with your setup, @Psycoguana. Wish i could be more helpful here.

**Comment by Psycoguana** [comment]
**It IS downloading!** I really needed this to work, so I started adding logs here and there until I modified this function in build/src/destreamer.js: `ffmpegCmd.on('update', (data) => {
            const currentChunks = Utils_1.ffmpegTimemarkToChunk(data.out_time);
            pbar.update(currentChunks, {
                speed: data.bitrate
            });`

I added this betweeen the currentChunks const and the pbar.update call: `            console.info('Remaining chunks: ' + (video.totalChunks - currentChunks));
            console.info('Download Speed: ' + data.bitrate + '\n');`

It works perfectly...almost. It looks like, for some reason, the progress bar is just not showing at all (Could the reason be that I use Oh My Zsh as my default shell?), but everything else works fine. The download takes a while cause it's downloading at ~200 kbits/s, I don't know why, but it's not that big of a deal.

Anyway, if you want I can provide more data and maybe we can fix my progress bar, but since this is working good enough for me and I'm the only one affected, feel free to close this issue.

Also, this is an amazing software and will help me a lot in my studies in these weird times, thanks a lot and good luck!

**Comment by snobu** [comment]
I did not tested on zsh at all. Try it in bash, it should work 'out of the box'.

**Comment by molikuner** [comment]
I'm using `oh-my-zsh` as well and it works fine, but it's macOS. I can try it on Linux tomorrow, but I don't see why the shell should be any problem, since the progress bar is done via `Node.js`. As far as I know, this should work independently from the shell.

**Comment by molikuner** [comment]
Also works flawlessly under Linux.

**Comment by snobu** [comment]
>... I don't see why the shell should be any problem, since the progress bar is done via `Node.js`. As far as I know, this should work independently from the shell.

The progress bar we're using only cares about the terminal features, shell should not be a factor. However, since there are many terminals out there, results may vary. Happy you could make this work in the end and it's of value to you.

**Comment by Psycoguana** [comment]
> I did not test on zsh at all. Try it in bash, it should work 'out of the box'.

It doesn't, I've got no idea what could be causing it. Anyway, I see you closed the issue and it's working good enough so it doesn't matter anymore, thanks a lot for your help @snobu !

**Comment by clalexni** [comment]
> **It IS downloading!** I really needed this to work, so I started adding logs here and there until I modified this function in build/src/destreamer.js: `ffmpegCmd.on('update', (data) => { const currentChunks = Utils_1.ffmpegTimemarkToChunk(data.out_time); pbar.update(currentChunks, { speed: data.bitrate });`
> 
> I added this betweeen the currentChunks const and the pbar.update call: ` console.info('Remaining chunks: ' + (video.totalChunks - currentChunks)); console.info('Download Speed: ' + data.bitrate + '\n');`
> 
> It works perfectly...almost. It looks like, for some reason, the progress bar is just not showing at all (Could the reason be that I use Oh My Zsh as my default shell?), but everything else works fine. The download takes a while cause it's downloading at ~200 kbits/s, I don't know why, but it's not that big of a deal.
> 
> Anyway, if you want I can provide more data and maybe we can fix my progress bar, but since this is working good enough for me and I'm the only one affected, feel free to close this issue.
> 
> Also, this is an amazing software and will help me a lot in my studies in these weird times, thanks a lot and good luck!

I had the same issue, seems to be working now. Thanks! btw, Im using zsh

**Comment by clalexni** [comment]
Had the same exact issue as described...
 `exec bash` in terminal to switch from zsh to bash. Running it with bash fixed the issue.
Just downloaded 3 vids in a row (about 1.5 hour long per video), so far so good :D

**Comment by snobu** [comment]
Hmm, interesting one. We do run in bash by default,
https://github.com/snobu/destreamer/blob/master/destreamer.sh#L1 not sure why switching shells manually would make a difference.
