### ISSUE TITLE
(node:17671) UnhandledPromiseRejectionWarning: Error: Page crashed!

### ISSUE THREAD

**Issue by 0livrea1** [snobu/destreamer#14]
I have this error:
`Output Directory: videos
Using youtube-dl version 2020.03.08
Using ffmpeg version n4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
Launching headless Chrome to perform the OpenID Connect dance...
Navigating to STS login page...
We are logged in. Sorry, i mean "you".
(node:17384) UnhandledPromiseRejectionWarning: TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at /home/livrea/Scrivania/destreamer-dev/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21
  -- ASYNC --
    at Frame.<anonymous> (/home/livrea/Scrivania/destreamer-dev/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/home/livrea/Scrivania/destreamer-dev/node_modules/puppeteer/lib/Page.js:674:49)
    at Page.<anonymous> (/home/livrea/Scrivania/destreamer-dev/node_modules/puppeteer/lib/helper.js:112:23)
    at rentVideoForLater (/home/livrea/Scrivania/destreamer-dev/destreamer.js:72:20)
(node:17384) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17384) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by lukaarma** [comment]
#18

**Comment by snobu** [comment]
Closing as this should already be fixed.
