### ISSUE TITLE
ffmpeg returned an error: Conversion failed!

### ISSUE THREAD

**Issue by eduardothevenet** [snobu/destreamer#140]
When running on macOS v10.14.6 the video start to download and just a few seconds the following error is shown.

ffmpeg returned an error: Conversion failed!
Unknown FFmpeg error

I did a git pull and then install + rebuild but the same issue.

![image](https://user-images.githubusercontent.com/55850550/82267936-240ed880-9944-11ea-87e9-872cecb7b09d.png)

**Comment by snobu** [comment]
Just tried it on my Mac and it works fine, i'm using FFmpeg 4.2.2.
Check your FFmpeg version it may be a bit too old for the job.

**Comment by eduardothevenet** [comment]
The problem is the FFmpeg version 3.3.1. Then based in your suggestion I did an upgrade to 4.2.2_5 and the problem was resolved. (brew upgrade ffmpeg).

Thanks very much for your support.
