### ISSUE TITLE
mismatched URLs-directories lists order

### ISSUE THREAD

**Issue by gelmanovic** [snobu/destreamer#142]
Videos are downloaded regardless of the order in which they appear in the URLs txt, only the txt directories list is followed along.
That's a problem because a few times videos don't have reserved frames at the beginning for displaying the date and time at which they were recorded.
Not sure as whether it's still an issue but as of one month ago it was in fact. Today I'm running it once more so tomorrow will be able to better tell.

**Comment by gelmanovic** [comment]
As of now it sticks to URLs txt order but actually I didn't pass the directories txt argument

**Comment by snobu** [comment]
Not sure i understand. Can you please rephrase and maybe use an example as well?

**Comment by gelmanovic** [comment]
I already did a few weeks ago.
I gave URLs txt list and directories txt list as arguments but videos were shuffled across directories, meaning the first directory in txt was not filled with the first video in txt

**Comment by snobu** [comment]
Oh i see, that's @kylon, you'll need to await his input.

**Comment by snobu** [comment]
Oh i see, that's @kylon's implementation, you'll need to await his input.

**Comment by gelmanovic** [comment]
I'm assuming he won't reply anytime soon

**Comment by lukaarma** [comment]
@gelmanovic there is a pattern in the mismatch? or it's purely random?

**Comment by gelmanovic** [comment]
Everytime a different one

**Comment by lukaarma** [comment]
I could use a url file (censored if you like) and folder file that you know are defective as an example, please

**Comment by gelmanovic** [comment]
I didn't keep the files and folders but one thing I can say is that it just stuck with folders' order, saving random files in the right folder order

**Comment by lukaarma** [comment]
ok that is helpful to know :D will look into it (if this is still an issue, if I recal right kylon did a fix for this exact reason some time ago)

**Comment by gelmanovic** [comment]
Grazie tipo

**Comment by lukaarma** [comment]
is this solved @gelmanovic ?

**Comment by lukaarma** [comment]
marking this as solved, reopen a new one if needed
