### ISSUE TITLE
deploy GPU for encoding

### ISSUE THREAD

**Issue by gelmanovic** [snobu/destreamer#143]
For what is my understanding of coding, this might either be the simplest shit there possible to write or a complete nightmare for low budget opensource projects like this.
But that would be nice if one could let the GPU do the encoding work.

**Comment by snobu** [comment]
Since we directly expose FFmpeg's video codec parameter you can do that today by passing `--vcodec h264_nvenc`. Your FFmpeg binary must be built with NVIDIA CUDA support.

https://developer.nvidia.com/ffmpeg

**Comment by gelmanovic** [comment]
I was thinking of vp9 but seems like it's not supported on the encoding side

**Comment by snobu** [comment]
Nobody supports VP9 in hardware, probably not even Google. It's either H264 or H265 (hopefully) for NVIDIA.

**Comment by gelmanovic** [comment]
I have done so but the diminished speed might be incompatible with token expiry time

**Comment by gelmanovic** [comment]
I found it nice though that one could run multiple istances of cmd, which along the skip already existing feature brings a lot more ease in our pupils' lives.
