### ISSUE TITLE
Created university of Pisa fork

### ISSUE THREAD

**Issue by Guray00** [snobu/destreamer#148]
Hi, i made a fork to work with the university of Pisa portal. You can find all here: https://github.com/Guray00/destreamer-unipi

If you can i would like to be added to the list of avaiable versions! 
Ps: I have done a credentials.txt to allow users to don't have to re-enter their credentials each time... It is not really safe but it works.

**Comment by snobu** [comment]
Will add a link to your fork in the README. I strongly suggest you implement keytar for storing passwords securely. It's very simple to use.
https://www.npmjs.com/package/keytar

**Comment by Guray00** [comment]
All right! Thanks so much!
