### ISSUE TITLE
Status code 401 ubuntu

### ISSUE THREAD

**Issue by TinoCle** [snobu/destreamer#149]
Hi! I'm having this error every hour and a half, more or less. It seems like my token has expired, but it never shows up the chromium window to re-login, destreamer just closes it the first time I put my credentials and I never see that window again until this error.

I see some "GET /api/refreshtoken" URLs but I don't know what this is doing.
I've read the "Outstanding bugs" section on your readme, it seems like I have to see chromium pop up every time my token expires, or that's what I understand.
Unfortanelly, every time I run the command a new file is created, and all the Mbs downloaded are just cut videos.
```
Error: Request failed with status code 401
    at createError (/home/agustin/Desktop/destreamer/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/agustin/Desktop/destreamer/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/agustin/Desktop/destreamer/node_modules/axios/lib/adapters/http.js:236:)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
config: 
   { url: 'https://usea-1.api.microsoftstream.com/api/refreshtoken?api-version=1.4-private',
     method: 'get',
     headers: 
      { Accept: 'application/json, text/plain, */*',
        Cookie: 'Authorization=XXX,
        'User-Agent': 'axios/0.19.2' },
 ```

**Comment by snobu** [comment]
Try to pull the latest `master` branch, you seem to be using destreamer at an older commit (version).

Unfortunately that bug is still present, not really a bug, more like we could not find a good way to refresh the token, so if the access token expires (one hour lifetime), the next video in the list will fail. To get around this download one video per run. Not great but it is what it is.

**Comment by gelmanovic** [comment]
So I found this strategy to be resolutive of the access token renewal request not showing up.
I simply lunch many instances of shell and prompt to download a single video. I can get up to 100 shells running synchronousely and up to 7mbps net download speed, So I end up having like +10Gb worth videos in quite about the same time amount the token takes to expire.
