### ISSUE TITLE
Won't run

### ISSUE THREAD

**Issue by elamouri** [snobu/destreamer#150]
when run it ,show me that 
![Screenshot_3](https://user-images.githubusercontent.com/34379854/83458254-ded1c700-a46a-11ea-8cda-b40f78d832ce.png)

**Comment by snobu** [comment]
Use cmd.exe or PowerShell on Windows. Other terminal/shell combos are not guaranteed to work at all.

**Comment by elamouri** [comment]
hmmm,can u put anyhelp like from google?

**Comment by elamouri** [comment]
Nvm i found it Thx you

**Comment by elamouri** [comment]
still don't work
