### ISSUE TITLE
Unknown FFmpeg error

### ISSUE THREAD

**Issue by steelpwner** [snobu/destreamer#151]
![image](https://user-images.githubusercontent.com/42214819/83679201-9d453700-a5a4-11ea-9163-db44c1cfd5b0.png)

My video doesn't download, I can see it but can't download it...

![image](https://user-images.githubusercontent.com/42214819/83679236-a9c98f80-a5a4-11ea-8e5d-793a2caf6060.png)

Can you help me?

**Comment by snobu** [comment]
Chevk your ffmpeg version. 4.2 or above and you should be good to go.

**Comment by lukaarma** [comment]
Did snobu's comment fixed it @steelpwner, or you need more help?

**Comment by fhassanuk** [comment]
<img width="630" alt="Screenshot 2020-06-14 at 06 30 42" src="https://user-images.githubusercontent.com/66887948/84580328-94f0c580-ae08-11ea-8281-f01ab6c88ea0.png">


I have the ffmeg folder but where do I place the files?

**Comment by fhassanuk** [comment]
<img width="568" alt="Screenshot 2020-06-14 at 06 31 32" src="https://user-images.githubusercontent.com/66887948/84580337-b0f46700-ae08-11ea-8bd3-b0efb4df12e6.png">

**Comment by lukaarma** [comment]
I can see from your file explorer that you have the ffmpeg folder there, you just need to open it and copy the ffmpeg binary into destreamer main folder or in a folder on your path|

**Comment by fhassanuk** [comment]
I did that but I keep getting the same error message above, that I need a recent release of FFmeg. I downloaded to most up to date version.

**Comment by lukaarma** [comment]
right, because of #146 ...
there is a fix there ([see this](https://github.com/snobu/destreamer/issues/146#issuecomment-634652024)) that you can try

I'll look into fixing ffmpeg not being detected soon™

**Comment by fhassanuk** [comment]
Erm, do I create the simlink from the ffmeg folder in destreamer? Can you please help with this?

**Comment by lukaarma** [comment]
`ln -s . /usr/local/bin/ffmpeg` should work (not so sure, never used macOs)

**Comment by fhassanuk** [comment]
Got it working, sharing link for MacOS users:

https://aaronolsen.github.io/tutorials/stereomorph/installing_ffmpeg.html

**Comment by lukaarma** [comment]
Nice, closing issue
If you have more trouble reopen this issue or a new one :D

**Comment by frakman1** [comment]
I was having a similar issue on my Mac (High Sierra with ffmpeg version `3.4.2`) 
It worked with one video, but kept getting errors midway  with another video.
```
[ERROR] FFmpeg returned an error: Conversion failed!
[FATAL ERROR] Unknown FFmpeg error
```
I upgraded it using brew. Several million files later, it upgraded to `4.3.1` and is working now

```bash
$brew upgrade ffmpeg
```
