### ISSUE TITLE
Solution for access token expiry time

### ISSUE THREAD

**Issue by gelmanovic** [snobu/destreamer#153]
So I found this strategy to be resolutive of the access token renewal request not showing up.
I simply lunch many instances of shell and prompt to download a single video each. I can get up to 100 shells running synchronously and up to 45Mbps net download speed, So I end up having like +30Gb worth videos in quite about the same time amount the token takes to expire.
This approach requires that you edit a text file (aided with excel formulas) so as to have each line to display the same destreamer code varying based on the specific video link and then (in my WinOs case) open powershell and copypaste a single line from the text file and press enter and so on. It will open a new bash shell each time so you don't even have to lunch them every time.

**Comment by lukaarma** [comment]
See #155

**Comment by gelmanovic** [comment]
thanks for R2A but for now I'm done donwloading videos, we'll get to talk again next year if lectures will keep being streamed.

**Comment by lukaarma** [comment]
Yeah, I guessed so (lectures are why I wanted to get involved with this in the first place :P)
Well if you could give it a try when you'll have more videos I'll be glad for the feedback

**Comment by gelmanovic** [comment]
For now I can tell that I already was checking "stay logged in" option in chromium but still did not work any magic

**Comment by lukaarma** [comment]
Well now it should if you use -k, as explained in #155 :D

**Comment by gelmanovic** [comment]
I said so because based on what you say it seems that one could not check that option before so just letting you know I already could

**Comment by lukaarma** [comment]
Yeah I known but what changed is that with - the new options you allow chrome caching that saves on disk all the chrome data so that it can use them the next time to login again and I (should) have implemented a refresh function that works

**Comment by gelmanovic** [comment]
not expert enough to know how can I get that branch on my terminal, would you please tell me
