### ISSUE TITLE
Unhandled error!

### ISSUE THREAD

**Issue by ErcouldnT** [snobu/destreamer#154]
I downloaded videos succesfully yesterday. But I face with this error after first succesfull session.
I rebuilt npm modules and redownloaded the script for trying some self solution but it's still giving me the same error. Final Red Error like that:

Unhandled error!
Timeout or fatal error, please check your downloads directory and try again

There's nothing in downloads directory and also no this kind of directory at first session.
Before this red-backgrounded-error message, there is tons of red error lines which i can write here if you want to develope script. Btw im using this script in Windows atm.

**Comment by lukaarma** [comment]
Did you try using the -v (verbose) option?

> Before this red-backgrounded-error message, there is tons of red error lines

those would be very usefull

**Comment by SimoneG97** [comment]
Can confirm had the same problem

`Fetching metadata...
Got HTTP undefined. Retrying request...
Error: timeout of 7000ms exceeded
    at createError (C:\Users\Simone\Desktop\destreamer\node_modules\axios\lib\core\createError.js:16:15)
    at ClientRequest.handleRequestTimeout (C:\Users\Simone\Desktop\destreamer\node_modules\axios\lib\adapters\http.js:256:16)
    at Object.onceWrapper (events.js:416:28)
    at ClientRequest.emit (events.js:322:22)
    at TLSSocket.emitRequestTimeout (_http_client.js:709:9)
    at Object.onceWrapper (events.js:416:28)
    at TLSSocket.emit (events.js:322:22)
    at TLSSocket.Socket._onTimeout (net.js:479:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  config: {
    url: 'videos/f30850c7-42ab-498d-8bc2-77ae9cbeb62d?api-version=1.4-private',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'destreamer/2.0 (Hammer of Dawn)',
      Authorization: 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IlNzWnNCTmhaY0YzUTlTNHRycFFCVEJ5TlJSSSIsImtpZCI6IlNzWnNCTmhaY0YzUTlTNHRycFFCVEJ5TlJSSSJ9.eyJhdWQiOiJodHRwczovLyoubWljcm9zb2Z0c3RyZWFtLmNvbSIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzlkZjA4YTdjLTMxZDctNDAyNC05YmE2LTVlZDVlZmFjMWEwMS8iLCJpYXQiOjE1OTE5NzEwNzYsIm5iZiI6MTU5MTk3MTA3NiwiZXhwIjoxNTkxOTc0OTc2LCJhY3IiOiIxIiwiYWlvIjoiNDJkZ1lQajF2YzlIcTJLT3JkWDVXVy9reExVNmNvK0liSkR3L0hQRzJ2YXg1NXhYZDdJQSIsImFtciI6WyJwd2QiXSwiYXBwaWQiOiJjZjUzZmNlOC1kZWY2LTRhZWItOGQzMC1iMTU4ZTdiMWNmODMiLCJhcHBpZGFjciI6IjIiLCJmYW1pbHlfbmFtZSI6IkdBTEFOVEUiLCJnaXZlbl9uYW1lIjoiU0lNT05FIiwiaXBhZGRyIjoiMTUxLjI2LjE2NC4yMzAiLCJuYW1lIjoiU2ltb25lIEdhbGFudGUiLCJvaWQiOiIzM2JjZDU3Yy1jYzQ3LTQxYWMtYWVmNC0yZWYxYzI0NDA1MDAiLCJvbnByZW1fc2lkIjoiUy0xLTUtMjEtMzc5NTcwMzA1NS0zMzUxNzEzMDI2LTMzNDUzMDQ3NzktMTQwOTU0IiwicHVpZCI6IjEwMDNCRkZEOUFDMjRBMDkiLCJyaCI6IjAuQVF3QWZJcnduZGN4SkVDYnBsN1Y3NndhQWVqOFU4XzIzdXRLalRDeFdPZXh6NE1NQUxrLiIsInNjcCI6ImFjY2Vzc19taWNyb3NvZnRzdHJlYW1fc2VydmljZSIsInN1YiI6Ik82LXRwaVhNZnloWFlUQzE3MmRJSmk5dEkzRVZWWVA3SlRVUHpmWGxwY1kiLCJ0aWQiOiI5ZGYwOGE3Yy0zMWQ3LTQwMjQtOWJhNi01ZWQ1ZWZhYzFhMDEiLCJ1bmlxdWVfbmFtZSI6InNpbW9uZS5nYWxhbnRlQHN0dWRlbnQudW5pdmFxLml0IiwidXBuIjoic2ltb25lLmdhbGFudGVAc3R1ZGVudC51bml2YXEuaXQiLCJ1dGkiOiJPb1ZIRzBqekxVS1lVWWMyOFZvWUFBIiwidmVyIjoiMS4wIn0.bx-mYXTIdOz9aYe67ctx5t3xvzWBVbT_cnCYsuwooYTxYislxpuYTTmCI8IaC5W_q1mnspXb8iXxa8nPNOjbNIY39infcHPYmaPSyH9IJs2tLS6kEMO847NzzddizxxGB8dOqwKvYtje231iwD6euKUOTZUaFGy9qX2Xj-KG-QhUxyCwCbQ8R1-NIIpmHW8E0yC_S71SV9XwSF3DIb2_IbJl1PA6iPToZfdQuNFQCXiy2C3mIbyI38GaVwAhE48sN_uLvdKRPR0aDOB-f9GLJTpFU2L1v9bURG8lHGraXXCm7z3dsM7nmlI9NSPqffQT5ztxnnNDBA2MpSHwXvCq3g'
    },
    baseURL: 'https://euwe-1.api.microsoftstream.com/api/',
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 7000,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus],
    'axios-retry': { retryCount: 0, lastRequestTime: 1591972775355 },
    data: undefined
  },
  code: 'ECONNABORTED',
  request: Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [Object]
    },
    writable: true,
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      protocol: 'https:',
      maxRedirects: 21,
      maxBodyLength: 10485760,
      path: '/api/videos/f30850c7-42ab-498d-8bc2-77ae9cbeb62d?api-version=1.4-private',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'euwe-1.api.microsoftstream.com',
      port: null,
      nativeProtocols: [Object],
      pathname: '/api/videos/f30850c7-42ab-498d-8bc2-77ae9cbeb62d',
      search: '?api-version=1.4-private'
    },
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'GET /api/videos/f30850c7-42ab-498d-8bc2-77ae9cbeb62d?api-version=1.4-private HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: destreamer/2.0 (Hammer of Dawn)\r\n' +
        'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IlNzWnNCTmhaY0YzUTlTNHRycFFCVEJ5TlJSSSIsImtpZCI6IlNzWnNCTmhaY0YzUTlTNHRycFFCVEJ5TlJSSSJ9.eyJhdWQiOiJodHRwczovLyoubWljcm9zb2Z0c3RyZWFtLmNvbSIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzlkZjA4YTdjLTMxZDctNDAyNC05YmE2LTVlZDVlZmFjMWEwMS8iLCJpYXQiOjE1OTE5NzEwNzYsIm5iZiI6MTU5MTk3MTA3NiwiZXhwIjoxNTkxOTc0OTc2LCJhY3IiOiIxIiwiYWlvIjoiNDJkZ1lQajF2YzlIcTJLT3JkWDVXVy9reExVNmNvK0liSkR3L0hQRzJ2YXg1NXhYZDdJQSIsImFtciI6WyJwd2QiXSwiYXBwaWQiOiJjZjUzZmNlOC1kZWY2LTRhZWItOGQzMC1iMTU4ZTdiMWNmODMiLCJhcHBpZGFjciI6IjIiLCJmYW1pbHlfbmFtZSI6IkdBTEFOVEUiLCJnaXZlbl9uYW1lIjoiU0lNT05FIiwiaXBhZGRyIjoiMTUxLjI2LjE2NC4yMzAiLCJuYW1lIjoiU2ltb25lIEdhbGFudGUiLCJvaWQiOiIzM2JjZDU3Yy1jYzQ3LTQxYWMtYWVmNC0yZWYxYzI0NDA1MDAiLCJvbnByZW1fc2lkIjoiUy0xLTUtMjEtMzc5NTcwMzA1NS0zMzUxNzEzMDI2LTMzNDUzMDQ3NzktMTQwOTU0IiwicHVpZCI6IjEwMDNCRkZEOUFDMjRBMDkiLCJyaCI6IjAuQVF3QWZJcnduZGN4SkVDYnBsN1Y3NndhQWVqOFU4XzIzdXRLalRDeFdPZXh6NE1NQUxrLiIsInNjcCI6ImFjY2Vzc19taWNyb3NvZnRzdHJlYW1fc2VydmljZSIsInN1YiI6Ik82LXRwaVhNZnloWFlUQzE3MmRJSmk5dEkzRVZWWVA3SlRVUHpmWGxwY1kiLCJ0aWQiOiI5ZGYwOGE3Yy0zMWQ3LTQwMjQtOWJhNi01ZWQ1ZWZhYzFhMDEiLCJ1bmlxdWVfbmFtZSI6InNpbW9uZS5nYWxhbnRlQHN0dWRlbnQudW5pdmFxLml0IiwidXBuIjoic2ltb25lLmdhbGFudGVAc3R1ZGVudC51bml2YXEuaXQiLCJ1dGkiOiJPb1ZIRzBqekxVS1lVWWMyOFZvWUFBIiwidmVyIjoiMS4wIn0.bx-mYXTIdOz9aYe67ctx5t3xvzWBVbT_cnCYsuwooYTxYislxpuYTTmCI8IaC5W_q1mnspXb8iXxa8nPNOjbNIY39infcHPYmaPSyH9IJs2tLS6kEMO847NzzddizxxGB8dOqwKvYtje231iwD6euKUOTZUaFGy9qX2Xj-KG-QhUxyCwCbQ8R1-NIIpmHW8E0yC_S71SV9XwSF3DIb2_IbJl1PA6iPToZfdQuNFQCXiy2C3mIbyI38GaVwAhE48sN_uLvdKRPR0aDOB-f9GLJTpFU2L1v9bURG8lHGraXXCm7z3dsM7nmlI9NSPqffQT5ztxnnNDBA2MpSHwXvCq3g\r\n' +
        'Host: euwe-1.api.microsoftstream.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      insecureHTTPParser: undefined,
      path: '/api/videos/f30850c7-42ab-498d-8bc2-77ae9cbeb62d?api-version=1.4-private',
      _ended: false,
      res: null,
      aborted: true,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      reusedSocket: false,
      _redirectable: [Circular],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://euwe-1.api.microsoftstream.com/api/videos/f30850c7-42ab-498d-8bc2-77ae9cbeb62d?api-version=1.4-private',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function]
}


Unhandled error!
Timeout or fatal error, please check your downloads directory and try again`

**Comment by lukaarma** [comment]
From what I can gather from your error is that the connection to the API times out, so what i can suggest you is to check you connection speed/stability, maybe try using you mobile connection instead of your home network

**Comment by snobu** [comment]
Correct.

```
Got HTTP undefined. Retrying request...
Error: timeout of 7000ms exceeded
```
That's the retry policy (something that i introduced last month) doing its thing, however even after three tries it can't get to the metadata. Just keep trying or switch to a different Wi-Fi.

**Comment by andreafresco** [comment]
Hi thanks for the great work! I'm having the similar problem and I tried yours suggestion but I'm not able to solve it. The first time it worked and the day after it stopped working. I tried with different wi-fi networks and tried several time to run the code.
Could you help me? Below I'm attaching the code I run in the verbose mode:

$ ./destreamer.sh -v -i https://web.microsoftstream.com/video/6fd95fe0-77ae-4555-8326-b4e707237ed8
Using ffmpeg version 2021-01-12-git-ca21cb1e36-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers

Video URLs:
[
  'https://web.microsoftstream.com/video/6fd95fe0-77ae-4555-8326-b4e707237ed8'
]

Access token still good for 58 minutes.

Video GUIDs:
[ '6fd95fe0-77ae-4555-8326-b4e707237ed8' ]
Fetching metadata...
Calling https://euwe-1.api.microsoftstream.com/api/videos/6fd95fe0-77ae-4555-8326-b4e707237ed8?api-version=1.4-private
[ 'videos' ]
RangeError: Invalid array length
    at Object.parse (C:\Users\andre\destreamer\node_modules\cli-progress\lib\options.js:48:38)
    at new SingleBar (C:\Users\andre\destreamer\node_modules\cli-progress\lib\single-bar.js:8:24)
    at downloadVideo (C:\Users\andre\destreamer\build\src\destreamer.js:138:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)


Unhandled error!
Timeout or fatal error, please check your downloads directory and try again

Thanx!
