### ISSUE TITLE
Can not download lists..Not valid format..

### ISSUE THREAD

**Issue by panoszik** [snobu/destreamer#156]
![image](https://user-images.githubusercontent.com/20783587/83853554-1e740980-a71e-11ea-8389-ef083d5423ca.png) I get this error with a text format like this 
![image](https://user-images.githubusercontent.com/20783587/83853653-43687c80-a71e-11ea-8190-2dd5f55eaeba.png)

**Comment by lukaarma** [comment]
Try to append the .txt extension, it should fix this issue
Right now it's trying to parse the path as an URL I think

**Comment by panoszik** [comment]
Now i think it can not find it..
![image](https://user-images.githubusercontent.com/20783587/83855881-67798d00-a721-11ea-97cc-d7653c100fe3.png)

**Comment by lukaarma** [comment]
You have to rename the file too so that it matches, so you need vid1.txt, etc... In your folder

**Comment by panoszik** [comment]
I tried this before but it gives this error 
![image](https://user-images.githubusercontent.com/20783587/83856557-685eee80-a722-11ea-98b3-a465444832ba.png)
![image](https://user-images.githubusercontent.com/20783587/83856596-77de3780-a722-11ea-8207-fcee4067f8c6.png)
Sorry for the inconvenience and your time

**Comment by panoszik** [comment]
![image](https://user-images.githubusercontent.com/20783587/83857017-0d79c700-a723-11ea-96e0-1735915bf110.png)

![image](https://user-images.githubusercontent.com/20783587/83857074-1c607980-a723-11ea-9a95-b55fe20685cd.png)

**Comment by lukaarma** [comment]
I had to remove your images because there was your Auth token, so better save than sorry :D

Happy to help, no worries

You seem to keep receiving a 403 forbidden, so you cannot access those videos.
You can play them in the browser if you wanted, or even there it doesn't allow you?

**Comment by panoszik** [comment]
Okay, there where 2 videos that i did not had access to it seems, so that did the trick i removed them and now it can download..Thanks for your help!

**Comment by lukaarma** [comment]
Always happy to help, have a nice day!
