### ISSUE TITLE
Where do I exactly put username?

### ISSUE THREAD

**Issue by Eniff** [snobu/destreamer#16]
Sorry, I'm new to programming and typescript files.

Which is the username constant?
I have seen you wrote this in the file:

// Type in your username here (the one you use to
// login to Microsoft Stream).
const args: string[] = process.argv.slice(2); // TODO: Remove this

Is this it? How should I give my username to it (what format)? Sorry if this is a really obvious question but I couldn't figure it out.

**Comment by snobu** [comment]
Right, sorry for the confusion, i have removed that part from the README.
You don't need to do any of that, just pass `--username someone@example.com` to the command line when you run destreamer.

**Comment by Eniff** [comment]
Alright, thanks for the clarification! I only asked because I thought there was a way to store a username in the program so I don't have to type it every time. But it doesn't really matter. Really cool project, thanks for the development, it is really useful in these times!
