### ISSUE TITLE
Download size

### ISSUE THREAD

**Issue by Mahanotrahul** [snobu/destreamer#160]
It will be better if the size of the video is printed on the terminal before starting the download and also while the video is being downloaded in the format - [downloaded size] / [total download size]
With the simulate -s also, download size must be shown.

**Comment by lukaarma** [comment]
I could look into that, but I you want to have choice over the resolution (and the download size indirectly) you can take a look at the aria2c branch

**Comment by snobu** [comment]
Since all we do is fetch segments there's no way to know the total file size upfront. We could do some wild approximation based on video length but i'd rather not. Actially we kinda already do that for the progress bar with varying degreea of succes :)

**Comment by lukaarma** [comment]
@snobu we could do a very good estimate of the size with in really convoluted way: grab the playlist => grab 1 item for video and 1 for audio and find out they sizes => multiply that size by the number of segments => PROFIT?

But i't nothing important and it's a bit elaborate just for the filesize

**Comment by snobu** [comment]
Aren't all videos on MSStream encoded with variable bit rate? I'm just assuming since that's the norm and that would make the final size a gamble.
