### ISSUE TITLE
Unknown FFmpeg error

### ISSUE THREAD

**Issue by Ergasta99** [snobu/destreamer#161]
Unknown FFmpeg error
when i download with latest version

**Comment by lukaarma** [comment]
check if you have the last ffmpeg version installed please.

If you have the latest version or the error keeps happening even after updating please check that when it errors out there should be some red text before the 'Unknown FFmpeg error' in red background, could you copy and paste it?

**Comment by Ergasta99** [comment]
Hello lukaarma,
>check if you have the last ffmpeg version installed please.
updated
it works
thanks!
best regards
