### ISSUE TITLE
Feature Request : Automated Password filling and 2FA pages passing support

### ISSUE THREAD

**Issue by fxerkan** [snobu/destreamer#162]
First of all I want to thank you for advance and this project, it is really works very well.

This is not an issue, actually it is New Feature request or suggestion to your code.

I made some changes at your destreamer.js file to fill the Password and pass the Stay Signed in pages automatically like below.

```javascript
    //Username
    await page.waitForSelector('input[type="email"]');
    if (username) {
        await page.keyboard.type(username);
        await page.click('input[type="submit"]');
    }
//new added lines to fill password and passing the stay signed page
	//Password
	await utils_1.sleep(1500);
	await page.waitForSelector('input[type="password"]');
	console.log('waiting for password');
	if (passwd) {
		await page.keyboard.type(passwd);
		console.log('password entered');
		
		await page.click('input[type="submit"]');
		console.log('submit click');
	}
	//Stay signed in
	await utils_1.sleep(1500);
	await page.waitForSelector('input[type="submit"]');
	await page.click('input[type="submit"]');
	console.log('stay signed submit click');
```

and it works as expected :-)

but I have a Stream account which needs 2 Factor Authentication(2FA) and has some different pages like below which I couldn't succeeded to click/fill these pages because of I don't know javascript.

```javascript
	//Sign in to your xxxxxx Corporate account page
	await utils_1.sleep(1500);
	console.log('waiting signinsmartcard page');
//there is a button and a hyperlink in this page which button's id=signinsmartcard and hyperlink's class=actionLink (I want to click)
	await page.waitForSelector('input[id="signinsmartcard"]'); //NOT working
	//await page.waitForSelector('input[type="submit"]'); //NOT working 
	console.log('signinsmartcard page found');
	
	await page.click('input[class="actionLink"]'); //NOT working
	console.log('clicked to sign in with username-password hyperlink');
	
	//Password page appear when I clicked the above hyperlink - works well
	await utils_1.sleep(1500);
	await page.waitForSelector('input[type="password"]');
	console.log('waiting for password');
	if (passwd) {
		await page.keyboard.type(passwd);
		console.log('password entered');
		
		await page.click('input[type="submit"]');
		console.log('submit click');
	}
	
	//For security reasons, we require additional information to verify your account page - this page is redirects to 2FA Mobile App unfortunatelly there is no way to automate it and I had to approve this request from mobile app
	await utils_1.sleep(1500);
	await page.waitForSelector('input[actionLink="WindowsAzureMultiFactorAuthentication"]');
	await page.click('input[actionLink="WindowsAzureMultiFactorAuthentication"]');
	console.log('Sign in with your phone or token device hyperlink click');
	
	//Stay signed in - works well
	await utils_1.sleep(1500);
	await page.waitForSelector('input[type="submit"]');
	await page.click('input[type="submit"]');
	console.log('stay signed submit click');
```

Can you please help about this issue and add automated Password filling, Stay Sgined, 2FA Pages passing mechanism to your code?

**Comment by lukaarma** [comment]
> Can you please help about this issue and add automated password filling

Yes we could but it's not a priority right now, we may do that if and when we also implement the system key-chain to save them

> Stay signed in

I may do this in the new 401_fix branch since that is also responsible of refreshing the session if you tell you browser to remember you

>2FA 

This will never (or very very very unlikely) be implemented since there are so many different 2FA systems or other tennants login procedures that we cannot forecast all the possibilities

<br><br>
> I have a Stream account which needs 2 Factor Authentication(2FA) and has some different pages like below which I couldn't succeeded to click/fill these pages because of I don't know javascript.

I really can't help you with this one since I would need a way to access the 2FA page to help you in some way
