### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by jeilopez1** [snobu/destreamer#165]
![image](https://user-images.githubusercontent.com/28574377/85818703-e79a7d80-b736-11ea-8e63-a355642ffa92.png)

#!/usr/bin/env bash
NODE_VERSION=$(node --version)

if [[ $NODE_VERSION == "v8."* ]]; then
    node build/src/destreamer.js "$@"
else
    node --max-http-header-size 32768 build/src/destreamer.js "$@"
fi

and 

![image](https://user-images.githubusercontent.com/28574377/85819033-ea49a280-b737-11ea-89c5-852b2386a259.png)

no estoy abriendo el cmd como administrador.

**Comment by lukaarma** [comment]
You have to run Destreamer as a regular user, don't run as an Administrator

**Comment by jeilopez1** [comment]
@lukaarma  
i am not using cmd as administrator

**Comment by lukaarma** [comment]
Are you absolutely sure about that @jeilopez1?
Could you try and see if powershell gives you the same issue?

**Comment by snobu** [comment]
Maybe you have UAC disabled thus running as Administrator all the time? Don't know if you can still do that in Windows nowadays but still.

**Comment by jeilopez1** [comment]
@lukaarma   @snobu   Hello friends, thanks to your help, I managed to download the video, make the modifications in UAC and when I run the cmd, the same administrator error appeared, but when I run the PowerShell it worked ...

![2](https://user-images.githubusercontent.com/28574377/85936190-c57f3780-b8bd-11ea-9a7c-466a35bd6b9b.png)


I have no idea what the problem would be, I had already run the PowerShell before and the same error had appeared.

downloading...
Thank you...
![ultimo](https://user-images.githubusercontent.com/28574377/85936192-cca64580-b8bd-11ea-959b-627195aeb7fe.png)
