### ISSUE TITLE
Get the video stream

### ISSUE THREAD

**Issue by cptloc** [snobu/destreamer#167]
Hi,

you can have the link to the stream instead of downloading the video. I would have to take the link of the video to put it into another app (Moodel - H5P). If I take the download link it works but it's only valid for 3 days.

I saw that for MS Stream this feature is coming in this year's Q4 (API Stream) but I need it now.

**Comment by lukaarma** [comment]
I'm not sure if I understand what you want...You want the link to the HLS stream to use it somewhere else?

**Comment by cptloc** [comment]
yes, I would like to use the stream in somewhere else (maybe with the user logged in MS Stream for the auth).

**Comment by lukaarma** [comment]
If you use the '-s' (simulate) flag after Destreamer fetches all the info it will print them and there you can find the HLS link but be aware that you must have an authenticated session token to fetch the keys needed for the decoding of the stream

**Comment by lukaarma** [comment]
If you like to share more details I could try and expose the needed elements from destreamer.ts in a separate fork/repo so that you can use them in your project @cptloc

**Comment by lukaarma** [comment]
closing as inactive
