### ISSUE TITLE
out of curiosity

### ISSUE THREAD

**Issue by gelmanovic** [snobu/destreamer#168]
How do I get videos URLs from site when I'm located in the teams' group page? There's no trace in the HTML.
I wanted to scrape all links without having to copypaste.
Might be worth saying that I want them to be in publishing chronological order.

**Comment by lukaarma** [comment]
I guess and I could take a look if I can come up with something

**Comment by gelmanovic** [comment]
Never mind. I've managed to go to chrome inspection panel and there it showed.
thanks anyway

**Comment by lukaarma** [comment]
Well I'm doing it anyway :P I enjoy coding and that is a good idea, scrape the page if it's detected as "not a video"

**Comment by gelmanovic** [comment]
![luke2](https://user-images.githubusercontent.com/57871063/85956135-0d689200-b984-11ea-92f7-2dc8c136c834.png)
![luke1](https://user-images.githubusercontent.com/57871063/85956136-0e012880-b984-11ea-9e1f-db6ee53de288.png)

In the black circle there is the main tag containing all video infos, in the red circle there is a given video tag
In word I then look up for right that string in the text (there are duplicate links for the same video and this search string returns only one for each video). 
I'm afraid though that I have to manually scroll all the page in order to let it dispaly all videos, otherwise they won't show up in the HTML. Of course I also have to order them the way I want prior to go to the HTML

**Comment by lukaarma** [comment]
I found a better way to get all the videos though the API, leave me this evening and I should have something that works

I'm afraid I didn't quite understand what was that you wanted to do with they order, can you please explain better?

**Comment by gelmanovic** [comment]
Hey man, thanks a lot but I'm done already, don't want to bother you.
The thing is, since they are saved with no meaningful names, I want to be sure I download them in the order they were uploaded so I keep the sequence when watching them offline. and thus I create the URLs text file with the ordered links so I know the order based on the time the downloaded video was created on my pc.

Insomma, per avere le lezioni ordinate cronologicamente, le scarico in quell'ordine così poi ordino i video in explorer in base alla data di creazione del download e le rinomino in bulk con numerazione progressiva.

**Comment by gelmanovic** [comment]
Ur my superhero. 😗
