### ISSUE TITLE
No video output

### ISSUE THREAD

**Issue by Nosh118** [snobu/destreamer#169]
When I run the program with destreamer.sh -i "https://web.microsoftstream.com/video/xxxxx" --format mp4 --outputDirectory Users\xxxxxx it doesn't output the video file when the progress bar completes

**Comment by Nosh118** [comment]
My bad, I think I'm just stupid
I'll close this if I fix it

**Comment by Nosh118** [comment]
Was using .sh instead of .cmd, my bad

**Comment by Nosh118** [comment]
It says that the download finished in the right directory, I corrected my multiple issues but now I'm lost, there's no file there

**Comment by snobu** [comment]
Just don't specify -o or --outputDirectory at all, that guarantees the output to be under a `videos` directory from where you run destreamer.

**Comment by lukaarma** [comment]
@Nosh118 which version of Destreamer are you using?

**Comment by Nosh118** [comment]
Downloaded it today, so the latest

**Comment by Nosh118** [comment]
Have realised that the /videos directory was in the destreamer root and that it apparently did download once I fixed all my other issues, thanks for the help
