### ISSUE TITLE
Browser issue - Error code 0x20400003

### ISSUE THREAD

**Issue by dexter93** [snobu/destreamer#17]
![image](https://user-images.githubusercontent.com/1979042/77662632-ccc43b80-6f84-11ea-9829-a28d65fbd724.png)

attempting this on gentoo with node v12.14.0, ffmpeg 4.2.2, latest youtube-dl

`Output Directory: vids/
Video/Audio Quality: 
Using youtube-dl version 2020.03.24
Using ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
Launching headless Chrome to perform the OpenID Connect dance...
Navigating to STS login page...
We are logged in. Sorry, i mean "you".
(node:134608) UnhandledPromiseRejectionWarning: TimeoutError: Navigation timeout of 30000 ms exceeded
    at /home/dexter/test/destreamer/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21
  -- ASYNC --
    at Frame.<anonymous> (/home/dexter/test/destreamer/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/home/dexter/test/destreamer/node_modules/puppeteer/lib/Page.js:672:49)
    at Page.<anonymous> (/home/dexter/test/destreamer/node_modules/puppeteer/lib/helper.js:112:23)
    at rentVideoForLater (/home/dexter/test/destreamer/destreamer.js:79:20)
(node:134608) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
`
Any thoughts?

**Comment by dexter93** [comment]
update: reinstalled all node deps and disabled sandbox. The error screen persists, but it might throw one frame and then the error screen.

It seems to be a hit and miss on picking up the cookies, as it will occasionally work and download a file, or fail miserably with a timeout. I'm still not sure how to go about debugging, since it seems that when it works, it works well

**Comment by snobu** [comment]
Just ignore that browser error thing. destreamer only needs the cookies from the browser session.
Pull the latest code, there were some improvements in how we fetch the HLS URL. Don't forget to do a `npm run -s build` before running destreamer. Also make sure your video doesn't have any trailing parameters as in `?something=something`.

**Comment by snobu** [comment]
Things should be much improved now. git pull, transpile and try again, if it's still failing for you please reopen the issue.
