### ISSUE TITLE
Destreamer is being throttled

### ISSUE THREAD

**Issue by lukaarma** [snobu/destreamer#170]
![image](https://user-images.githubusercontent.com/27893195/86507878-c511ff80-bddb-11ea-8e38-eaf05263de79.png)

As you can see in this image Destreamer is being throttled after 10/12 video info fetch in the span of 1/5 sec (I tried with and without a 500ms delay between each fetch), then after a hard reset from the server we can fetch 5 (without delay) to 10 (with 500ms delay) videos info before another hard reset from the server (longer this time)

From my testing it seems that there's a cap of request/sec (or short ammount of time) and a cap on request/min

@snobu Any advice?

**Comment by lukaarma** [comment]
Fixed changing the video info gathering from bulk to single video before before each download

**Comment by lukaarma** [comment]
But testing is still a PITA...

Leaving this here so that anybody can see this before opening a new issue

**Comment by Kizuna-Meraki** [comment]
I tried to download a 3h04m14s video lecture from Microsoft Streams today and destreamer stopped twice at 45% complete and after a reboot, stopped at 94% complete. (Same video link for all three attempts.)

Via brew, I upgraded ffmpeg from 4.2.3 to 4.3.1. Now running destreamer and will update this comment if successful or unsuccessful.

**Comment by lukaarma** [comment]
Closing, see #203 for discussion
