### ISSUE TITLE
ERROR - stdout is not a tty

### ISSUE THREAD

**Issue by Tenshey** [snobu/destreamer#171]
Seems to be not working with powershell at windows 10 idk why, but when I run at CMD it works perfectly. Any ideas?
![image](https://user-images.githubusercontent.com/9168938/86837940-e60a7700-c09f-11ea-9089-759cf281c64d.png)

**Comment by lukaarma** [comment]
Ok, this is not a Destreamer issue, it's something to do with your node/Powershell.
I can't help you further without any more insight on how is your system setup :/

**Comment by snobu** [comment]
I've seen this before. It's the terminal not the shell. Use the native Windows one or Windows Terminal (from Store) for best results.

**Comment by CrownKingClown** [comment]
Had the same problem here. 
If you are using cmq just omit .sh on the comand 

destreamer -i "https://web.microsoftstream.com/video/videocodehere"

**Comment by lukaarma** [comment]
> Had the same problem here.
> If you are using cmd just omit .sh on the comand
> 
> destreamer -i "https://web.microsoftstream.com/video/videocodehere"

That work because doing so calls destreamer.cmd, the proper script for cmd on Windows, destreamer.sh is meant for *nix Systems. Just wanted to let you know :)

**Comment by lukaarma** [comment]
Closing as inactive
