### ISSUE TITLE
Bulk download of many videos with same title

### ISSUE THREAD

**Issue by beppe9000** [snobu/destreamer#173]
I am trying to download my ms teams recorded meetings in bulk. the problem is that the person that recorded it kept the same name for all the videos. is there a way to have destreamer automatically rename the newer ones Meeting(1), Meeting(2) and so on?

**Comment by lukaarma** [comment]
Destreamer should already add a progressive number at the end of videos that already exist in the folder, it's not working that way?

**Comment by beppe9000** [comment]
My bad, was using the first version 👍
