### ISSUE TITLE
I am new to GitHub and want to know how to download my Assembly. Please help me.

### ISSUE THREAD

**Issue by yasfaz11** [snobu/destreamer#174]
## PLEASE NEVER PASTE YOUR ACCESS TOKEN INTO A GITHUB ISSUE AS IT MAY CONTAIN PRIVATE INFORMATION

When you paste in output from destreamer, locate your access token (it looks like this: `Authorization: Bearer eyJ....<a lot more base64 encoded text>.....`) and redact it.

**Comment by lukaarma** [comment]
Follow the instructions in the README, if you search on YouTube there's also a "tutorial" on our tool
