### ISSUE TITLE
change date format in files to make it easeier to order

### ISSUE THREAD

**Issue by beppe9000** [snobu/destreamer#175]
instead of DD-MM-YYYY I suggest YYYY-MM-DD so one could use sorting when browsing files

**Comment by snobu** [comment]
Good suggestion. Meanwhile, feel free to send in a pull request if you wish.

**Comment by lukaarma** [comment]
We could add a title template so that we can let the user choose how to build their title with things like 'title', 'author', 'published date', ecc...

**Comment by beppe9000** [comment]
basically a format argument , to be used like `--format="@title - @upload_time"`

**Comment by lukaarma** [comment]
Yeah like that or we can take inspiration from youtube-dl idk...

**Comment by snobu** [comment]
This project is slowly becoming the FFmpeg of corporate video :) We should probably change our tagline.

**Comment by beppe9000** [comment]
also education :P

**Comment by lukaarma** [comment]
closed by #164
