### ISSUE TITLE
[BUG] make file names more unique

### ISSUE THREAD

**Issue by beppe9000** [snobu/destreamer#176]
I believe appending an unique identifier such as the video id at the end of the file name will prevent such a situation (resulting in download of only one of two different videos with same name in the same day) when resuming a download with `--skip`. Maybe make it an optional  `--append-id` parameter or something like that.

The ideal file name format for me would be `[yyyy-mm-dd] - [title] - [id].mkv`, if there was a way to specify it.

![image](https://user-images.githubusercontent.com/6625123/87166728-42ea7500-c2cc-11ea-8ced-bff5ecd79ecc.png)

**Comment by lukaarma** [comment]
I see where you are coming from.. Right now I'm working on a big update to improve download speeds drastically but as soon as I'm done with that I'll look into this.
But I don't think that using the video GUID it's the way to go, that would be 32 extra chars, a bit too much in my opinion

**Comment by beppe9000** [comment]
Thinking about it... I believe appending the publish time expressed as a unix timestamp would be the most practical way to add uniqueness to all video with the same name. `1594465752` is shorter than ` 51357782-d2fd-4b1d-a205-4f5ea082f679- 51357782-d2fd-4b1d-a205-4f5ea082f679`....

**Comment by lukaarma** [comment]
That's for sure better than using the Guid...since I don't have any better idea I'd say that for now we'll use the timestamp.
If you are going to work on this please use the "code_refactoring" branch as a base

**Comment by beppe9000** [comment]
sure 👍

**Comment by snobu** [comment]
As the owner of the video (uploader or whatever it's called), you still can't make a video available for download for a group (or anyone besides yourself), can you?

![bacon](https://user-images.githubusercontent.com/6472374/87416365-45ecaa80-c5d7-11ea-9af6-b4dc6adf4975.jpg)

**Comment by snobu** [comment]
@lukaarma suggested having a title format parameter on a different thread, i think that's the right way to go and we only need to support Title, Owner (Author) and Publish Date.

**Comment by snobu** [comment]
Sorry, that was @beppe9000 that suggested it. Credit where credit is due.

**Comment by beppe9000** [comment]
> As the owner of the video (uploader or whatever it's called), you still can't make a video available for download for a group (or anyone besides yourself), can you?

Well, in my case (university) both students and professors can record calls on Teams, but they are uploaded to Streams only if the record button was pressed by a professor. So I just discovered that button exists... lol

**Comment by lukaarma** [comment]
closing, moving discussion at #190
