### ISSUE TITLE
Concerns

### ISSUE THREAD

**Issue by Alex16324** [snobu/destreamer#177]
Hi! I´m actually curious: is there a way for the downloads to be trackeble? ´Cause I was downloading and all the sudden, by almost the end of the download, it came an error of "timeout". But a huge ammount of script was made in red. And it has never happened before. So, is there a way for someone to stop the downloading from the outside?

**Comment by snobu** [comment]
No. I mean yes but who would put in the effort to do any of that? Microsoft has bigger fish to fry. The red block of text usually has an error message at the top. That should tell you why it happened, or at least, what happened.
