### ISSUE TITLE
Download does not start

### ISSUE THREAD

**Issue by abrarkhan87** [snobu/destreamer#178]
On some recent videos the download does not start it shown the progress at 0 and does nothing. Works on some other older videos.

![image](https://user-images.githubusercontent.com/52589431/87394361-bfc56980-c5c0-11ea-81e6-b91ca7942949.png)

Thank you for the help.

**Comment by lukaarma** [comment]
Have you tried updating to the latest version of Destreamer?

**Comment by lukaarma** [comment]
Closing as inactive
