### ISSUE TITLE
First time login with '-k' fails evaluation

### ISSUE THREAD

**Issue by lelobirchal** [snobu/destreamer#182]
Hello,
I can not login in my Microsoft stream account neither with or without -u key. Is there a way to pass the password with -u key?

I'm using MAC OS and I always got the following:

MBP-de-birchal:destreamer birchal$ ./destreamer.sh  -u XXXXXX@sga.pucminas.br -i https://web.microsoftstream.com/video/4645b55e-3b13-4550-bc48-a205ab8e4897
Using ffmpeg version 4.3.1-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2020 the FFmpeg developers

Username: XXXXXX@sga.pucminas.br

[WARNING] .token_cache not found. 

Launching headless Chrome to perform the OpenID Connect dance...
Navigating to login page...
We are logged in.

[FATAL ERROR] Could not evaluate sessionInfo on the page 

Thanks,

Marco A S Birchal

<br><br>

#### EDIT: for anyone working on this it's because we wait for the URL to include 'microsoftStream.com' or something similar and during the login procedure we already have a page like that so we should also check that there is something else unique to the login URL so that we can add a negative check for that
_Luca

**Comment by snobu** [comment]
Is this with the latest version of the code? We pushed a big overhaul last night, if your code is older than that please do a git pull, rebuild and try again.

**Comment by snobu** [comment]
Found the problem, the first time you login you will get that error, simply try again and it will work. There's a small bug in the token cache logic for new logins, trying to track this down now.

@lukaarma - this only happens for first logins (no .chrome_data or .token_cache):
```
[WARNING] .token_cache not found.

Launching headless Chrome to perform the OpenID Connect dance...
Navigating to login page...
We are logged in.


[FATAL ERROR] Could not evaluate sessionInfo on the page
```

2nd time around seems to be fine.

**Comment by lukaarma** [comment]
@snobu l have some work to do irl™ today, will look into it tomorrow

**Comment by sblaker** [comment]
I have the same issue

**Comment by lukaarma** [comment]
@snobu I have some new unwanted features in Life™, this update and all other bug hunting will have to wait sorry :/
