### ISSUE TITLE
ffmpeg Invalid data found when processing input

### ISSUE THREAD

**Issue by cswalke1** [snobu/destreamer#183]
I'm using opensuse Leap 15.2.  destremer worked fine in opensuse Leap 15.0.

ffmpeg -v
ffmpeg version 3.4.4 Copyright (c) 2000-2018 the FFmpeg developers

this ffmpeg is from pacman repo

this is what happens:

./destreamer.sh -i https://web.microsoftstream.com/video/xxxx-xxx-x-x-x
Using ffmpeg version 3.4.4 Copyright (c) 2000-2018 the FFmpeg developers

Access token has expired.
Launching headless Chrome to perform the OpenID Connect dance...
Navigating to login page...
We are logged in.
Wrote access token to token cache.
At this point Chromium's job is done, shutting it down...

Fetching metadata...
Fresh access token dropped into .token_cache

Downloading Video: Meeting with XXXXXXX

Spawning ffmpeg with access token and HLS URL. This may take a few seconds...

progress [░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0% 0 0s

ffmpeg returned an error: https://usea-1.api.microsoftstream.com/api/videos/manifest?api-version=1.0&playbackurl=https://streamusea1su011.azureedge.net/xxxxxxxx-xxxx-xxxx/xxx-xxxxxx.ism/manifest(format=m3u8-aapl): Invalid data found when processing input

**Comment by snobu** [comment]
Your ffmpeg is a little old, try with a recent version (4.2 or above).

**Comment by cswalke1** [comment]
I downloaded ffmpeg-4 package from opensuse leap 15.2 multimedia:libs repo.  Currently at 4.3.1 and I get 
"ffmpeg returned an error:  Last message repeated 1 times

Unknown FFmpeg error"

Trying to build from source at the moment to see if that helps

**Comment by cswalke1** [comment]
I checked out ffmpeg n4.2.1
now I get:
./destreamer.sh -i https://web.microsoftstream.com/video/XXXXXX-XXXXX-XXXXXX
Using ffmpeg version n4.2.1 Copyright (c) 2000-2019 the FFmpeg developers


Access token still good for 27 minutes.

Fetching metadata...

Downloading Video: Meeting with XXXXXXX

Spawning ffmpeg with access token and HLS URL. This may take a few seconds...
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄

progress [░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0% 0 0s

ffmpeg returned an error: Did you mean file:https://usea-1.api.microsoftstream.com/api/videos/manifest?api-version=1.0&playbackurl=https://streamusea1su011.azureedge.net/xxxx-x-x-x-xxxxxx/x-xxxxxxxxxxxxxxxxxxxxxxx.ism/manifest(format=m3u8-aapl)?



Unknown FFmpeg error

**Comment by cswalke1** [comment]
I also tried n4.3.1...same message

**Comment by lukaarma** [comment]
I'm sorry for the late response, did you try again with the same issue?

**Comment by cswalke1** [comment]
I rebuilt destreamer.sh from the latest code and am still getting the same message as https://github.com/snobu/destreamer/issues/183#issuecomment-662235045

I might as well add, I rebooted into my older opensuse 13.0 to try it there since it was working there before.  It is no longer working there either. Something on microsoft streams has changed that destreamer is not picking up.

**Comment by cswalke1** [comment]
I really appreciate this tool, so if I can be of any help in fixing the problem let me know.  I'm currently using simplescreenrecorder to just "tape" the stupid video.  oh well.

**Comment by snobu** [comment]
I would go one step further and test with a static build of ffmpeg (so you don't touch any OpenSuse dependency).https://johnvansickle.com/ffmpeg/

**Comment by cswalke1** [comment]
that did the trick, thank you so much!!
