### ISSUE TITLE
Error when trying to download with links in a file

### ISSUE THREAD

**Issue by RiccardoJR** [snobu/destreamer#184]
Hi, after the update 2.1.0 when i try to download videos from a file (".txt"). It gives me this error:

[ERROR] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Object.join (path.js:375:7)
    at D:\destreamer-master\build\src\VideoUtils.js:78:64
    at Array.forEach (<anonymous>)
    at Object.createUniquePath (D:\destreamer-master\build\src\VideoUtils.js:75:12)
    at downloadVideo (D:\destreamer-master\build\src\destreamer.js:101:33)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

how can i fix this?

**Comment by s-monti97** [comment]
I got the same issue. Besides, when chromium get opened, it gets crashed in the next 10-15 seconds and it returns the following error.

`[ERROR] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
at validateString (internal/validators.js:120:11)
at Object.join (path.js:375:7)
at D:\destreamer-master\build\src\VideoUtils.js:78:64
at Array.forEach ()
at Object.createUniquePath (D:\destreamer-master\build\src\VideoUtils.js:75:12)
at downloadVideo (D:\destreamer-master\build\src\destreamer.js:101:33)
at processTicksAndRejections (internal/process/task_queues.js:97:5)`

**Comment by lukaarma** [comment]
could you try to run with the --verbose/-v flag and paste here your output please? censor as you like usernames or real folder names with fake ones if you like :)

**Comment by RiccardoJR** [comment]
[VERBOSE] Session and API info
         API Gateway URL: https://euwe-1.api.microsoftstream.com/api/
         API Gateway version: 1.4-private

Parsing input file

[VERBOSE] List of GUIDs and corresponding output directory
        https://web.microsoftstream.com/video/X => undefined

The error is the same as above

**Comment by lukaarma** [comment]
would you mind sharing the command you are launching and the input file? I can't figure out why it's resulting in an `undefined` directory

**Comment by RiccardoJR** [comment]
D:\destreamer-master>
[algebra.txt](https://github.com/snobu/destreamer/files/4956400/algebra.txt)
destreamer.cmd -k -v -f algebra.txt
Using ffmpeg version git-2020-07-16-d11cc74 Copyright (c) 2000-2020 the FFmpeg developers

Access token still good for 52 minutes.


[VERBOSE] Session and API info
         API Gateway URL: https://euwe-1.api.microsoftstream.com/api/
         API Gateway version: 1.4-private

Parsing input file

[VERBOSE] List of GUIDs and corresponding output directory
        https://web.microsoftstream.com/video/61659c80-3ec5-4663-8f44-e810187b288d => undefined

**Comment by lukaarma** [comment]
Thank you very much, found the bug thanks to you file @RiccardoJR! will push a fix as soon as I can
