### ISSUE TITLE
Error: Failed to launch the browser process! spawn

### ISSUE THREAD

**Issue by omkar4345** [snobu/destreamer#185]
Dear Team,

Iam getting below error after running destreamer command as suggessted in procedure.

Created directory: videos
Using ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers

[WARNING] .token_cache not found.

Launching headless Chrome to perform the OpenID Connect dance...

[ERROR] Error: Failed to launch the browser process! spawn /home/ansadm/destreamer/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome ENOENT

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/ansadm/destreamer/node_modules/puppeteer/lib/Launcher.js:750:14)
    at ChildProcess.<anonymous> (/home/ansadm/destreamer/node_modules/puppeteer/lib/Launcher.js:741:65)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

Regards,
Omkar

**Comment by lukaarma** [comment]
It seems that it's having trouble finding the path of chromium...
If you want to try and comment out this line
https://github.com/snobu/destreamer/blob/78e5818cc3d6bca1dd4b3de761b56c47fefa15f2/src/destreamer.ts#L51
and this one
https://github.com/snobu/destreamer/blob/78e5818cc3d6bca1dd4b3de761b56c47fefa15f2/src/TokenCache.ts#L60
rebuild and launch again and let me know how it goes

Sorry if I don't debug this one further but I have no time now :/

**Comment by HaarisIqubal** [comment]
I still not working i tried both these method

**Comment by lukaarma** [comment]
Did chromium launch and were you able to complete the login procedure?

**Comment by HaarisIqubal** [comment]
Yes

**Comment by lukaarma** [comment]
did you use the '-k' option to use the 'remember me' function during login?

**Comment by HaarisIqubal** [comment]
NO its not working yet

**Comment by lukaarma** [comment]
If you try again do you stil have this problem

`at onClose (/home/ansadm/destreamer/node_modules/puppeteer/lib/Launcher.js:750:14)
at ChildProcess.<anonymous> (/home/ansadm/destreamer/node_modules/puppeteer/lib/Launcher.js:741:65)
at ChildProcess.emit (events.js:314:20)
at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
at onErrorNT (internal/child_process.js:468:16)
at processTicksAndRejections (internal/process/task_queues.js:80:21)`

or this one?

`[FATAL ERROR] Could not evaluate sessionInfo on the page`

**Comment by omkar4345** [comment]
Dear All,

The issue due to chromium. Chromium was not getting downloaded with the given procedure and not given error during the same. I noticed chromium directory was not present under puppeteer directory. 

Seems it was due to my internet restrictions. Chromium started downloading after I refired the "npm i puppeteer" command.

Thanks for support,

Cheers........
Omkar
