### ISSUE TITLE
My artwork here!

### ISSUE THREAD

**Issue by peppelongo96** [snobu/destreamer#187]
Hi! I compiled a specific version of Destreamer useful for University of Calabria users. Looks up [here](https://github.com/peppelongo96/UnicalDown) and feel free to mention it and suggest features or get inspiration from :)

**Comment by lukaarma** [comment]
I see that it's based on polidown, if you want we have just released 2.1 that should let the user refresh the session so that it won't crash mid-download and I'm working on a complete implementatiom of aria2c with rpc-json over websoket for better reliability over spawning aria2c as a child process

Take a look at out refresh logic and copy as you like :) I'll try to remember to add your link to the reasons, ping me if I forget

**Comment by lukaarma** [comment]
Or if you want I can help you move the uniCal login logic over to Destreamer so that you have a more solid base to start and expand with new features

**Comment by lukaarma** [comment]
Let me know if you need anything!

**Comment by peppelongo96** [comment]
@lukaarma thanks man! I had a look of your work on Destreamer and what you are planning and that is absolutely fantastic! But rebasing UnicalDown on Destreamer properly developing model is a really hard work that not worth it. Unical has not too much aware users that could appreciate the work.
Howewer, in [important notes](https://github.com/peppelongo96/UnicalDown#important-notes), I wrote something about what I am really interested for (like a personal challange):
- session cookies expiring, that doesn't permit consecutive downloads for more then 1 hour (sincerely, I didn't understand if you found a way properly for this with the newer version);
- avoid PC auto suspend mode. I tried different ways and npm packages that heavily increased the package weight... and they clearly are not the right way to go.
Feel free to help me if you have some suggestion :)

**Comment by lukaarma** [comment]
> avoid PC auto suspend mode.

This should be left to the user: they can change their power settings but there is no way to circumvent a system sleep from the nodejs sandbox

>session cookies expiring

First order of business is that I suggest you should change from session cookies, that are extracted unreliably in polidown and switch to session eval in the page like we do
Second I solved (I hope) the refresh session problem by letting chrome create a 20MB~ cache folder and after the first login with "remember me" from the user every time we launch the browser with that cache the login is automatic
It's a quick hack to make this work but it's very reliable from what I can see
When I'll have more time (after aria2c) I'll play some more with the cookies and we'll see if I can come up with something more elegant
Here is the refresh session function
https://github.com/snobu/destreamer/blob/78e5818cc3d6bca1dd4b3de761b56c47fefa15f2/src/TokenCache.ts#L56
And here is the folder we pass to puppeteer
https://github.com/snobu/destreamer/blob/78e5818cc3d6bca1dd4b3de761b56c47fefa15f2/src/destreamer.ts#L53
Check them out and maybe they can inspire you to create something similar

**Comment by peppelongo96** [comment]
@lukaarma okay, got it! I think is something that I can do in not much time. I can adapt your function and also move to session eval. Thanks for all suggestions :) and remind to pin my repo if you feel!

**Comment by peppelongo96** [comment]
@lukaarma EDIT: I was looking for some way to implement your solution about session exipiring. It requires a total re-implementation of user token managment and so good hours to spend on it. I decided to edit my notes in the Readme project file by pinning [your comment](https://github.com/snobu/destreamer/issues/187#issuecomment-662181930). Maybe someone could working on if already has what and how to do.
