### ISSUE TITLE
Error after download about two-three videos from txt file

### ISSUE THREAD

**Issue by s-monti97** [snobu/destreamer#189]
I'm receiving an error after completing two-three video download with -f text file. Cmd returns this error:
Spawning ffmpeg with access token and HLS URL. This may take a few seconds...

```
[WARNING] Got HTTP code 401. Retrying request...

[ERROR] Error: Request failed with status code 401
    at createError (C:\Users\monti\Desktop\destreamer\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\monti\Desktop\destreamer\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\monti\Desktop\destreamer\node_modules\axios\lib\adapters\http.js:236:11)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

Somebody can help?

**Comment by lukaarma** [comment]
Are you using the -k option? If not this is "normal" behaviour because the session token expires after 1 hour

**Comment by s-monti97** [comment]
> Are you using the -k option? If not this is "normal" behaviour because the session token expires after 1 hour

Yes, I'm using: `destreamer.cmd -k -f controlli.txt`

**Comment by lukaarma** [comment]
And you clicked yes at the "remember me" page?

**Comment by s-monti97** [comment]
Yes I did, I can try to re-download repository and launch npm build

**Comment by lukaarma** [comment]
could you please let me know ho long were those videos?

**Comment by s-monti97** [comment]
> Could you please let me know how long were those videos?

Of course, they're about 2-3 hours.

**Comment by lukaarma** [comment]
Before the error in the first message do you remember if there was an image rendered in the terminal or just the text you got?

**Comment by s-monti97** [comment]
I really don't remember. I can do some tests these days so I can try helping you to solve this problem.

**Comment by lukaarma** [comment]
It would be great if you could run again the same command and then the same plus '-x' option and report back what happens
Thanks for your help

**Comment by AnmolTomer** [comment]
Try doing a `git pull` followed by `npm install` and then `npm run build`, I was facing the same issue, but pulling in newer changes from parent repo, fixed it for me.

**Comment by 71walceli** [comment]
I was also facing this. To work around it, I made the following shell script:

```
for u in $urlListFile
do
  echo ------------------------------------------------------------------------------------------------------
  ./destreamer.sh -k -i $u;
  if [[ $? -eq 0 ]]
  then 
    echo DONE $u
  else 
    echo FAILED $u
  fi
  echo
  echo
done
```

I'm using Linux Mint, so this script is for Bash. Hope it helps.

**Comment by lukaarma** [comment]
Closing as inactive
