### ISSUE TITLE
User's video list

### ISSUE THREAD

**Issue by bruno-telstar** [snobu/destreamer#195]
Hi everyone.

Is there a way to get all video URLs a user has using this API?

Best regards,

Bruno

**Comment by lukaarma** [comment]
Hi I'm on vacation, I'll be back next week and I'll look into it

**Comment by snobu** [comment]
This is the API that returns that:
```
https://use2-2.api.microsoftstream.com/api/videos?$top=16&$skip=0&$expand=events&$filter=creator%2Fid%20eq%20%278384<CREATOR_GUID>%27&api-version=1.4-private'
```

Not sure why this would be useful in destreamer as you can already download your own videos (that you've uploaded) from the MS Stream page (go to your video -> three dots -> Download).

**Comment by bruno-telstar** [comment]
> This is the API that returns that (yeah, our old friend `/videos` again but with some ODATA haberdashery):
> 
> Line breaks for readability.
> 
> ```
> https://use2-2.api.microsoftstream.com/api/videos? 
>    $top=16&$skip=0&$expand=events&$filter=creator%2Fid%20eq%20%27<CREATOR_GUID>%27
>    &api-version=1.4-private
> ```
> 
> I don't know why CREATOR_GUID is between %27 (which decodes to `:`), but at this point i'm too afraid to ask.
> 
> Not sure why this would be useful in destreamer as you can already download your own videos (that you've uploaded) from the MS Stream page (go to your video -> three dots -> Download).

Thank you very much, I will try this!

**Comment by lukaarma** [comment]
@bruno-telstar you wanted a list of all the videos the user has uploaded or the user can view?

**Comment by bruno-telstar** [comment]
Hi Luka,

Actually I have to download all the videos recorded by a specific user. So I need the video URLs to donwload it using destreamer.

Thank you!

**Comment by lukaarma** [comment]
Ok, so using the endpoint provided by @snobu should do the trick, let me know if you need help using it

**Comment by lukaarma** [comment]
Closing as inactive
