### ISSUE TITLE
Wish to have feature to use proxy

### ISSUE THREAD

**Issue by popwee416** [snobu/destreamer#196]
Hope we can add feature to support proxy in the command such as --proxy , so that we can use proxy to download in faster speed or when we are in restricted network.

Thanks

**Comment by lukaarma** [comment]
Hi I'm on vacation, I'll be back next week and I'll look into it

**Comment by snobu** [comment]
We have a dependency on ffmpeg, even if we honor proxy settings we would need to find a way to convince ffmpeg to use the same proxy, worse if we add `aria` as a dependency as well... you see where this is going.

Just spin up a VM somewhere where you don't need a proxy to access the internet.

**Comment by lukaarma** [comment]
@snobu if I'm not mistaken aria has proxy settings and when we use aria ffmpeg will be all offline

**Comment by snobu** [comment]
Ah i see. Ok, i'm gonna start a new _Project_ for destreamer v3 and link this issue there. Yes, i guess we could expose aria's configuration somehow (either though a `.destreamer` config file or CLI params) - https://aria2.github.io/manual/en/html/aria2c.html?highlight=all%20proxy#http-ftp-sftp-options
