### ISSUE TITLE
Ability to merge(concat) videos when downloading multiple URLs

### ISSUE THREAD

**Issue by popwee416** [snobu/destreamer#197]
As Teams' recording sucks... a long recording will be break into multiple streams when we pause in the middle, so it is very frequent to download multiple URLs and need to concat manually. For example:

(echo file '1.mp4' & echo file '2.mp4' & echo file '3.mp4' & echo file '4.mp4') | ffmpeg -protocol_whitelist file,pipe -f concat -safe 0 -i pipe: -vcodec copy -acodec copy "result.mp4"

Thus, it will be awesome if we can add one more parameter to destreamer to auto merge the videos after download.

Thanks

**Comment by snobu** [comment]
I like this idea, i'm adding it to our destreamer v3.0 milestone. Can't promise anything but we'll try to have it in v3.
