### ISSUE TITLE
Low download speed

### ISSUE THREAD

**Issue by Anhunghezo** [snobu/destreamer#198]
![image](https://user-images.githubusercontent.com/44318468/89712799-6aad2580-d9bd-11ea-8025-9fbdbb9af6b2.png)

Can you improve the download speed?
My speed is really low.
Normal download speed is 3MB/s in my area.

Can I have multiple cmd windows open at the same time?

**Comment by lukaarma** [comment]
> Can you improve the download speed?

In the next big update there will be a big improvement in the download speed but we don't have an ETA for that update, sorry

> Can I have multiple cmd windows open at the same time?

You sure can

**Comment by Anhunghezo** [comment]
Thank you so much <3
