### ISSUE TITLE
FFmpeg returned an error: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument

### ISSUE THREAD

**Issue by 71walceli** [snobu/destreamer#199]
I was trying to download a Stream video for the first time, but I kept getting this error:

[ERROR] FFmpeg returned an error: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument

[FATAL ERROR] Unknown FFmpeg error 

I just installed FFmpeg and nodejs. 

It does seem to find the videos I indicate.

Fortunately, I hot it to download by doing this, testing with codecs till it worked:

```./destreamer.sh -k -i https://web.microsoftstream.com/video/e3fde0fe-5491-42a8-bf07-15c5c7edfe83 --vcodec libx264 --acodec mp3```

`ffmpeg --version` shows it's '2.8.17-0ubuntu0.1'

I don't understand what is going wrong, it happems probably because I missed something,but don't know what it is.

Thanks for your support

Keep up the good work...!

**Comment by snobu** [comment]
1.Don't use - -vcodec, you don't need to as the videos on MS Stream are already H264 emcoded.
2. Your ffmpeg us very old. Google for ffmpeg static builds and you'll find a newer one for Ubuntu (>v4.2)

**Comment by 71walceli** [comment]
> 1. Don't use `--vcodec`, you don't need to as the videos on MS Stream are already H264 encoded.
Ok
> 2. Your ffmpeg is very old. Google for ffmpeg static builds and you'll find a newer one for Ubuntu (ffmpeg >v4.2)
It's maybe the version of my distro that doesn't let me get the latest. I have Linux Mint 18.3, based on Ubuntu 16.04, I guess... You're right...

```
apk@HP-ProBook-6470b ~/Test $ ffmpeg -v
ffmpeg version 2.8.17-0ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Missing argument for option 'v'.
Error splitting the argument list: Invalid argument
```

**Comment by 71walceli** [comment]
Do you mind explaining how I should use a static build with `destreamer`?

**Comment by snobu** [comment]
Here you go, https://johnvansickle.com/ffmpeg/

Extract and drop the ffmpeg binary somewhere in your PATH. Uninstall the old one via apt remove.

**Comment by 71walceli** [comment]
Thanks for your support. `destreamer` is working fine for me.
