### ISSUE TITLE
Server returned 5XX Server Error reply

### ISSUE THREAD

**Issue by qpham5o4** [snobu/destreamer#201]
I installed everything as expected.  This is on Catalina, latest version.  

The 1st attempt came back with the error 'Server returned 5XX Server Error reply'.  The 2nd attempt I got. 'Invalid data found when processing input [FATAL ERROR] Unknown FFmpeg error'.

**Comment by lukaarma** [comment]
The first error it's nothing we can do something about.
For the second one I suggest you to try and download the most recent ffmpeg (static if possible) and try again

**Comment by qpham5o4** [comment]
Hey,

Thanks for responding quickly.  

I actually do have the latest ffmpeg.  I ran it a 3rd time after opening this issue and it just worked.  3rd times the charm I guess.  Weird.

**Comment by lukaarma** [comment]
Yeah...that ffmpeg "bug" it's something that we couldn't figure out since it's so random and unusual.
Don't worry, I'm (slowly cause no free time) working on v3.0 that will rely on ffmpeg only locally so no more weird bugs

**Comment by lukaarma** [comment]
Closing as solved
