### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by plachta11b** [snobu/destreamer#210]
I did not found official container so there is mine for others who does not like to install any packages except docker and XQuartz. Tested on MACOS and with small modification should work on linux too.

### Dockerfile
```
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    nodejs \
    npm \
    ffmpeg \
    libgtk-3-0 \
    libgdk-pixbuf2.0-0 \
    libcups2-dev \
    libatk-adaptor \
    libnss3-dev \
    x11-apps \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /
RUN git clone https://github.com/snobu/destreamer \
    && git -C /destreamer checkout 7fc7c4733aa9f79a28d163888834c1c01bd93679


WORKDIR /destreamer
RUN npm install

# fix this before code transpilation
# https://github.com/jessfraz/dockerfiles/issues/515
# --ipc=host, --ignore-gpu-blacklist, --use-gl=swiftshader
RUN sed -i "s#'--no-sandbox'#'--no-sandbox','--use-gl=swiftshader'#" /destreamer/src/destreamer.ts

RUN npm run build

WORKDIR /destreamer/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux
RUN chown root:root chrome_sandbox
RUN chmod 4755 chrome_sandbox
RUN cp -p chrome_sandbox /usr/local/sbin/chrome-devel-sandbox

WORKDIR /destreamer
ENV CHROME_DEVEL_SANDBOX=/usr/local/sbin/chrome-devel-sandbox

RUN apt-get update && apt-get install -y --no-install-recommends \
    libxtst6 \
    && rm -rf /var/lib/apt/lists/*

RUN groupadd --gid 5000 ubuntu \
    && useradd --home-dir /home/newuser --create-home --uid 5000 \
    --gid 5000 --shell /bin/sh --skel /dev/null ubuntu
USER ubuntu

# modify with param -e DISPLAY=host.docker.internal:0
ENV DISPLAY=host.docker.internal:0

ENTRYPOINT [ "/destreamer/destreamer.sh" ]
```

### How to use on MACOS
```
xhost +$(hostname)
# open xquartz (Enable 'Allow connections from network clients')
# WARNING: change VIDEO-1 to hash of your video
docker run -v $(realpath ./video):/video -v /tmp/.X11-unix:/tmp/.X11-unix plachta11b/destreamer:7fc7c47 -i "https://web.microsoftstream.com/video/VIDEO-1" -o /video
# or for file list download
docker run -v $(realpath ./video):/video -v /tmp/.X11-unix:/tmp/.X11-unix plachta11b/destreamer:7fc7c47 -f /video/list.txt -o /video
```

Docker hub: https://hub.docker.com/r/plachta11b/destreamer

This tool helped me download some lectures. Thank you :)

**Comment by lukaarma** [comment]
We just need to add your link to the docker hub in the README for this right? There's no real file to create in our repo right?

Sorry for the dumb question but I just know how docker works in theory but I have no idea how you actually start/implement it

**Comment by plachta11b** [comment]
File "Dockerfile" is often placed into project root dir (when owner use docker). Problem is that I am unable to maintain it because I have only temporary access to teams. Link it only as inspiration for others please. It would be great to remove dependency on Xserver by passing password into browser in headless mode. User would be able to download video with only one command.

@lukaarma You are right. I should omit checkout and mention exact commit as tested in comment.

**Comment by lukaarma** [comment]
>  I should omit checkout and mention exact commit as tested in comment.

Could you please post a fixed docker file? :D

@snobu, could you take a look at this and advise on what to do?

**Comment by plachta11b** [comment]
New improved version with latest commit .D

build: `docker build -t destreamer:latest .`

run: `docker run -v $(realpath ./video):/video -v /tmp/.X11-unix:/tmp/.X11-unix destreamer:latest -i "https://web.microsoftstream.com/video/VIDEO-1" -o /video`

Tested without CHROME_DEVEL_SANDBOX and it works. It was added due to error I had got in past due to xquartz not runnning.
<details><summary>Error when xquartz not running</summary>
[ERROR] Error: Failed to launch the browser process!
[21:21:0825/151430.758675:ERROR:browser_main_loop.cc(1512)] Unable to open X display.
[0825/151430.768572:ERROR:nacl_helper_linux.cc(308)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly
</details>



<details><summary>Dockerfile</summary>

```Dockerfile
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
	git \
	nodejs \
	npm \
	ffmpeg \
	libgtk-3-0 \
	libgdk-pixbuf2.0-0 \
	libcups2-dev \
	libatk-adaptor \
	libnss3-dev \
	libxtst6 \
	x11-apps \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /
RUN git clone https://github.com/snobu/destreamer

# This dockerfile was tested with version 7fc7c4733aa9f79a28d163888834c1c01bd93679
# Checkout to commit above in case of broken dependencies
# RUN git -C /destreamer checkout 7fc7c4733aa9f79a28d163888834c1c01bd93679

WORKDIR /destreamer
RUN npm install

# fix this before code transpilation
# https://github.com/jessfraz/dockerfiles/issues/515
# --ipc=host, --ignore-gpu-blacklist, --use-gl=swiftshader
RUN sed -i "s#'--no-sandbox'#'--no-sandbox','--use-gl=swiftshader'#" /destreamer/src/destreamer.ts

RUN npm run build

RUN groupadd --gid 5000 ubuntu \
	&& useradd --home-dir /home/newuser --create-home --uid 5000 \
	--gid 5000 --shell /bin/sh --skel /dev/null ubuntu
USER ubuntu

# modify with param -e DISPLAY=host.docker.internal:0
ENV DISPLAY=host.docker.internal:0

ENTRYPOINT [ "/destreamer/destreamer.sh" ]
```
</details>

**Comment by plachta11b** [comment]
I will do more testing of this feature. How about that GUI and X server dependency? Is there way to pass password without opening browser?

**Comment by lukaarma** [comment]
There's not an efficient way, every Tennant could have different login procedures/multiple logins/2FA
So we have to keep the xServer

**Comment by snobu** [comment]
I'm afraid not. Maybe after we implement keytar but there are a lot of security considerations for that as well, so don't expect anything soon around passing clear text passwords.

**Comment by plachta11b** [comment]
Ok, in that case I will look into noVNC or something similar too as connecting to X server can be non trivial. Thanks for info.

**Comment by lukaarma** [comment]
Closing as inactive

**Comment by plachta11b** [comment]
Can somebody test this workflow? I do not have access to any teams organisation anymore.

### step 1
```docker run -it -p 8080:8080 -v $(realpath ./video):/video plachta11b/destreamer:2b09d17 -i 'https://web.microsoftstream.com/video/______HASHOFYOURVIDEOHERE_____' -o /video```

### step 2
http://localhost:8080/vnc.html

### step 3
Video should appear in ./video directory.

**Comment by mbenitog** [comment]
It works. Tested on macOS Big Sur.

I couldn't get it to work exactly as you said. I only had to replace `$(realpath ./video)` with an absolute path and it works perfectly fine now.

**Comment by plachta11b** [comment]
@mbenitog Thank you for testing it out. Good to know that it works as I am not able to test it by myself :)

**Comment by colinfrei** [comment]
> Can somebody test this workflow? I do not have access to any teams organisation anymore.

This worked great, thanks!
