### ISSUE TITLE
Unnecessary login request

### ISSUE THREAD

**Issue by ricardoroehe** [snobu/destreamer#211]
Greetings!

I'm trying to download a video from Microsoft Teams, but by using anonymous access.

You can check it out here:
https://teams.microsoft.com/l/meetup-join/19:meeting_N2UyZjhiMjYtNmEwOS00ZTRjLTgxMGMtM2NlMTRlZDczOTQ0@thread.v2/0?context={"Tid":"29e081cc-983f-4d52-b1d0-103595213bc6","Oid":"683f4a6e-3974-43ef-a2c5-f1a8b63482a9","IsBroadcastMeeting":true}
1) On the 1st screen: "Watch on web instead" button;
2) On the 2nd screen: "Or Join anonymously" link.

So, there is no need to login to get to the video stream.
Is it possible to bypass that step? Or Destreamer just won't work in this case?

Console output:
```
$ ./destreamer.sh -i "https://teams.microsoft.com/l/meetup-join/19:meeting_N2UyZjhiMjYtNmEwOS00ZTRjLTgxMGMtM2NlMTRlZDczOTQ0@thread.v2/0?context={"Tid":"29e081cc-983f-4d52-b1d0-103595213bc6","Oid":"683f4a6e-3974-43ef-a2c5-f1a8b63482a9","IsBroadcastMeeting":true}"

[WARNING] .token_cache not found. 

Launching headless Chrome to perform the OpenID Connect dance...
Navigating to login page...

[ERROR] TimeoutError: waiting for target failed: timeout 150000ms exceeded
    at Function.waitWithTimeout (/home/user/destreamer/node_modules/puppeteer/lib/helper.js:228:26)
    at Browser.waitForTarget (/home/user/destreamer/node_modules/puppeteer/lib/Browser.js:214:27)
    at Browser.<anonymous> (/home/user/destreamer/node_modules/puppeteer/lib/helper.js:112:23)
    at DoInteractiveLogin (/home/user/destreamer/build/src/destreamer.js:71:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by lukaarma** [comment]
As you can see in #209 Destreamer doesn't work with teams videos
You can find some info about a possible workaround in #132 but I don't have time to finish it now.
