### ISSUE TITLE
[ERROR] TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r722234 is guaranteed to work.

### ISSUE THREAD

**Issue by ethanhines** [snobu/destreamer#212]
## PLEASE NEVER PASTE YOUR ACCESS TOKEN INTO A GITHUB ISSUE AS IT MAY CONTAIN PRIVATE INFORMATION

I am using a iMac 16.2 8GB RAM,1TB. I get this "Error" all the time. I have deducted that it's related to the time your program is allowing for the "drone" chrome to open to the login screen. I request that you increase the delay time to more than 30,000ms=30seconds. In some cases due to insufficient system resources say having Microsoft Teams, Adobe Illustrator and a Web Browser open, even though the "drone" chrome is activated it still times out.

**Comment by lukaarma** [comment]
This happens when you first launch Destreamer or while it's running?

**Comment by ethanhines** [comment]
It can happen at anytime. But yes usually the first time I run the program it stalls. I run it again and it seems to respond faster.

**Comment by lukaarma** [comment]
you can try to add a line between this two 
https://github.com/snobu/destreamer/blob/7fc7c4733aa9f79a28d163888834c1c01bd93679/src/destreamer.ts#L50-L51
and add this code
`timeout: XXXXXXX,`
where XXXXXX is the number of millisecond Destreamer will wait for the browser to spawn (I suggest to start with 90000 and move up from there if needed)

**Comment by ethanhines** [comment]
I realize this is open source but I am not a programmer. I don't even know where to begin. I had a hard enough time following the steps to install the program. I would appreciate a update to the program as I am sure I am not the only one who has experienced this error.

**Comment by lukaarma** [comment]
clone [this ](https://github.com/snobu/destreamer/tree/fix_browser_timeout) instead of master in a new folder, build and run

**Comment by ethanhines** [comment]
Thank you! It seems to be working perfectly now!
