### ISSUE TITLE
Request failed with status code 500 // Console.log response body on 500 errors

### ISSUE THREAD

**Issue by kostapsimoulis** [snobu/destreamer#214]
Hello,

I am getting requested failed with status code 500 error. I was wondering if there is a way to debug this. The verbose output does not give much details.

destreamer version: latest master
NodeJs: 12.18.3
ffmpeg: 4.2.2, 4.3.1 and latest master
Chromium: 80.0.3987 64 bit
OS: Windows 10
Shell: Powershell and cmd

I tried to open Chromium manually from node_modules/puppeteer/.local-chromium/win64-72234/chrome-win/Chrome.exe and I am able to successfully watch the video.

Note: I am using an HTTP proxy to access the internet.

![image](https://user-images.githubusercontent.com/12829287/91348020-2f7a6700-e7b1-11ea-8ab6-3dea3437fff0.png)

**Comment by snobu** [comment]
You could add `console.dir(err)` right before this line here and rebuild.
https://github.com/snobu/destreamer/blob/7bfc565a05ffc95e462afa56cff3419f9b3592bb/src/ApiClient.ts#L30
That should print out the body of that 500 error as well.

**Comment by kostapsimoulis** [comment]
Thank you @snobu the error is very clear now, it was proxy related so I am closing this issue.

**Comment by snobu** [comment]
Reopening this since we should return response body in the final throw. Thanks for pointing out `verbose` doesn't do that, @kostapsimoulis.

**Comment by lukaarma** [comment]
@snobu per axios documentation you were right about `err.response.data` ([see here](https://github.com/axios/axios#handling-errors))
