### ISSUE TITLE
[ERROR] Error: Failed to launch the browser process! - libatk-1.0.so.0

### ISSUE THREAD

**Issue by KhalidQasim** [snobu/destreamer#216]
sudo apt install libtaktuk-1-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  libtaktuk-1-dev
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 9980 B of archives.
After this operation, 33.8 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal/universe amd64 libtaktuk-1-dev amd64 3.7.7-2 [9980 B]
Fetched 9980 B in 0s (26.4 kB/s)
Selecting previously unselected package libtaktuk-1-dev:amd64.
(Reading database ... 47503 files and directories currently installed.)
Preparing to unpack .../libtaktuk-1-dev_3.7.7-2_amd64.deb ...
Unpacking libtaktuk-1-dev:amd64 (3.7.7-2) ...
Setting up libtaktuk-1-dev:amd64 (3.7.7-2) ...
Processing triggers for man-db (2.9.1-1) ...

./destreamer.sh -i https://web.microsoftstream.com/video/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx

[WARNING] .token_cache not found.
Launching headless Chrome to perform the OpenID Connect dance...

[ERROR] Error: Failed to launch the browser process!
/mnt/c/Users/Tester/BIN/destreamer/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/mnt/c/Users/Tester/BIN/destreamer/node_modules/puppeteer/lib/Launcher.js:750:14)
    at Interface.helper.addEventListener (/mnt/c/Users/Tester/BIN/destreamer/node_modules/puppeteer/lib/Launcher.js:739:50)
    at Interface.emit (events.js:203:15)
    at Interface.close (readline.js:397:8)
    at Socket.onend (readline.js:173:10)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by lukaarma** [comment]
I don't think you installed the right package, could you try this `sudo apt-get install libatk1.0` and let me know?

**Comment by lukaarma** [comment]
any updates?

**Comment by KhalidQasim** [comment]
Hello,
I was able to successfully rebuild and run destreamer on Ubuntu 20.

After installing npm, node, ffmpeg, and git I also installed the following (based on the missing library error messages):
sudo apt install libcups2 libnss3-dev librust-atk-sys-dev libatk-bridge2.0-dev librust-gtk-sys-dev

Thank you for your help
