### ISSUE TITLE
Unhandled error, time out or fatal error

### ISSUE THREAD

**Issue by Jaime1317** [snobu/destreamer#219]
Hello guys. I've been downloading Microsoft Teams videos from my university for the last 6 months and I hadn't had a problem until now. I'm getting this error:

This is what it shows at the beginning 

![image](https://user-images.githubusercontent.com/70987644/92544116-78a3cf80-f223-11ea-897d-76adb35ca8b1.png)

Then it appears a bunch of red code and this is what it shows at the end

![image](https://user-images.githubusercontent.com/70987644/92544277-e3550b00-f223-11ea-8abc-9fa0f2afebd2.png)

I'd really appreciate your help.
PD: My OS is Windows 10

**Comment by lukaarma** [comment]
You should update Destreamer to the latest version and use the destreamer.ps1 script to launch the app, that should solve your problem!

PS: I think you have quite an old version of Destreamer, we have implemented some new cool stuff, like the -k option, check them out in the readme!

**Comment by Jaime1317** [comment]
Thank you so much lukaarma, I've updated to the latest version and followed the instructions in the readme section.
Finally I can continue downloading videos!

**Comment by lukaarma** [comment]
Have a nice day!
