### ISSUE TITLE
Introduce token cache

### ISSUE THREAD

**Issue by snobu** [snobu/destreamer#22]
We need a token cache that:
* Saves the access token (preferably encrypted) to local storage (`~/.destreamer/token.cache` or something like that to be consistent with every other project out there that needs to save state).
* Decodes the token on every run, looks at the expiration date and decides if we still need to pop up a browser window to acquire a new token or we can proceed without user interaction.

This will dramatically improve the user experience since within the span of one hour (Azure AD issues tokens with 1-hour lifetime) users can download videos without having to log back in.

Decode sample:
```typescript
import * as jwt_decode from 'jwt-decode';

const token = 'eyJ0eXAi...';
const decoded = jwt_decode(token);

let now = Math.floor(Date.now() / 1000);
let exp = decoded['exp'];
let timeLeft = exp - now; // seconds
```

Stretch goal:
* Can we get an access token for `https://*.microsoftstream.com` just by doing an Open ID connect / OAuth 2.0 dance using the default system browser (drop puppeteer altogether).

### Implementation in progress. See _tokencache_ branch for status.

**Comment by lukaarma** [comment]
It's working great, the only issue we may have is if the token expires mid-download but for that there is already #43

**Comment by snobu** [comment]
Closing since token cache has been implemented. Tracking `/refreshtoken` implementation via https://github.com/snobu/destreamer/issues/43
