### ISSUE TITLE
It is downloading for a long time, but still 0% How can I fix it?

### ISSUE THREAD

**Issue by ASHREDpikachu** [snobu/destreamer#221]

**Comment by ASHREDpikachu** [comment]
![image](https://user-images.githubusercontent.com/71052195/92673693-ae95a080-f356-11ea-9ab5-5287e42a175b.png)
I was using this so good for a long time. But today, this problem happened.
So how could I fix it?

**Comment by snobu** [comment]
Hard to say, can you try with a different video URL? Same story? Try upgrading your ffmpeg version, can't promise that will change anything but is worth a shot.

**Comment by lukaarma** [comment]
Was this solved @ASHREDpikachu?

**Comment by lukaarma** [comment]
Closing as inactive
