### ISSUE TITLE
Black chrome client

### ISSUE THREAD

**Issue by funnisquares** [snobu/destreamer#225]
When I run:
![image](https://user-images.githubusercontent.com/43013384/93633339-30c03d80-f9c5-11ea-8d28-705b3e48d48d.png)
A chrome client opens, but it is black and not intractable
![image](https://user-images.githubusercontent.com/43013384/93633355-361d8800-f9c5-11ea-88c5-0d35dc57a5d3.png)
Eventually, after 150000ms I get a timeout error and the program exits
![image](https://user-images.githubusercontent.com/43013384/93633361-3d449600-f9c5-11ea-848b-106c1de86df0.png)

**Comment by funnisquares** [comment]
I've also tried different browsers, different versions of chromium and google chrome result in the error above, Firefox however gives a different error.

![image](https://user-images.githubusercontent.com/43013384/93633702-c22faf80-f9c5-11ea-862d-3885c21fa8f8.png)

**Comment by snobu** [comment]
Well, never seen this one before. I suggest pluggin in your own browser, check Readme.

**Comment by funnisquares** [comment]
> Well, never seen this one before. I suggest pluggin in your own browser, check Readme.

I did plug in several other browsers, following the Readme instructions. As stated on my second comment.

**Comment by snobu** [comment]
Oh right, i didn't know those were your own installed browsers.

What OS is this?

**Comment by funnisquares** [comment]
Manjaro latest

**Comment by snobu** [comment]
If you're willing to try a different X environment like XFCE that might solve this bizarre rendering bug. You may also try booting X in a fail safe graphic mode see if that makes any difference.

Just speculation but looks like a render problem to me since the process does get launched.

**Comment by funnisquares** [comment]
Running on openbox fixed it.

**Comment by snobu** [comment]
You may want to file a bug in puppeteer, however not sure it's puppeteer at fault here, could be so many things in between. Happy you fixed it.
