### ISSUE TITLE
Error: getaddrinfo ENOTFOUND euwe-1.api.microsoftstream.com at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)

### ISSUE THREAD

**Issue by safsoun** [snobu/destreamer#227]
Hello,

When I tried to download a stream from Microsoft stream as following:
C:\destreamer-master> destreamer.cmd -i "https://web.microsoftstream.com/video/7db01d20-4012-489f-XXXX-YYYYYYYYYYYY"

I have a warning: [WARNING] Error: getaddrinfo ENOTFOUND euwe-1.api.microsoftstream.com. Retrying request...
which is displayed 7 times and it ends with the following error: 
Error: getaddrinfo ENOTFOUND euwe-1.api.microsoftstream.com at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)

Could you please help?
Thanks

**Comment by lukaarma** [comment]
You have to check you internet connection because that error means that Destreamer could not reach the address specified.

Did you have trouble logging in?

**Comment by safsoun** [comment]
Thank you for your reply ..
No.. my connection is good and I can watch the video but I cannot download it!

**Comment by safsoun** [comment]
I don't have any issue when I logged in..

**Comment by lukaarma** [comment]
Could you please tell me the output of this command `git rev-parse --short HEAD` after running it in Destreamer folder?
Did you just download it or you were already using Destreamer and it stopped working?

**Comment by safsoun** [comment]
I donwloaded it yesterday using zip. I cannot run git command in the downoladed repository.. Meanwhile I noticed that the last change was done 5 days ago. So I downloaded destreamer using git and found the rev is de6ab1d.
And it's my first time to use destreamer and I running it behind the company proxy. I don't know if this has a link with the issue!

**Comment by lukaarma** [comment]
You are trying to use Destreamer behind a company proxy? That could definitely be the issue..could you try again in an unrestricted network?

**Comment by safsoun** [comment]
Unfortunately I couldn't disable the proxy nor to open the stream from another location (outside the office network).
Does Destreamer provide a proxy configuration? and how to proceed?

**Comment by lukaarma** [comment]
Destreamer does not provide a proxy setting at the moment but it's a work in progress but I don't have an ETA,.sorry I'll keep you updated

**Comment by snobu** [comment]
Try a VM on a cloud provider if your office network is 'difficult' to get
by.

Azure for example gives you 200 USD of free credit, you should be good for
running a VM several months.

>

**Comment by lukaarma** [comment]
Closing as not Destreamer fault
