### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:8000

### ISSUE THREAD

**Issue by dogwolf** [snobu/destreamer#228]
Dear sir,
I recently installed destreamer 3.0.0  I get the error below when trying to run it:
The same error appear on a Kubuntu and Ubuntu 20.04, behind a proxy and without restrictions.

Any help would be appreciate.
Thank you

[WARNING] .token_cache not found. 

Launching headless Chrome to perform the OpenID Connect dance...
Navigating to login page...
We are logged in.
Wrote access token to token cache.
At this point Chromium's job is done, shutting it down... 

Fresh access token dropped into .token_cachen 

Parsing video/group urls
Downloading video info, this might take a while...
Trying to launch and connect to aria2c...

[FATAL ERROR] Unknown error: exit code 1 

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:8000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
Emitted 'error' event at:
    at ClientRequest.req.on (/destreamer/node_modules/ws/lib/websocket.js:551:15)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by lukaarma** [comment]
You have tu pull the latest changes because 502565d should fix all the problems related to webSocket connection.

But you still can't use that version on anything but windows because I'm a dumbass and hardcoded windows commands and forgot about *nix :P

**Comment by dogwolf** [comment]
Thank you for the response
I'm going to install everything on Windows

**Comment by lukaarma** [comment]
Closing, see [comment](https://github.com/snobu/destreamer/pull/220#issuecomment-698800908)
