### ISSUE TITLE
Can't run destreamer with brave using Default profile

### ISSUE THREAD

**Issue by sudo-panda** [snobu/destreamer#230]
When using 
The executable as `"/usr/bin/brave --profile-directory=Default"` I get `ENOENT` when I `npm run build` the app. 

Has anyone been able to run destreamer with brave using the Default profile successfully? If yes then could you please help.

**Comment by lukaarma** [comment]
With Brave you are intending the browser, right?

**Comment by snobu** [comment]
If it's based on Chromium it should speak DevTools protocol, should work. No guarantees though.

**Comment by sudo-panda** [comment]
> With Brave you are intending the browser, right?

@lukaarma yes the browser

**Comment by sudo-panda** [comment]
> If it's based on Chromium it should speak DevTools protocol, should work. No guarantees though.

@snobu it works with puppetteer but it runs in Guest profile instead of the default profile.

**Comment by snobu** [comment]
Check its docs, there should be a parameter for specifying profile. Then use that in the command line as stated here in the Readme.

**Comment by snobu** [comment]
There's a userDataDir in puppeteer as well, maybe that applies for you,
https://stackoverflow.com/questions/53236692/how-to-use-chrome-profile-in-puppeteer

**Comment by lukaarma** [comment]
You have to add args to the puppeteer launcher

Add your launch options here
https://github.com/snobu/destreamer/blob/de6ab1d8afb7b54a29e00f75276d792a779f9d5c/src/destreamer.ts#L54-L58

**Comment by lukaarma** [comment]
any update @sudo-panda ?

**Comment by sudo-panda** [comment]
I added this to args:
```javascript
async function DoInteractiveLogin(url: string, username?: string): Promise<Session> {

    logger.info('Launching headless Chrome to perform the OpenID Connect dance...');

    const browser: puppeteer.Browser = await puppeteer.launch({
        executablePath: "/usr/bin/brave",
        headless: false,
        userDataDir: (argv.keepLoginCookies) ? chromeCacheFolder : undefined,
        args: [
            '--disable-dev-shm-usage',
            '--fast-start',
            '--no-sandbox',
	    '--profile-directory=Default'
        ]
    });
```

Also I changed chromeCacheFolder:
```javascript
export const chromeCacheFolder = '/home/sudo-panda/.config/BraveSoftware';
```

But it still launches as guest.

**Comment by lukaarma** [comment]
Sorry for the delayed response, I'm not sure how you could solve this :/ 
I'm sorry but I don't have the time to download brave and do all the testing required to help here.

**Comment by sudo-panda** [comment]
Hey @lukaarma it's alright I wasn't hoping you were going to either. I hoped if someone who has used brave with puppeteer might respond to me that would have been swell. Anyways thanks for the directions. :)
