### ISSUE TITLE
Error on the prerelease branch

### ISSUE THREAD

**Issue by Dunsteer** [snobu/destreamer#232]
I was testing the speed of the prerelease when I got the error
```
[ERROR] stdout maxBuffer length exceeded

[FATAL ERROR] The aria2c rpc server crashed with the previous message
```
This happened after I downloaded about 3 files that I supplied the links via the file.txt input.

EDIT

Always crashes with the error above after downloading 2 whole videos and finishes the video segment of the third, about when starting to download the audio segments.

**Comment by lukaarma** [comment]
Could you please tell me the platform/os you are running and how long were the videos?

Are you comfortable with editing the code a little bit yourself to test a possible solution?

**Comment by Dunsteer** [comment]
I'm running windows 10. Can give you all the specs if it is necessary.
Sure, I can take a crack at it and do the necessary changes.

**Comment by lukaarma** [comment]
Please add a space and `-q` after `{port}` on this line, compile and try again

https://github.com/snobu/destreamer/blob/331efd9773dcc45c470d5ed474d9e7e3fff3dd3e/src/destreamer.ts#L167

**Comment by Dunsteer** [comment]
I got this error 
```
(node:17988) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added to [WebSocket]. Use emitter.setMaxListeners() to increase limit
```
In the middle of downloading the 5th video.

The old problem with **maxBuffer** was fixed with `-q`.

**Comment by lukaarma** [comment]
Middle of 5th download, do you remember when? Before the video download, before the audio download or somewhere else?

**Comment by Dunsteer** [comment]
![image](https://user-images.githubusercontent.com/12565043/94373079-345d6e00-0103-11eb-94c9-c269c6ee94a7.png)
Maybe this can help.

**Comment by lukaarma** [comment]
It does! Thank you very much for your patience and help beta testing this branch!

**Comment by lukaarma** [comment]
I'll let you know when I have a solution but I have a suspect on what's wrong here so I hope it won't take much

**Comment by Dunsteer** [comment]
No problem mate, let me know if there is anything I can help with.

**Comment by Dunsteer** [comment]
Oh and btw my PC just crashed because chromium was using to much RAM memory. Idk what happened but my RAM was at 99.8%. No logs sorry.

**Comment by lukaarma** [comment]
pull the newest release, I couldn't fix it in the little time I had but there's a workaround in place, so you can use it


> Oh and btw my PC just crashed because chromium was using to much RAM memory. Idk what happened but my RAM was at 99.8%. No logs sorry.

I really have no idea, Destreamer should always clean up after itself :/ if it happens again let me know

**Comment by Dunsteer** [comment]
> I really have no idea, Destreamer should always clean up after itself :/ if it happens again let me know

I downloaded 20-30 videos in batches of 10 while testing and everything was normal until that moment, it was a couple hours later. Maybe there is a process stuck.

**Comment by lukaarma** [comment]
Did it crash again because of Chromium @Dunsteer ?

**Comment by Dunsteer** [comment]
Was talking about the bug earlier, didn't test it after that. Maybe next weekend.

**Comment by lukaarma** [comment]
Ok, open a new issue if needed. Closing
