### ISSUE TITLE
Freezing Downloads

### ISSUE THREAD

**Issue by Gianvix11** [snobu/destreamer#234]
Video download starts correctly but randomly freezes and does not restart anymore. it is not only a visual bug but an actual one, in fact it does not appear complete in the video folder

**Comment by lukaarma** [comment]
What version of Destreamer are you using and on what platform?

**Comment by Gianvix11** [comment]
Destreamer-master, downloaded 5 days ago, running on Win 10

**Comment by lukaarma** [comment]
If it freezes when the progress bar is making progress there's nothing that Destreamer can do since it's FFmpeg fault, you could try again a few times or switch to our new branch that uses aria2c, more info in the README

**Comment by Gianvix11** [comment]
Where can i find It?

**Comment by lukaarma** [comment]
https://github.com/snobu/destreamer/tree/aria2c_forRealNow

**Comment by lukaarma** [comment]
any update @Gianvix11 ?

**Comment by Gianvix11** [comment]
with aria2c I haven't tried yet, but with destreamer master and ffmpeg there is no way to finish the download, it stops at different percentages, I also tried with other PCs but nothing to do.

**Comment by lukaarma** [comment]
If it stops mid-download there nothing we can do, I'm sorry.
You can try the new branch mentioned above as an alternative.
