### ISSUE TITLE
The chromium script crashes before i finish to insert my credentials!

### ISSUE THREAD

**Issue by sblaker** [snobu/destreamer#235]
As title i start destreamer with ./destreamer.sh -u "credenzialiunipa" -i "videolink" . Appears in the shell stdout is not tty .Then the script launches crhomium with streams form and redirect to my University website. When I am typing my credentials, after 2-3 seconds the Chromium table closed.

I usually avoid this problem typing my credentials fast as i can and sometimes works.But now I am very tired to do this every single day

**Comment by lukaarma** [comment]
Do you know what version you are using? Have you tried updating to the latest release or the new [beta branch](https://github.com/snobu/destreamer/tree/aria2c_forRealNow)?

**Comment by sblaker** [comment]
I did a git pull Yesterday so i guess i own the latest version.

**Comment by lukaarma** [comment]
Could you please paste here the error you are getting when chromium closes, if any?
How much time it takes to load the first page and your university page? Have you considered saving the login in the browser using the '-k' option? Read more [here](https://github.com/snobu/destreamer#usage)

**Comment by sblaker** [comment]
I think there is an error code but the shell closes so much fast that i can't read-
The loading time is ok,it's in the media,like just surfing in the internet.
I tried with K options..but it closes anyway

**Comment by lukaarma** [comment]
How do you launch destreamer? Because if you open up a terminal and then launch `./destreamer.sh -u "credenzialiunipa" -i "videolink"` I don't see how the shell could close on its own...
What OS/distro are you running?

**Comment by sblaker** [comment]
Windows 10 :/ If you have telegram I can explain more like filming a video.

**Comment by lukaarma** [comment]
Write me an email (check my profile) and I'll leave you my telegram handle

**Comment by lukaarma** [comment]
Closing for now, if needed open a new one or write me on telegram
