### ISSUE TITLE
[ERROR] FFmpeg returned an error: Did you mean file:https://...

### ISSUE THREAD

**Issue by BlasterV2** [snobu/destreamer#238]
Hello beautiful people,

I'm getting this error about FFmpeg, I'm not sure which version of FFmpeg I'm using so I attach "ffmpeg -version" too.

![ISSUE](https://user-images.githubusercontent.com/17282819/94751489-99040d00-033d-11eb-83bd-a23753f37376.png)

ffmpeg is in /usr/local/bin/ added to PATH.

**Comment by lukaarma** [comment]
It happens every time you run it?
Have you tried a different link?

**Comment by Mirkesx** [comment]
I don't know if it can help you, but i had this same problem. I first installed ffmpeg manually and whichever video i tried to download it would fail telling me the same error. Then i deleted all the files and i installed with apt install (i have Ubuntu 20.04) and then it worked at fist try.

**Comment by snobu** [comment]
Your ffmpeg binary is missing HLS support it seems. Remove it and add ffmpeg via `apt install` like @Mirkesx already suggested.

**Comment by pivotz1** [comment]
Hi! I have the same problem, but I've installed ffmpeg simply via apt (first remove it, then apt install), and the above error appears again and again!
Then I' used this: sudo mv /usr/local/bin/ffmpeg /usr/local/bin/ffmpeg_old
And then reinstall ffmpeg via apt, and it works now!

**Comment by lukaarma** [comment]
Closing as inactive
