### ISSUE TITLE
Request feature for v3: download live meetings

### ISSUE THREAD

**Issue by phormula** [snobu/destreamer#243]
Can we have destreamer download live MS team meetings?

**Comment by lukaarma** [comment]
You are asking for a download while the meeting is ongoing?

**Comment by phormula** [comment]
No, there is a live broadcast in MS Teams just like Youtube live and I'm asking if destreamer can download that after the live broadcast is done.

**Comment by lukaarma** [comment]
Right now no, there was a little progress on #132 but that's it and I don't see this feature coming in the near future, I'm sorry
