### ISSUE TITLE
Download of audio failing for many long/big videos in arai2c.

### ISSUE THREAD

**Issue by CrupanshuUdani** [snobu/destreamer#248]
Download of audio failing for many long/big videos in arai2c.
I'm aware the v3 with aria2c is still in progress but if you could help with this i'd appreciate

OS: Linux x64 (Arch)
Branch: aria2c_forRealNow
Launch command used: ./destreamer.sh -xtv '{title}-{publishDate}' -i https://web.microsoftstream.com/video/xxxx --skip

<details>
<summary>Verbose  log</summary>
[VERBOSE] Using ffmpeg version n4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
[VERBOSE] Using aria2 version 1.35.0
Access token still good for 42 minutes.
[VERBOSE] Session and API info 
	 API Gateway URL: https://uswe-1.api.microsoftstream.com/api/
	 API Gateway version: 1.4-private
Parsing video/group urls
[VERBOSE] List of videos and corresponding output directory 
	https://web.microsoftstream.com/video/xxxxxxxx => videos 
Downloading video info, this might take a while...
Trying to launch and connect to aria2c...
Connected to aria2 daemon!
Downloading video no.1 
Downloading video segments 

progress [████████████████████████████████████████████████████████] 100%   0.83 MB/s   0s

Downloading audio segments 

progress [██████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 11%   0.26 MB/s   6m5s
[ERROR] stdout maxBuffer length exceeded

[FATAL ERROR] The aria2c rpc server crashed with the previous message 
</details>

**Comment by lukaarma** [comment]
I already know this bug and I thought I fixed it... I'll take a look

**Comment by loremed** [comment]
I'm having this issue too

OS: Linux x64 (Kubuntu 20.04)
Branch: aria2c_forRealNow
Launch command used: ./destreamer.sh -k -x -f videos.txt -t '{publishDate}-{publishTime}' -o <destination directory>  --verbose

The file only specified the links, not the destination directories

<details>
<summary>
<i>Verbose log </i>
</summary>
<p>[VERBOSE] Using ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers


[VERBOSE] Using aria2 version 1.35.0

Access token still good for 39 minutes.


[VERBOSE] Session and API info 
         API Gateway URL: https://euwe-1.api.microsoftstream.com/api/
         API Gateway version: 1.4-private

Parsing input file

[WARNING] Line 12 is empty, skipping..

[VERBOSE] List of videos and corresponding output directory 
        <list of video -> deirectory entries> 

Downloading video info, this might take a while...
Trying to launch and connect to aria2c...

Connected to aria2 daemon!

Downloading video no.1 


Downloading video segments 

progress [███████████████████████████████████████████████████████████████████░░░░░░░░░░░░] 84%   0.89 MB/s   1m55s
[ERROR] stdout maxBuffer length exceeded



[FATAL ERROR] The aria2c rpc server crashed with the previous message </p>
</details>

**Comment by lukaarma** [comment]
Closing this, track updates on #250

**Comment by lukaarma** [comment]
It's now fixed, pull the new changes and you'll be ok
