### ISSUE TITLE
Same video title will not be download

### ISSUE THREAD

**Issue by teabao** [snobu/destreamer#25]
First of all, I want to say that this is wonderful and help me a lots.

There is a little bug that if two video have the exactly same title name, only the first video in the list will be downloaded because the output folder can not have two files with exactly the same name.

**Comment by teabao** [comment]
I found there is the same question in the list.

**Comment by snobu** [comment]
Give us a few days, it will be fixed once the outstanding pull request is merged. For now just rename one of the videos by hand once downloaded.
