### ISSUE TITLE
Download speed is capped @~400kb/s 

### ISSUE THREAD

**Issue by Alex2610** [snobu/destreamer#252]
![Screen](https://user-images.githubusercontent.com/22039589/95655548-8d1c0600-0b08-11eb-8bdc-4dad1c9164f5.PNG)
as you can see the download speed seems to be capped at ~400kb/s.
Any suggestion ?

OS:Win 10 pro
Ram: 16GB
GPU: RX580 8gb
CPU: Ryzen 1600
Network speed available: ~1.5MB/s (~14Mbps)
Using ffmpeg version 2020-10-07-git-a086b73e1f-full_build-www.gyan.dev

**Comment by Alex2610** [comment]
EDIT:
i've just seen that there's an automatic login feature for polimi... where do i have to fill out the needed parameters ?

**Comment by Alex2610** [comment]
opened help in terminal and printed out how to login automatically....

**Comment by Alex87a** [comment]
> ![Screen](https://user-images.githubusercontent.com/22039589/95655548-8d1c0600-0b08-11eb-8bdc-4dad1c9164f5.PNG)
> as you can see the download speed seems to be capped at ~400kb/s.
> Any suggestion ?
> 
> 
> OS:Win 10 pro
> Ram: 16GB
> GPU: RX580 8gb
> CPU: Ryzen 1600
> Network speed available: ~1.5MB/s (~14Mbps)
> Using ffmpeg version 2020-10-07-git-a086b73e1f-full_build-www.gyan.dev

Which version of destreamer are you using?

**Comment by Alex2610** [comment]
I'm using the version 2.0.0 (output of --version)

**Comment by Alex87a** [comment]
> I'm using the version 2.0.0 (output of --version)

If I does not mistake version 2 is limited under the point of view of speed, then the maximum you can reach is ~ 400/500 kbps.

**Comment by Alex2610** [comment]
Alright, but I've done 
git clone https://github.com/SamanFekri/destreamer.git
And obtained the version 2.0.0

**Comment by lukaarma** [comment]
The v3 Is in a branch, can't link now since I'm on mobile

The automatic login from Polimi it's not in our version, it's in fork. You can find the link in our homepage
You can still save your login with us using the '-k' option and saying yes when asked if you want to remember the login

**Comment by Alex87a** [comment]
> Va bene, ma oggi ho fatto
> git clone https://github.com/SamanFekri/destreamer.git
> e ho ottenuto la versione 2.0.0

Try with this:

- Create a new folder and clone the repo again into that folder using this command: 
  git clone https://github.com/snobu/destreamer -b aria2c_forRealNow
- follow the normal destreamer installation guide
- install aria2 following this guide https://www.youtube.com/watch?v=LS-VmSmtaWg
- if you are on windows you can launch destreamer by creating a .bat file with the following command:
  cmd /k destreamer --help
- you can also create a list of microsoft stream videos URL's, save it in the same folder as your destreamer repo and download all 
  of it by creating a .bat file with the following command:
  cmd /k destreamer -f myList.txt

_Originally posted by @SpaceGauchoDev in https://github.com/snobu/destreamer/issues/223#issuecomment-706168339_

I have done with this and the speed has gone from 280 Kbps/s up to 4/5 Mb/s!

**Comment by Alex2610** [comment]
Thanks it worked!!!

**Comment by Alex87a** [comment]
> Thanks it worked!!!

What's your speed, out of curiosity?

**Comment by Alex2610** [comment]
~1.5MB/s my maximum downloading speed ahahah

**Comment by Alex87a** [comment]
> ~1.5MB/s my maximum downloading speed ahahah

It is still a good improvement over before! 😂😂😂

**Comment by lukaarma** [comment]
nice, closing as solved
