### ISSUE TITLE
Various problems with v3

### ISSUE THREAD

**Issue by Alex87a** [snobu/destreamer#253]
Hi guys! First of all I thank you for this useful tool that you have created, it is a true salvation. Secondly, I would like to report some problems that have arisen by downloading version 3: 
1) First of all, every two lessons downloaded, an error concerning the aria2 server appeared on the screen, "[ERROR] stdout maxBuffer length exceeded [FATAL ERROR] The aria2c rpc server crashed with the previous message";
2) Although my speedtest says that my download speed is about 13 Mb/s, why the script can't take all the bandwidth but only 3-4 Mb/s?

P.S. I apologize if by chance I got the wrong section, I'm new in the forum and I can't move well.

**Comment by lukaarma** [comment]
For problem n1 just pull in the latest changes
For n2 we decided not to overload Microsoft's servers so it's much faster then V2 but it's still somewhat capped

**Comment by Alex87a** [comment]
> For problem n1 just pull in the latest changes
> For n2 we decided not to overload Microsoft's servers so it's much faster then V2 but it's still somewhat capped

Thanks @lukaarma!
How could I solve for the point number 1?

**Comment by lukaarma** [comment]
update the repo with `git pull` should solve it

**Comment by lukaarma** [comment]
@Alex87a for the 1st point the bug i thought solved it's still lingering, don't have much time to fix it...will have to wait.

Track any updates on the related pinned issue, closing this
