### ISSUE TITLE
aria2.onDownloadError

### ISSUE THREAD

**Issue by Alex87a** [snobu/destreamer#256]
[ERROR] {"jsonrpc":"2.0","method":"aria2.onDownloadError","params":[{"gid":"8cebe1d32bd00ded"}]}

[ERROR] RECIVED URL TO RETRY, NOT IMPLEMENTED YET

[ERROR] {
    "id": "getUrlForRetry",
    "jsonrpc": "2.0",
    "error": {
        "code": 1,
        "message": "The parameter at 0 has wrong type."
    }
}

**Comment by lukaarma** [comment]
Duplicate of #249
