### ISSUE TITLE
This is AWESOME!

### ISSUE THREAD

**Issue by stkalcic1994** [snobu/destreamer#261]
Hey,
Sorry I opened a ticket, I just couldn't find any other quick way to contact you guys all at once. This application is fantastic and I really appreciate all the work put into it. I'm not used to working from CLI but even I figured it out, the readme was very informative and got me up and running. I love that I can just add a URL to a group I'm in and it will download all the videos. I've even made a torrent so my classmates can have all our lectures saved too.

Great job guys, really

and thank you,

Stefan

**Comment by snobu** [comment]
![image](https://user-images.githubusercontent.com/6472374/96176604-40d02c00-0f35-11eb-8634-2dd1723888a8.png)

We truly appreciate this kind of feedback. Hope you enjoy the work of so many talented people that have contributed to this project. Cheers!
