### ISSUE TITLE
Getting Error when trying to download a video (worked fine until a few moments earlier)

### ISSUE THREAD

**Issue by kamark85** [snobu/destreamer#263]
Hello, I used destreamer until a couple of hours ago without problem. Now i get this error

[ERROR] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at TokenCache.Read (C:\Users\XX\Videos\Destreamer\build\src\TokenCache.js:21:28)
    at main (C:\Users\XX\Videos\Destreamer\build\src\destreamer.js:212:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

I'm using CMD on Win10

EDIT: SOLVED

So I did a fresh install and now it works again.
Unfortunately I am no coder, but online I was finding info about a problem with the node_modules folder and the package-lock.json file, so maybe there was something corrupt there.

Hope this helps

**Comment by Alex87a** [comment]
> Hello, I used destreamer until a couple of hours ago without problem. Now i get this error
> 
> [ERROR] SyntaxError: Unexpected end of JSON input
>     at JSON.parse (<anonymous>)
>     at TokenCache.Read (C:\Users\XX\Videos\Destreamer\build\src\TokenCache.js:21:28)
>     at main (C:\Users\XX\Videos\Destreamer\build\src\destreamer.js:212:32)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> 
> I'm using CMD on Win10

Hi, I think you used the  --keepLoginCookies, -k command to keep the session active. If so, try deleting that item and restarting the download.

**Comment by kamark85** [comment]
Hi, first of all thanks for answering.

I am not using -k. In fact I am just using the -i (Link) parameter.

**Comment by lukaarma** [comment]
Is this solved @kamark85? If yes then close the issue, thank you :D

**Comment by kamark85** [comment]
Yes, I was giving it a couple of days in case someone else had my problem. Will close now :).
