### ISSUE TITLE
Firefox instead of Chromium

### ISSUE THREAD

**Issue by alds-02agem** [snobu/destreamer#264]
Hi, 
i have tried to plug in firefox instead of chromium for the  authentication part, following the instructions given. It doesn't work at all. Maybe it works only with chromium-based browsers ?

**Comment by snobu** [comment]
Puppeteer talks DevTools protocol which is Chromium only. You'll want Microsoft's Playwright to go cross browser,, including Firefox. Should be an easy change in destreamer.ts. Maybe, not sure, everything looks trivial if you don't personally need it :)

https://github.com/microsoft/playwright

**Comment by Tajnymag** [comment]
@snobu Puppeteer supports Firefox natively since version 3.0. ([Source](https://github.com/puppeteer/puppeteer#q-what-is-the-status-of-cross-browser-support))

The problem @alds-02agem experiences might be due to a different set of flags needed to be passed to the firefox binary.

I haven't made it to work myself, but it should theroretically work with the correct puppeteer config.

**Comment by snobu** [comment]
If you look in package.json we are using puppeteer 2.1.1. Try to upgrade to 3.x then, hopefully no other changes are necessary.

**Comment by Tajnymag** [comment]
The [aria2c_forRealNow](https://github.com/snobu/destreamer/tree/aria2c_forRealNow) currently uses puppeteer 5.3.0. That might also be an option.

**Comment by lukaarma** [comment]
I used Firefox while testing my branch and it did work, so @alds-02agem you could try the new branch or update puppeteer in the master branch

**Comment by alds-02agem** [comment]
Thank you all for your support. I'll try all the options.
@snobu you're right, it's just for optimization. To get the video url you need to login to M stream in any browser you use. So why login again in chromium? i propose firefox because that's the browser i use.
what do you think about replacing the username login in destreamer with browser selection ? (for examples -firefox, or -chrome instead of -u)
