### ISSUE TITLE
Resume group video downloads

### ISSUE THREAD

**Issue by mohamed-aiman** [snobu/destreamer#267]
**Issue:** Normally we get an access token for an hour. Lets say the group has lot of videos. In my case, when using group url my token expired before downloading of all videos are finished. So I ran the same command hoping it will resume from the next video. But, to my surprise it started from the first video. Also there might be some scenarios where additional videos are being added to the same group later on. 

**Proposal:** write the video urls in group to a file after fetching, so if the user got disconnected while downloading, the user will have a list to edit and use. He can delete the first urls that were already downloaded and use the list option to download the remaining videos.

**Comment by lukaarma** [comment]
There are already 2 solutions: use the '-k' option and during login consent to "remember me" and Destreamer will keep refreshing the token before it expires and even if it crash launch it again on the same download folder using the '--skip' option and we will not download again the files already present

**Comment by mohamed-aiman** [comment]
Thank you for the clarification 👍🏽
