### ISSUE TITLE
Error when trying to download multiple videos

### ISSUE THREAD

**Issue by FraH90** [snobu/destreamer#27]
So, as in title, I get an error when I try to download multiple videos with the same command. 
I've used:

node destreamer.js --username MYUSERNAME --outputdirectory "videos" \ --videoUrls "VIDEOURL1" \ "VIDEOURL2" \ "VIDEOURL3"

The videos have all different names, so that's not the problem.

It starts downloading the video related to VIDEOURL1, but when it correctly finish the first video, it gives me:

`[ffmpeg] Downloaded 103911358 bytes
[download] 100% of 99.10MiB in 07:59
[ffmpeg] Merging formats into "videos\NAMEOFTHEVIDEO.mp4"
Deleting original file videos\NAMEOFTHEVIDEO.f629.mp4 (pass -k to keep)
Deleting original file videos\NAMEOFTHEVIDEO.f137.mp4 (pass -k to keep)
(node:1948) UnhandledPromiseRejectionWarning: Error: Protocol error (Page.navigate): Cannot navigate to invalid URL
    at C:\destreamer-dev\node_modules\puppeteer\lib\Connection.js:183:56
    at new Promise (<anonymous>)
    at CDPSession.send (C:\destreamer-dev\node_modules\puppeteer\lib\Connection.js:182:12)
    at navigate (C:\destreamer-dev\node_modules\puppeteer\lib\FrameManager.js:118:39)
    at FrameManager.navigateFrame (C:\destreamer-dev\node_modules\puppeteer\lib\FrameManager.js:95:7)
    at Frame.goto (C:\destreamer-dev\node_modules\puppeteer\lib\FrameManager.js:406:37)
    at Frame.<anonymous> (C:\destreamer-dev\node_modules\puppeteer\lib\helper.js:112:23)
    at Page.goto (C:\destreamer-dev\node_modules\puppeteer\lib\Page.js:672:49)
    at Page.<anonymous> (C:\destreamer-dev\node_modules\puppeteer\lib\helper.js:112:23)
    at rentVideoForLater (C:\destreamer-dev\destreamer.js:110:20)
  -- ASYNC --
    at Frame.<anonymous> (C:\destreamer-dev\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.goto (C:\destreamer-dev\node_modules\puppeteer\lib\Page.js:672:49)
    at Page.<anonymous> (C:\destreamer-dev\node_modules\puppeteer\lib\helper.js:112:23)
    at rentVideoForLater (C:\destreamer-dev\destreamer.js:110:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1948) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1948) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Obviously that's a minor issue, but hope it will get fixed

**Comment by lukaarma** [comment]
It seems that there's a problem with the second URL syntax.

Check that it is not malformed/ that has some junk at the end

**Comment by FraH90** [comment]
Yes, I thought that too, but I've checked multiple times, seems all ok. 
Also because if I try to copy the second url just as it is in the multi-command and launch it as a single command, it will download the second video

**Comment by lukaarma** [comment]
Dumb question but did you leave the Chromium browser open?

**Comment by FraH90** [comment]
> Dumb question but did you leave the Chromium browser open?

Yes, obviously :/

**Comment by snobu** [comment]
I'm unable to reproduce this. You sure you have the latest code? There have been quite a lot of changes since yesterday to the codebase.

**Comment by FraH90** [comment]
> I'm unable to reproduce this. You sure you have the latest code? There have been quite a lot of changes since yesterday to the codebase.
> 
> When you launch destreamer, does the video URL array populate correctly?
> 
> ```
> Video URLs: [
>   'https://web.microsoftstream.com/video/6f--------------------',
>   'https://web.microsoftstream.com/video/38--------------------'
> ]
> ```

Yes, I've updated just today. Great the fix for the other issue that I posted some days ago.

I haven't checked if the URL array populate that way, let me launch the command, I'll post the next multiple download command that I'll use (so you can check if there are any errors in the syntax maybe, but I dont guess so, just to be sure) and I'll give you the results and how the array populates..

**Comment by FraH90** [comment]
> I'm unable to reproduce this. You sure you have the latest code? There have been quite a lot of changes since yesterday to the codebase.
> 
> When you launch destreamer, does the video URL array populate correctly?
> 
> ```
> Video URLs: [
>   'https://web.microsoftstream.com/video/6f--------------------',
>   'https://web.microsoftstream.com/video/38--------------------'
> ]
> ```

So, I tried to make another multiple download today. I launched this command:

`node destreamer.js --username MYUSERNAME --outputdirectory "videos" \ --videoUrls "https://web.microsoftstream.com/video/************************************" \ "https://web.microsoftstream.com/video/************************************" \ "https://web.microsoftstream.com/video/************************************"`


The command window reply with:

`Video URLs: [
  'https://web.microsoftstream.com/video/************************************',
  '\\',
  'https://web.microsoftstream.com/video/************************************',
  '\\',
  'https://web.microsoftstream.com/video/************************************'
]
Username: MYUSERNAME
Output Directory: videos
Video/Audio Quality: undefined


Using youtube-dl version 2020.03.08
Using ffmpeg version git-2020-03-15-c467328 Copyright (c) 2000-2020 the FFmpeg developers
Launching headless Chrome to perform the OpenID Connect dance...
Navigating to STS login page...
We are logged in.`

So I guess that the url are taken correctly by the script.

Then, the first video will download correctly. 
But when it finish the first video download, it doesn't go on downloading the second, and it gives me this:

`size=   50769kB time=00:53:31.47 bitrate= 129.5kbits/s speed=3.93x
video:0kB audio:50180kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.174600%
[ffmpeg] Downloaded 51987534 bytes
[download] 100% of 49.58MiB in 13:39
[ffmpeg] Merging formats into "videos\NAMEOFTHEVIDEO.mp4"
Deleting original file videos\NAMEOFTHEVIDEO.f614.mp4 (pass -k to keep)
Deleting original file videos\NAMEOFTHEVIDEO.f137.mp4 (pass -k to keep)
(node:13900) UnhandledPromiseRejectionWarning: Error: Protocol error (Page.navigate): Cannot navigate to invalid URL
    at C:\destreamer-dev\node_modules\puppeteer\lib\Connection.js:183:56
    at new Promise (<anonymous>)
    at CDPSession.send (C:\destreamer-dev\node_modules\puppeteer\lib\Connection.js:182:12)
    at navigate (C:\destreamer-dev\node_modules\puppeteer\lib\FrameManager.js:118:39)
    at FrameManager.navigateFrame (C:\destreamer-dev\node_modules\puppeteer\lib\FrameManager.js:95:7)
    at Frame.goto (C:\destreamer-dev\node_modules\puppeteer\lib\FrameManager.js:406:37)
    at Frame.<anonymous> (C:\destreamer-dev\node_modules\puppeteer\lib\helper.js:112:23)
    at Page.goto (C:\destreamer-dev\node_modules\puppeteer\lib\Page.js:672:49)
    at Page.<anonymous> (C:\destreamer-dev\node_modules\puppeteer\lib\helper.js:112:23)
    at rentVideoForLater (C:\destreamer-dev\destreamer.js:110:20)
  -- ASYNC --
    at Frame.<anonymous> (C:\destreamer-dev\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.goto (C:\destreamer-dev\node_modules\puppeteer\lib\Page.js:672:49)
    at Page.<anonymous> (C:\destreamer-dev\node_modules\puppeteer\lib\helper.js:112:23)
    at rentVideoForLater (C:\destreamer-dev\destreamer.js:110:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:13900) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13900) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`


Hope this will help understanding what's going on

**Comment by snobu** [comment]
There's your problem -

```
`Video URLs: [
'https://web.microsoftstream.com/video/',
'\',
'https://web.microsoftstream.com/video/',
'\',
'https://web.microsoftstream.com/video/************************************'
]
```

Note the backslashes? They are being taken as URLs by our argument parser.
@lukaarma do you want to take a shot at fixing this? We just need to tell yargs to ignore escape chars... which i guess is something it should do by default but obviously it fails to.

@FraH90 Just don't use `\` for now, replace with whitespace between video URLs.
BTW you can now have a `list.txt` that you can pass to `--videoUrls`. Have your videos one per line.

**Comment by lukaarma** [comment]
@snobu As soon as I can I'll look into it

**Comment by snobu** [comment]
On second thought the shell is responsible to interpret those escapes and pass a clean array down to caller, if you're trying to use `\` in cmd or PowerShell that's not an escape char, use backtick for PowerShell.

**Comment by snobu** [comment]
@lukaarma I don't think we need to guard for this in our parser logic. The README has all the info.
