### ISSUE TITLE
trying using aria2c download is stuck at 0%

### ISSUE THREAD

**Issue by 91857** [snobu/destreamer#272]
Hi thanks for the very useful code, I installed "git clone https://github.com/snobu/destreamer -b aria2c_forRealNow", followed the guide to build it, downloaded ffmpeg and pasted in the destreamer directory, I already installed aria2c with  the same process and I also set the variables.
When I run the command from prompt(same results using cmd ofc) :
PS C:\destreamerAria2\destreamer> ./destreamer.ps1 -o C:\Users\...\Desktop\  -f C:\Users\...\Desktop\videoStream.txt
I got this:
Access token still good for 49 minutes.
Parsing input file
Downloading video info, this might take a while...
Trying to launch and connect to aria2c...
Connected to aria2 daemon!
Downloading video no.1
Downloading video segments
progress [░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0%   0 MB/s   0s
and it stays like that forever stuck until it appears some kind of aria2 download errors:
_**[ERROR] RECIVED URL TO RETRY, NOT IMPLEMENTED YET
[ERROR] {
    "id": "getUrlForRetry",
    "jsonrpc": "2.0",
    "error": {
        "code": 1,
        "message": "The parameter at 0 has wrong type."
    }
}
[ERROR] RECIVED URL TO RETRY, NOT IMPLEMENTED YET
[ERROR] {
    "id": "getUrlForRetry",
    "jsonrpc": "2.0",
    "error": {
        "code": 1,
        "message": "The parameter at 0 has wrong type."
    }
}
[ERROR] RECIVED URL TO RETRY, NOT IMPLEMENTED YET
[ERROR] {
    "id": "getUrlForRetry",
    "jsonrpc": "2.0",
    "error": {
        "code": 1,
        "message": "The parameter at 0 has wrong type."
    }
}
[ERROR] {"jsonrpc":"2.0","method":"aria2.onDownloadError","params":[{"gid":"b296a5cccf9712c4"}]}
[ERROR] {"jsonrpc":"2.0","method":"aria2.onDownloadError","params":[{"gid":"51bfad646202423c"}]}
[ERROR] {"jsonrpc":"2.0","method":"aria2.onDownloadError","params":[{"gid":"947ba997b59e4e3a"}]}
[ERROR] {"jsonrpc":"2.0","method":"aria2.onDownloadError","params":[{"gid":"3108f4fb13f7adb6"}]}
[ERROR] {"jsonrpc":"2.0","method":"aria2.onDownloadError","params":[{"gid":"9243de9867d0cfc0"}]}
[ERROR] RECIVED URL TO RETRY, NOT IMPLEMENTED YET**_

OS: Windows 10

Launch command used: ./destreamer.ps1 -o "path directory" -f "path txt file"

<details>
<summary>Verbose  log</summary>
  
```
PASTE VERBOSE LOG HERE
[VERBOSE] Using ffmpeg version 4.3.1-2020-10-28-essentials_build-www.gyan.dev Copyright (c) 2000-2020 the FFmpeg developers


[VERBOSE] Using aria2 version 1.35.0


[WARNING] Access token has expired!

Launching headless Chrome to perform the OpenID Connect dance...
Navigating to login page...

[ERROR] Error: net::ERR_NAME_NOT_RESOLVED at https://web.microsoftstream.com/
    at navigate (C:\Users\2019-2020\AppData\Roaming\destreamerAria2\destreamer\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:113:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async FrameManager.navigateFrame (C:\Users\2019-2020\AppData\Roaming\destreamerAria2\destreamer\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:88:21)
    at async Frame.goto (C:\Users\2019-2020\AppData\Roaming\destreamerAria2\destreamer\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:405:16)
    at async Page.goto (C:\Users\2019-2020\AppData\Roaming\destreamerAria2\destreamer\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:826:16)
    at async DoInteractiveLogin (C:\Users\2019-2020\AppData\Roaming\destreamerAria2\destreamer\build\src\destreamer.js:59:5)
    at async main (C:\Users\2019-2020\AppData\Roaming\destreamerAria2\destreamer\build\src\destreamer.js:283:79)



[FATAL ERROR] Unhandled error or uncaught exception!
Please check your download directory/directories and try again.
If this keep happening please report it on github "https://github.com/snobu/destreamer/issues"
```
</details>

**Comment by 91857** [comment]
Tried  the same command on the plain version without aria2 and it works.  I can't figure it out how to set up properly aria2 ...

**Comment by lukaarma** [comment]
Sorry for the super very late response but I'm here. Aria2c was a rough build still, now it should be a little bit more stable. You could try again.
Again sorry for the late response but Uni was requiring all my time
