### ISSUE TITLE
Downloading starts and gets stuck

### ISSUE THREAD

**Issue by CrispJam** [snobu/destreamer#276]
OS: Windows 10 (windows terminal used)

Launch command used: 
```
.\destreamer.ps1 -i "https://web.microsoftstream.com/video/<secret-part-of-url>" -v -x -k
```

<details>
<summary>Verbose  log</summary>
  
```
[VERBOSE] Using ffmpeg version N-99863-g70d8077b79 Copyright (c) 2000-2020 the FFmpeg developers

Access token still good for 22 minutes.


[VERBOSE] Session and API info
         API Gateway URL: https://euwe-1.api.microsoftstream.com/api/
         API Gateway version: 1.4-private

Parsing video/group urls

[VERBOSE] List of GUIDs and corresponding output directory
       <secret-url> => videos

Fetching videos info...


Downloading Video: <secret-name>

[VERBOSE] Extra video info
         Video m3u8 playlist URL: <secret-url>
         Video tumbnail URL: <secret-url>
         Video subtitle URL (may not exist): undefined
         Video total chunks: 93.71666666666667

Spawning ffmpeg with access token and HLS URL. This may take a few seconds...


progress [█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 4% 779.2kbits/s 7m40s
```
</details>

Downloading starts and gets stuck at around 0 - 4 %

No matter what options I use (tried -x and different output paths) it always gets stuck.
I also tried running the script from cmd and it behaves in the same fashion.
The program stays stuck and outputs no further errors. Left it for around 20 minutes and then killed the process since none of its output was moving. The beginning of the file was saved successfully to the output path provided.

I checked my internet connection and access to the specified stream and tried the whole process several times always with the same result described above. I'd be grateful for any suggestions as to how to fix this issue.

**Comment by lukaarma** [comment]
Did it happen again?

**Comment by guicortei** [comment]
Same problem here... did you find a solution?

**Comment by CrispJam** [comment]
Unfortunately, I didn't manage to solve it back then and since then I haven't had the need for this tool so I haven't tried to solve this any further.
