### ISSUE TITLE
401/404 error codes, even if the videos are available

### ISSUE THREAD

**Issue by carminoski** [snobu/destreamer#277]
Hello, it's a couple of days I am getting errors like this (see verbose down below). The videos are available on Microsoft stream and I can access the manually. I don't understand what has changed , it always worked without problems.

<pre><font color="#06989A">[VERBOSE] </font>Using ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers

<font color="#4E9A06">Access token still good for 51 minutes.</font>

<font color="#06989A">[VERBOSE] </font>Session and API info 
	<font color="#06989A"> API Gateway URL: </font>https://euno-1.api.microsoftstream.com/api/
	<font color="#06989A"> API Gateway version: </font>1.4-private

Parsing input file

<font color="#C4A000">[WARNING] </font>Line 10 is empty, skipping..

<font color="#06989A">[VERBOSE] </font>List of GUIDs and corresponding output directory 
	https://web.microsoftstream.com/video/653f27e6-924b-4700-9b87-cafd224f35b5 =&gt; videos 
	https://web.microsoftstream.com/video/c0e75495-c62f-40ec-bdcf-cbb5473b8642 =&gt; videos 
	https://web.microsoftstream.com/video/62c02302-77c1-4b1d-a785-5b3d54e375b9 =&gt; videos 
	https://web.microsoftstream.com/video/e470dacd-15d7-4805-b2a3-db012689816d =&gt; videos 
	https://web.microsoftstream.com/video/d9f70b50-8fd5-4bdd-8532-c9b2f78fe16a =&gt; videos 
	https://web.microsoftstream.com/video/133bf16e-f5f9-46d0-933a-3142b6fd7b69 =&gt; videos 
	https://web.microsoftstream.com/video/2d4616b8-1fa2-4cae-90f2-1ec430085a8a =&gt; videos 
	https://web.microsoftstream.com/video/4fc4d953-894f-40af-acab-6b89c15e877d =&gt; videos 
	https://web.microsoftstream.com/video/a6f93806-0d67-448b-8ba5-004f0c2bc791 =&gt; videos 

Fetching videos info... 

<font color="#C4A000">[WARNING] </font>Got HTTP code 404. Retrying request...

<font color="#06989A">[VERBOSE] </font>Here is the error message: 
 &apos;[object Object]

<font color="#CC0000">[ERROR] </font>Error: Request failed with status code 404
    at createError (/home/carmine/destreamer-UniPi/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/carmine/destreamer-UniPi/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/carmine/destreamer-UniPi/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
</pre>

**Comment by carminoski** [comment]
<pre><font color="#4E9A06">Using ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers</font>

Video URLs:
[ <font color="#4E9A06">&apos;list.txt&apos;</font> ]

<span style="background-color:#4E9A06"><font color="#2E3436">Access token still good for 3 minutes.</font></span>

Video GUIDs:
[ <font color="#4E9A06">&apos;c0e75495-c62f-40ec-bdcf-cbb5473b8642&apos;</font>,
  <font color="#4E9A06">&apos;62c02302-77c1-4b1d-a785-5b3d54e375b9&apos;</font>,
  <font color="#4E9A06">&apos;e470dacd-15d7-4805-b2a3-db012689816d&apos;</font>,
  <font color="#4E9A06">&apos;d9f70b50-8fd5-4bdd-8532-c9b2f78fe16a&apos;</font>,
  <font color="#4E9A06">&apos;133bf16e-f5f9-46d0-933a-3142b6fd7b69&apos;</font>,
  <font color="#4E9A06">&apos;2d4616b8-1fa2-4cae-90f2-1ec430085a8a&apos;</font>,
  <font color="#4E9A06">&apos;4fc4d953-894f-40af-acab-6b89c15e877d&apos;</font>,
  <font color="#4E9A06">&apos;a6f93806-0d67-448b-8ba5-004f0c2bc791&apos;</font> ]
Fetching metadata...
Got HTTP 404. Retrying request...
<font color="#CC0000">{ Error: Request failed with status code 404</font>
<font color="#CC0000">    at createError (/home/carmine/destreamer-unipi/node_modules/axios/lib/core/createError.js:16:15)</font>
<font color="#CC0000">    at settle (/home/carmine/destreamer-unipi/node_modules/axios/lib/core/settle.js:17:12)</font>
<font color="#CC0000">    at IncomingMessage.handleStreamEnd (/home/carmine/destreamer-unipi/node_modules/axios/lib/adapters/http.js:236:11)</font>
<font color="#CC0000">    at IncomingMessage.emit (events.js:203:15)</font>
<font color="#CC0000">    at endReadableNT (_stream_readable.js:1145:12)</font>
<font color="#CC0000">    at process._tickCallback (internal/process/next_tick.js:63:19)</font>
<font color="#CC0000">  config:</font>
<font color="#CC0000">   { url:</font>
<font color="#CC0000">      &apos;videos/2d4616b8-1fa2-4cae-90f2-1ec430085a8a?api-version=1.4-private&apos;,</font>
<font color="#CC0000">     method: &apos;get&apos;,</font>
<font color="#CC0000">     headers:</font>
<font color="#CC0000">      { Accept: &apos;application/json, text/plain, */*&apos;,</font>
<font color="#CC0000">        &apos;User-Agent&apos;: &apos;destreamer/2.0 (Hammer of Dawn)&apos;,</font>
<font color="#CC0000">        Authorization:</font>
<font color="#CC0000">         &apos;Bearer eyJ0 [...] &apos; },</font>
<font color="#CC0000">     baseURL: &apos;https://euno-1.api.microsoftstream.com/api/&apos;,</font>
<font color="#CC0000">     transformRequest: [ [Function: transformRequest] ],</font>
<font color="#CC0000">     transformResponse: [ [Function: transformResponse] ],</font>
<font color="#CC0000">     timeout: 7000,</font>
<font color="#CC0000">     adapter: [Function: httpAdapter],</font>
<font color="#CC0000">     xsrfCookieName: &apos;XSRF-TOKEN&apos;,</font>
<font color="#CC0000">     xsrfHeaderName: &apos;X-XSRF-TOKEN&apos;,</font>
<font color="#CC0000">     maxContentLength: -1,</font>
<font color="#CC0000">     validateStatus: [Function: validateStatus],</font>
<font color="#CC0000">     &apos;axios-retry&apos;: { retryCount: 0, lastRequestTime: 1605172281473 },</font>
<font color="#CC0000">     data: undefined },</font>
<font color="#CC0000">  request:</font>
<font color="#CC0000">   ClientRequest {</font>
<font color="#CC0000">     _events:</font>
<font color="#CC0000">      [Object: null prototype] {</font>
<font color="#CC0000">        socket: [Array],</font>
<font color="#CC0000">        abort: [Function],</font>
<font color="#CC0000">        aborted: [Function],</font>
<font color="#CC0000">        error: [Function],</font>
<font color="#CC0000">        timeout: [Array],</font>
<font color="#CC0000">        prefinish: [Function: requestOnPrefinish] },</font>
<font color="#CC0000">     _eventsCount: 6,</font>
<font color="#CC0000">     _maxListeners: undefined,</font>
<font color="#CC0000">     output: [],</font>
<font color="#CC0000">     outputEncodings: [],</font>
<font color="#CC0000">     outputCallbacks: [],</font>
<font color="#CC0000">     outputSize: 0,</font>
<font color="#CC0000">     writable: true,</font>
<font color="#CC0000">     _last: true,</font>
<font color="#CC0000">     chunkedEncoding: false,</font>
<font color="#CC0000">     shouldKeepAlive: false,</font>
<font color="#CC0000">     useChunkedEncodingByDefault: false,</font>
<font color="#CC0000">     sendDate: false,</font>
<font color="#CC0000">     _removedConnection: false,</font>
<font color="#CC0000">     _removedContLen: false,</font>
<font color="#CC0000">     _removedTE: false,</font>
<font color="#CC0000">     _contentLength: 0,</font>
<font color="#CC0000">     _hasBody: true,</font>
<font color="#CC0000">     _trailer: &apos;&apos;,</font>
<font color="#CC0000">     finished: true,</font>
<font color="#CC0000">     _headerSent: true,</font>
<font color="#CC0000">     socket:</font>
<font color="#CC0000">      TLSSocket {</font>
<font color="#CC0000">        _tlsOptions: [Object],</font>
<font color="#CC0000">        _secureEstablished: true,</font>
<font color="#CC0000">        _securePending: false,</font>
<font color="#CC0000">        _newSessionPending: false,</font>
<font color="#CC0000">        _controlReleased: true,</font>
<font color="#CC0000">        _SNICallback: null,</font>
<font color="#CC0000">        servername: &apos;euno-1.api.microsoftstream.com&apos;,</font>
<font color="#CC0000">        alpnProtocol: false,</font>
<font color="#CC0000">        authorized: true,</font>
<font color="#CC0000">        authorizationError: null,</font>
<font color="#CC0000">        encrypted: true,</font>
<font color="#CC0000">        _events: [Object],</font>
<font color="#CC0000">        _eventsCount: 8,</font>
<font color="#CC0000">        connecting: false,</font>
<font color="#CC0000">        _hadError: false,</font>
<font color="#CC0000">        _handle: [TLSWrap],</font>
<font color="#CC0000">        _parent: null,</font>
<font color="#CC0000">        _host: &apos;euno-1.api.microsoftstream.com&apos;,</font>
<font color="#CC0000">        _readableState: [ReadableState],</font>
<font color="#CC0000">        readable: true,</font>
<font color="#CC0000">        _maxListeners: undefined,</font>
<font color="#CC0000">        _writableState: [WritableState],</font>
<font color="#CC0000">        writable: false,</font>
<font color="#CC0000">        allowHalfOpen: false,</font>
<font color="#CC0000">        _sockname: null,</font>
<font color="#CC0000">        _pendingData: null,</font>
<font color="#CC0000">        _pendingEncoding: &apos;&apos;,</font>
<font color="#CC0000">        server: undefined,</font>
<font color="#CC0000">        _server: null,</font>
<font color="#CC0000">        ssl: [TLSWrap],</font>
<font color="#CC0000">        _requestCert: true,</font>
<font color="#CC0000">        _rejectUnauthorized: true,</font>
<font color="#CC0000">        parser: null,</font>
<font color="#CC0000">        _httpMessage: [Circular],</font>
<font color="#CC0000">        timeout: 7000,</font>
<font color="#CC0000">        [Symbol(res)]: [TLSWrap],</font>
<font color="#CC0000">        [Symbol(asyncId)]: 119,</font>
<font color="#CC0000">        [Symbol(lastWriteQueueSize)]: 0,</font>
<font color="#CC0000">        [Symbol(timeout)]:</font>
<font color="#CC0000">         Timeout {</font>
<font color="#CC0000">           _called: false,</font>
<font color="#CC0000">           _idleTimeout: 7000,</font>
<font color="#CC0000">           _idlePrev: [TimersList],</font>
<font color="#CC0000">           _idleNext: [TimersList],</font>
<font color="#CC0000">           _idleStart: 6864,</font>
<font color="#CC0000">           _onTimeout: [Function: bound ],</font>
<font color="#CC0000">           _timerArgs: undefined,</font>
<font color="#CC0000">           _repeat: null,</font>
<font color="#CC0000">           _destroyed: false,</font>
<font color="#CC0000">           [Symbol(unrefed)]: true,</font>
<font color="#CC0000">           [Symbol(asyncId)]: 129,</font>
<font color="#CC0000">           [Symbol(triggerId)]: 127 },</font>
<font color="#CC0000">        [Symbol(kBytesRead)]: 0,</font>
<font color="#CC0000">        [Symbol(kBytesWritten)]: 0,</font>
<font color="#CC0000">        [Symbol(connect-options)]: [Object] },</font>
<font color="#CC0000">     connection:</font>
<font color="#CC0000">      TLSSocket {</font>
<font color="#CC0000">        _tlsOptions: [Object],</font>
<font color="#CC0000">        _secureEstablished: true,</font>
<font color="#CC0000">        _securePending: false,</font>
<font color="#CC0000">        _newSessionPending: false,</font>
<font color="#CC0000">        _controlReleased: true,</font>
<font color="#CC0000">        _SNICallback: null,</font>
<font color="#CC0000">        servername: &apos;euno-1.api.microsoftstream.com&apos;,</font>
<font color="#CC0000">        alpnProtocol: false,</font>
<font color="#CC0000">        authorized: true,</font>
<font color="#CC0000">        authorizationError: null,</font>
<font color="#CC0000">        encrypted: true,</font>
<font color="#CC0000">        _events: [Object],</font>
<font color="#CC0000">        _eventsCount: 8,</font>
<font color="#CC0000">        connecting: false,</font>
<font color="#CC0000">        _hadError: false,</font>
<font color="#CC0000">        _handle: [TLSWrap],</font>
<font color="#CC0000">        _parent: null,</font>
<font color="#CC0000">        _host: &apos;euno-1.api.microsoftstream.com&apos;,</font>
<font color="#CC0000">        _readableState: [ReadableState],</font>
<font color="#CC0000">        readable: true,</font>
<font color="#CC0000">        _maxListeners: undefined,</font>
<font color="#CC0000">        _writableState: [WritableState],</font>
<font color="#CC0000">        writable: false,</font>
<font color="#CC0000">        allowHalfOpen: false,</font>
<font color="#CC0000">        _sockname: null,</font>
<font color="#CC0000">        _pendingData: null,</font>
<font color="#CC0000">        _pendingEncoding: &apos;&apos;,</font>
<font color="#CC0000">        server: undefined,</font>
<font color="#CC0000">        _server: null,</font>
<font color="#CC0000">        ssl: [TLSWrap],</font>
<font color="#CC0000">        _requestCert: true,</font>
<font color="#CC0000">        _rejectUnauthorized: true,</font>
<font color="#CC0000">        parser: null,</font>
<font color="#CC0000">        _httpMessage: [Circular],</font>
<font color="#CC0000">        timeout: 7000,</font>
<font color="#CC0000">        [Symbol(res)]: [TLSWrap],</font>
<font color="#CC0000">        [Symbol(asyncId)]: 119,</font>
<font color="#CC0000">        [Symbol(lastWriteQueueSize)]: 0,</font>
<font color="#CC0000">        [Symbol(timeout)]:</font>
<font color="#CC0000">         Timeout {</font>
<font color="#CC0000">           _called: false,</font>
<font color="#CC0000">           _idleTimeout: 7000,</font>
<font color="#CC0000">           _idlePrev: [TimersList],</font>
<font color="#CC0000">           _idleNext: [TimersList],</font>
<font color="#CC0000">           _idleStart: 6864,</font>
<font color="#CC0000">           _onTimeout: [Function: bound ],</font>
<font color="#CC0000">           _timerArgs: undefined,</font>
<font color="#CC0000">           _repeat: null,</font>
<font color="#CC0000">           _destroyed: false,</font>
<font color="#CC0000">           [Symbol(unrefed)]: true,</font>
<font color="#CC0000">           [Symbol(asyncId)]: 129,</font>
<font color="#CC0000">           [Symbol(triggerId)]: 127 },</font>
<font color="#CC0000">        [Symbol(kBytesRead)]: 0,</font>
<font color="#CC0000">        [Symbol(kBytesWritten)]: 0,</font>
<font color="#CC0000">        [Symbol(connect-options)]: [Object] },</font>
<font color="#CC0000">     _header:</font>
<font color="#CC0000">      &apos;GET /api/videos/2d4616b8-1fa2-4cae-90f2-1ec430085a8a?api-version=1.4-private HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: destreamer/2.0 (Hammer of Dawn)\r\nAuthorization: Bearer eyJ0 [...] \r\nHost: euno-1.api.microsoftstream.com\r\nConnection: close\r\n\r\n&apos;,</font>
<font color="#CC0000">     _onPendingData: [Function: noopPendingOutput],</font>
<font color="#CC0000">     agent:</font>
<font color="#CC0000">      Agent {</font>
<font color="#CC0000">        _events: [Object],</font>
<font color="#CC0000">        _eventsCount: 1,</font>
<font color="#CC0000">        _maxListeners: undefined,</font>
<font color="#CC0000">        defaultPort: 443,</font>
<font color="#CC0000">        protocol: &apos;https:&apos;,</font>
<font color="#CC0000">        options: [Object],</font>
<font color="#CC0000">        requests: {},</font>
<font color="#CC0000">        sockets: [Object],</font>
<font color="#CC0000">        freeSockets: {},</font>
<font color="#CC0000">        keepAliveMsecs: 1000,</font>
<font color="#CC0000">        keepAlive: false,</font>
<font color="#CC0000">        maxSockets: Infinity,</font>
<font color="#CC0000">        maxFreeSockets: 256,</font>
<font color="#CC0000">        maxCachedSessions: 100,</font>
<font color="#CC0000">        _sessionCache: [Object] },</font>
<font color="#CC0000">     socketPath: undefined,</font>
<font color="#CC0000">     timeout: undefined,</font>
<font color="#CC0000">     method: &apos;GET&apos;,</font>
<font color="#CC0000">     insecureHTTPParser: undefined,</font>
<font color="#CC0000">     path:</font>
<font color="#CC0000">      &apos;/api/videos/2d4616b8-1fa2-4cae-90f2-1ec430085a8a?api-version=1.4-private&apos;,</font>
<font color="#CC0000">     _ended: true,</font>
<font color="#CC0000">     res:</font>
<font color="#CC0000">      IncomingMessage {</font>
<font color="#CC0000">        _readableState: [ReadableState],</font>
<font color="#CC0000">        readable: false,</font>
<font color="#CC0000">        _events: [Object],</font>
<font color="#CC0000">        _eventsCount: 3,</font>
<font color="#CC0000">        _maxListeners: undefined,</font>
<font color="#CC0000">        socket: [TLSSocket],</font>
<font color="#CC0000">        connection: [TLSSocket],</font>
<font color="#CC0000">        httpVersionMajor: 1,</font>
<font color="#CC0000">        httpVersionMinor: 1,</font>
<font color="#CC0000">        httpVersion: &apos;1.1&apos;,</font>
<font color="#CC0000">        complete: true,</font>
<font color="#CC0000">        headers: [Object],</font>
<font color="#CC0000">        rawHeaders: [Array],</font>
<font color="#CC0000">        trailers: {},</font>
<font color="#CC0000">        rawTrailers: [],</font>
<font color="#CC0000">        aborted: false,</font>
<font color="#CC0000">        upgrade: false,</font>
<font color="#CC0000">        url: &apos;&apos;,</font>
<font color="#CC0000">        method: null,</font>
<font color="#CC0000">        statusCode: 404,</font>
<font color="#CC0000">        statusMessage: &apos;Not Found&apos;,</font>
<font color="#CC0000">        client: [TLSSocket],</font>
<font color="#CC0000">        _consuming: false,</font>
<font color="#CC0000">        _dumped: false,</font>
<font color="#CC0000">        req: [Circular],</font>
<font color="#CC0000">        responseUrl:</font>
<font color="#CC0000">         &apos;https://euno-1.api.microsoftstream.com/api/videos/2d4616b8-1fa2-4cae-90f2-1ec430085a8a?api-version=1.4-private&apos;,</font>
<font color="#CC0000">        redirects: [] },</font>
<font color="#CC0000">     aborted: undefined,</font>
<font color="#CC0000">     timeoutCb: [Function: emitRequestTimeout],</font>
<font color="#CC0000">     upgradeOrConnect: false,</font>
<font color="#CC0000">     parser: null,</font>
<font color="#CC0000">     maxHeadersCount: null,</font>
<font color="#CC0000">     _redirectable:</font>
<font color="#CC0000">      Writable {</font>
<font color="#CC0000">        _writableState: [WritableState],</font>
<font color="#CC0000">        writable: true,</font>
<font color="#CC0000">        _events: [Object],</font>
<font color="#CC0000">        _eventsCount: 2,</font>
<font color="#CC0000">        _maxListeners: undefined,</font>
<font color="#CC0000">        _options: [Object],</font>
<font color="#CC0000">        _redirectCount: 0,</font>
<font color="#CC0000">        _redirects: [],</font>
<font color="#CC0000">        _requestBodyLength: 0,</font>
<font color="#CC0000">        _requestBodyBuffers: [],</font>
<font color="#CC0000">        _onNativeResponse: [Function],</font>
<font color="#CC0000">        _currentRequest: [Circular],</font>
<font color="#CC0000">        _currentUrl:</font>
<font color="#CC0000">         &apos;https://euno-1.api.microsoftstream.com/api/videos/2d4616b8-1fa2-4cae-90f2-1ec430085a8a?api-version=1.4-private&apos; },</font>
<font color="#CC0000">     [Symbol(isCorked)]: false,</font>
<font color="#CC0000">     [Symbol(outHeadersKey)]:</font>
<font color="#CC0000">      [Object: null prototype] {</font>
<font color="#CC0000">        accept: [Array],</font>
<font color="#CC0000">        &apos;user-agent&apos;: [Array],</font>
<font color="#CC0000">        authorization: [Array],</font>
<font color="#CC0000">        host: [Array] } },</font>
<font color="#CC0000">  response:</font>
<font color="#CC0000">   { status: 404,</font>
<font color="#CC0000">     statusText: &apos;Not Found&apos;,</font>
<font color="#CC0000">     headers:</font>
<font color="#CC0000">      { &apos;cache-control&apos;: &apos;no-cache&apos;,</font>
<font color="#CC0000">        pragma: &apos;no-cache&apos;,</font>
<font color="#CC0000">        &apos;content-length&apos;: &apos;70&apos;,</font>
<font color="#CC0000">        &apos;content-type&apos;: &apos;application/json; charset=utf-8&apos;,</font>
<font color="#CC0000">        &apos;content-language&apos;: &apos;en&apos;,</font>
<font color="#CC0000">        expires: &apos;-1&apos;,</font>
<font color="#CC0000">        &apos;x-ms-request-id&apos;: &apos;d23f9fb5-6bc7-48b9-82c6-d557df585697&apos;,</font>
<font color="#CC0000">        &apos;access-control-expose-headers&apos;: &apos;x-ms-request-id&apos;,</font>
<font color="#CC0000">        &apos;strict-transport-security&apos;: &apos;max-age=31536000; includeSubDomains&apos;,</font>
<font color="#CC0000">        date: &apos;Thu, 12 Nov 2020 09:11:21 GMT&apos;,</font>
<font color="#CC0000">        connection: &apos;close&apos; },</font>
<font color="#CC0000">     config:</font>
<font color="#CC0000">      { url:</font>
<font color="#CC0000">         &apos;videos/2d4616b8-1fa2-4cae-90f2-1ec430085a8a?api-version=1.4-private&apos;,</font>
<font color="#CC0000">        method: &apos;get&apos;,</font>
<font color="#CC0000">        headers: [Object],</font>
<font color="#CC0000">        baseURL: &apos;https://euno-1.api.microsoftstream.com/api/&apos;,</font>
<font color="#CC0000">        transformRequest: [Array],</font>
<font color="#CC0000">        transformResponse: [Array],</font>
<font color="#CC0000">        timeout: 7000,</font>
<font color="#CC0000">        adapter: [Function: httpAdapter],</font>
<font color="#CC0000">        xsrfCookieName: &apos;XSRF-TOKEN&apos;,</font>
<font color="#CC0000">        xsrfHeaderName: &apos;X-XSRF-TOKEN&apos;,</font>
<font color="#CC0000">        maxContentLength: -1,</font>
<font color="#CC0000">        validateStatus: [Function: validateStatus],</font>
<font color="#CC0000">        &apos;axios-retry&apos;: [Object],</font>
<font color="#CC0000">        data: undefined },</font>
<font color="#CC0000">     request:</font>
<font color="#CC0000">      ClientRequest {</font>
<font color="#CC0000">        _events: [Object],</font>
<font color="#CC0000">        _eventsCount: 6,</font>
<font color="#CC0000">        _maxListeners: undefined,</font>
<font color="#CC0000">        output: [],</font>
<font color="#CC0000">        outputEncodings: [],</font>
<font color="#CC0000">        outputCallbacks: [],</font>
<font color="#CC0000">        outputSize: 0,</font>
<font color="#CC0000">        writable: true,</font>
<font color="#CC0000">        _last: true,</font>
<font color="#CC0000">        chunkedEncoding: false,</font>
<font color="#CC0000">        shouldKeepAlive: false,</font>
<font color="#CC0000">        useChunkedEncodingByDefault: false,</font>
<font color="#CC0000">        sendDate: false,</font>
<font color="#CC0000">        _removedConnection: false,</font>
<font color="#CC0000">        _removedContLen: false,</font>
<font color="#CC0000">        _removedTE: false,</font>
<font color="#CC0000">        _contentLength: 0,</font>
<font color="#CC0000">        _hasBody: true,</font>
<font color="#CC0000">        _trailer: &apos;&apos;,</font>
<font color="#CC0000">        finished: true,</font>
<font color="#CC0000">        _headerSent: true,</font>
<font color="#CC0000">        socket: [TLSSocket],</font>
<font color="#CC0000">        connection: [TLSSocket],</font>
<font color="#CC0000">        _header:</font>
<font color="#CC0000">         &apos;GET /api/videos/2d4616b8-1fa2-4cae-90f2-1ec430085a8a?api-version=1.4-private HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: destreamer/2.0 (Hammer of Dawn)\r\nAuthorization: Bearer eyJ0 [...] \r\nHost: euno-1.api.microsoftstream.com\r\nConnection: close\r\n\r\n&apos;,</font>
<font color="#CC0000">        _onPendingData: [Function: noopPendingOutput],</font>
<font color="#CC0000">        agent: [Agent],</font>
<font color="#CC0000">        socketPath: undefined,</font>
<font color="#CC0000">        timeout: undefined,</font>
<font color="#CC0000">        method: &apos;GET&apos;,</font>
<font color="#CC0000">        insecureHTTPParser: undefined,</font>
<font color="#CC0000">        path:</font>
<font color="#CC0000">         &apos;/api/videos/2d4616b8-1fa2-4cae-90f2-1ec430085a8a?api-version=1.4-private&apos;,</font>
<font color="#CC0000">        _ended: true,</font>
<font color="#CC0000">        res: [IncomingMessage],</font>
<font color="#CC0000">        aborted: undefined,</font>
<font color="#CC0000">        timeoutCb: [Function: emitRequestTimeout],</font>
<font color="#CC0000">        upgradeOrConnect: false,</font>
<font color="#CC0000">        parser: null,</font>
<font color="#CC0000">        maxHeadersCount: null,</font>
<font color="#CC0000">        _redirectable: [Writable],</font>
<font color="#CC0000">        [Symbol(isCorked)]: false,</font>
<font color="#CC0000">        [Symbol(outHeadersKey)]: [Object] },</font>
<font color="#CC0000">     data: { error: [Object] } },</font>
<font color="#CC0000">  isAxiosError: true,</font>
<font color="#CC0000">  toJSON: [Function] }</font>


<span style="background-color:#CC0000">Unhandled error!</span>
<span style="background-color:#CC0000">Timeout or fatal error, please check your downloads directory and try again </span>
</pre>

**Comment by mitchelmaxwel** [comment]
Strange. Very nice piece of work. I am following regardless

**Comment by frashersam** [comment]
hello, I also have the same problem. it happen when I try to download a Microsoft group or text file.
The only way i can download is link by link.


![sub](https://user-images.githubusercontent.com/73443754/98975617-53159980-24e4-11eb-934b-f671444ce031.png)

**Comment by carminoski** [comment]
I tried installing the "original" destreamer instead of the forked destreamer-unipi and I am getting the same error message.
I used a text file, now I will try to pass directly the links one by one

 ![image](https://user-images.githubusercontent.com/20257940/98978467-4f046e80-251a-11eb-97ab-9215f44f1583.png)

**Comment by carminoski** [comment]
maybe something has changed in the authentication procedure

![image](https://user-images.githubusercontent.com/20257940/98982878-56c71180-2520-11eb-8ff5-10d9fea7a0f5.png)

**Comment by carminoski** [comment]
now it is making the same thing even with a single video link

**Comment by snobu** [comment]
Fixed the verbose logging and got this:

```
[WARNING] Got HTTP code 400. Retrying request...

[VERBOSE] Here is the error message:
{
  error: {
    code: 'BadRequest',
    message: 'The requested $top value is too large. The maximum supported value is 100.'
  }
}
```

So there's pagination now added to to the API, i added quick workaround, only the first 100 videos will be downloaded for a group.

Fix is now applied to both `master` (destreamer 2.0) and `aria2c_forRealNow` (3.0).

You'll need to `git pull` to merge changes then `npm run build`.

**Comment by carminoski** [comment]
now it seems to work with single video links, but unfortunately not with a text file list
In any case, you did a good job !

**Comment by snobu** [comment]
Not sure what would be different about a text file as input, is it the same exact error message?
```
'The requested $top value is too large. The maximum supported value is 100.'
```
