### ISSUE TITLE
Cannot find module destreamer.js

### ISSUE THREAD

**Issue by xfarrow** [snobu/destreamer#278]
I'm using a Linux machine (Debian-based) with

- the latest version of destreamer (cloned from GitHub);

- Node.js version 8.10.0

- npm version 3.5.2

- ffmpef version 3.4.8
When executing "./destreamer.sh" the following error pops up:

```
module.js: 549
Cannot find module in /destreamer/build/src/destreamer.js
```
indeed I can't find any "build" folder in the project.

**Comment by snobu** [comment]
I believe you may have skipped the build step.
```
npm run build
```

**Comment by xfarrow** [comment]
@snobu I did it, just realized it was failing, now fixed. Thank you!
