### ISSUE TITLE
stdout is not a tty

### ISSUE THREAD

**Issue by adamkovari** [snobu/destreamer#280]
Hi,

i get this : "stdout is not a tty", what is this issue?

Thx

**Comment by snobu** [comment]
Most probably your terminal is not a native Windows terminal. Use either cmd.exe or PowerShell to host destreamer, don't use "Git Bash", "MinTTY" and the sorts, their time is over.

Windows Terminal is also a great option for running destreamer -
https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab

**Comment by duo6666** [comment]
Hello, guys:

Destreamer works great since Sept 01, but it didn't work now.
Window 10 system(2018.09 version).
How to fix it?

**Comment by LuciaFresno** [comment]
Got the same message Using CMD using the app for the 1st time

`destreamer.sh -i "https://economicasuba-my.sharepoint.com/personal/65nm30409264_campus_economicas_uba_ar/_layouts/15/stream.aspx?id=%2Fpersonal%2F65nm30409264%5Fcampus%5Feconomicas%5Fuba%5Far%2FDocuments%2FGrabaciones%2FITIC%20%2D%20Devoluci%C3%B3n%20segundo%20parcial%20y%20cierre%20del%20curso%2D20221116%5F194307%2DGrabaci%C3%B3n%20de%20la%20reuni%C3%B3n%2Emp4&ga=1" -o \videos`

**Comment by LuciaFresno** [comment]
Same error message using powershel 7.3.2

**Comment by LuciaFresno** [comment]
had this issue, solved it in Windows 10 CMD removing the ".sh"  from destreamer.sh
but after doing that and upgrading ffmpg I stil couldn't do it cause the url wasn't recognized.

**Comment by b0b-103** [comment]
`destreamer -i "(video link)" `
Thx, Worked for me from windows command prompt.
