### ISSUE TITLE
Pass access token instead of cookie to youtube-dl

### ISSUE THREAD

**Issue by snobu** [snobu/destreamer#29]
We no longer need to pass the browser cookie down to youtube-dl, we can simply use the access token we get from sessionInfo (as Bearer).

Since we can simply call the MS Stream API for the HLS URL we only need the browser to get to the access token (also API endpoint and version but that's in the sessionInfo as well).

For example:
```
youtube-dl --no-call-home --no-warnings 
    --output "videos/blah blah.mp4"
    --add-header Authorization:"Bearer ey......"
    "https://xxxxx.azureedge.net/X-X-X-X/zzzz.ism/manifest(format=m3u8-aapl)"
```

**Comment by lukaarma** [comment]
implemented in b03d85b2a935928e12b5be661673f76315b7c96e
