### ISSUE TITLE
Errors when "npm install" & "npm run build"

### ISSUE THREAD

**Issue by Oodoctor** [snobu/destreamer#291]
Hello,

So first of all I would like to point that I am not very bright when it comes to cmd stuff so this issue might seem stupid to you, but for me, I am completely lost.

So I followed the tutorial on [this video](https://www.youtube.com/watch?v=vmND6dLBzlI). But I get these errors (even when I open cmd as administrator).

Here is the screen capture of the errors:
![image](https://user-images.githubusercontent.com/48358649/101476408-fcb64200-394d-11eb-9ca0-b8f2c349ebf3.png)

The logs that they are talking about are here (C:\Users\Ismail\AppData\Roaming\npm-cache\_logs\2020-12-08T11_02_31_136Z-debug.log): 

> 0 info it worked if it ends with ok
> 1 verbose cli [
> 1 verbose cli   'D:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'run',
> 1 verbose cli   'build'
> 1 verbose cli ]
> 2 info using npm@6.14.8
> 3 info using node@v14.15.1
> 4 verbose stack Error: ENOENT: no such file or directory, open 'C:\Users\Ismail\Desktop\destreamer-master\package.json'
> 5 verbose cwd C:\Users\Ismail\Desktop\destreamer-master
> 6 verbose Windows_NT 10.0.18363
> 7 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
> 8 verbose node v14.15.1
> 9 verbose npm  v6.14.8
> 10 error code ENOENT
> 11 error syscall open
> 12 error path C:\Users\Ismail\Desktop\destreamer-master\package.json
> 13 error errno -4058
> 14 error enoent ENOENT: no such file or directory, open 'C:\Users\Ismail\Desktop\destreamer-master\package.json'
> 15 error enoent This is related to npm not being able to find a file.
> 16 verbose exit [ -4058, true ]

It seems that they can't find the file package.json (I guess) but I have checked the folder and IT IS there.

So I'm kind of confused as to what the problem is.

Thanks for your help!

**Comment by lukaarma** [comment]
could you download again Destreamer [here ](https://github.com/snobu/destreamer/archive/master.zip) and try again?

**Comment by Oodoctor** [comment]
> could you download again Destreamer [here ](https://github.com/snobu/destreamer/archive/master.zip) and try again?

That's where I originally downloaded it from, I don't how it would fix the problem since it hasn't been updated since I wrote this. (last update was 9 days ago, and I wrote this 3 days ago)

**Comment by lukaarma** [comment]
You have to check inside your Destreamer folder if there is a file called `package.json`, If not then you have to download it again because it's missing a required file.
If the file exists then try to move the folder to something like your Documents folder because maybe there were some permission issues.
