### ISSUE TITLE
Increase speed further?

### ISSUE THREAD

**Issue by Alex87a** [snobu/destreamer#293]
Hi, I downloaded the hypothetical version v3. However, my download speed remains stuck at 3.0 Mb / s.
Would it be possible to increase it? I have Gigabit fiber at home and could reach much higher speeds.
Thanks in advance for your reply!

**Comment by snobu** [comment]
Not sure if you're hitting the limit of what aria2c downloader can do or what the Microsoft Stream storage backend can give you, either way we are not restricting speed in any way.

**Comment by MrXTheAnon** [comment]
> Not sure if you're hitting the limit of what aria2c downloader can do or what the Microsoft Stream storage backend can give you, either way we are not restricting speed in any way.

Hello Nobu, installed using these steps "https://dev.to/osnibjunior/download-videos-from-microsoft-stream-with-destreamer-3c59"

and i don't think my destreamer is connected with aria2 daemon, can you say how to link with it.
Thank you.

**Comment by snobu** [comment]
@lukaarma may be able to help here as he wrote that branch.
