### ISSUE TITLE
Download CC

### ISSUE THREAD

**Issue by constructor-s** [snobu/destreamer#3]
Hi I just want to first say that this project is awesome and helps me a lot! 

I would just like to suggest the feature of adding download of captions/transcript. For the videos I have access to, the transcript is served as a JSON file. For example, for: 

`https://web.microsoftstream.com/video/VIDEO_ID?channelId=CHANEL_ID`

The auto-generated transcript is served as JSON at:

`https://cact-1.api.microsoftstream.com/api/videos/VIDEO_ID/events?$filter=Type%20eq%20%27transcript%27&api-version=1.3-private`

I am not sure if `cact` is region specific. 

Maybe the easiest solution is to download the JSON file and convert it to a standard subtitles file format. 

Just thought this would be a neat feature.

**Comment by snobu** [comment]
Thank you for your suggestion. I agree, this could be useful. I'll look into it next week.

**Comment by snobu** [comment]
Okay, so the transcript JSON is not -

* SAMI or
* TTML or
* WebVTT

I don't know what this is, maybe someone out there has seen this before?
Goes like this:

```json
{
  "value": [
    {
      "id": "0f7df2f7-a28f-48af-ae27-e7a6d8a8e35a",
      "type": "transcript",
      "start": "PT0.74S",
      "end": "PT3.372S",
      "eventData": {
        "type": "caption",
        "language": "en",
        "text": "Financial institutions are\r\nencountering risk and compliance"
      },
      "hidden": false,
      "userData": null
    },
    {
      "id": "e290c713-1728-47b7-a36b-8c94697cf7f1",
      "type": "transcript",
      "start": "PT3.372S",
      "end": "PT6.38S",
      "eventData": {
        "type": "caption",
        "language": "en",
        "text": "challenges when deploying cloud\r\nsolutions. Lack of understanding"
      },
      "hidden": false,
      "userData": null
    },
    ...
```

**Comment by shirj** [comment]
I feel like it is probably a MS proprietary format, but someone may know better. 

My feeling is also that it would be a long shot to find where it gets converted to a standard subtitle stream, if at all.

**Comment by snobu** [comment]
I've added this to the roadmap (see README). Closing issue for now.

**Comment by snobu** [comment]
Reopening since i just discovered the API call to list closed caption URLs -

```
https://use2-2.api.microsoftstream.com/api/videos/<GUID-OF-VIDEO>/texttracks?api-version=1.3-private
```

..which gives us a WebVTT file:

```
WEBVTT

e0cd7542-4a10-498c-a1d0-073096e86f95
00:00:04.460 --> 00:00:07.590
>> Hi. I'm [redacted] vice president of [redacted]
```

**Comment by ashwani4java** [comment]
Dear @snobu,

I am new to node.js and not able to configure the steps which you have mentioned. Could you please elaborate more and steps to download the steam videos. 
Thanks in advance.

**Comment by snobu** [comment]
Are you talking about downloading subtitles or videos?
For videos, just follow this README section all the way down to Usage -
https://github.com/snobu/destreamer#prereqs

We did not implement subtitle downloading yet.

**Comment by ashwani4java** [comment]
No I am not downloading subtitles

**Comment by ashwani4java** [comment]
I followed the step and getting the below error 
FFmpeg is missing!
Destreamer requires a fairly recent release of FFmpeg to download videos
and after that, I tried to install and getting below: 

$ npm install ffmpeg
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ ffmpeg@0.0.4
added 2 packages from 4 contributors and audited 735 packages in 4.227s

28 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by snobu** [comment]
Download ffmpeg from this link: https://ffmpeg.zeranoe.com/builds/
Extract and copy all the binaries to the destreamer folder or to another folder that is in your $PATH.

**Comment by ashwani4java** [comment]
Sorry, I am bothering you again and again.

Now I copied and extracted the ffmpeg binaries to destreamer folder and I initiated the download step, then getting below error:

`Using ffmpeg version git-2020-04-20-cacdac8 Copyright (c) 2000-2020 the FFmpeg developers

Access token still good for 58 minutes.

Fetching metadata...
RangeError: Invalid array length
    at Object.parse (C:\destreamer\node_modules\cli-progress\lib\options.js:48:38)
    at new SingleBar (C:\destreamer\node_modules\cli-progress\lib\single-bar.js:8:24)
    at downloadVideo (C:\destreamer\build\src\destreamer.js:120:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Unhandled error!
Timeout or fatal error, please check your downloads directory and try again
`

Please help on this.

**Comment by snobu** [comment]
What's the full command you're trying to execute (with parameters?). Please censor out the GUIDs for the videos.

**Comment by ashwani4java** [comment]
The full command is 
`./destreamer.sh -i "https://web.microsoftstream.com/video/747f341c-75b3-4acf-9513-34014ch97f6d"`

**Comment by snobu** [comment]
Are you on a Mac/Linux or Windows machine? If Windows, use `destreamer.cmd -i "https://URL_OF_THE_VIDEO` instead.

**Comment by ashwani4java** [comment]
I am using Windows and after using above command still getting the same error 
`RangeError: Invalid array length`
`Unhandled error!
Timeout or fatal error, please check your downloads directory and try again`

**Comment by snobu** [comment]
Not sure what you're doing wrong. Maybe you're using a very old version of Node.js? Get the latest.

**Comment by ashwani4java** [comment]
$ node --version
v12.16.2

**Comment by snobu** [comment]
That's fine. Really not sure what's wrong in your case. I would advise you to start over, clone the repo to a new directory, npm install, build and try again.

**Comment by kylon** [comment]
add -v to your command, it could give us more info
if you are on windows, why are you running the bash script? WLS?

**Comment by snobu** [comment]
I've just tried to run it with the exact same ffmpeg build and it works just fine. Must be something else.

**Comment by kylon** [comment]
the error says the bar size is wrong somehow
process cant get a size or it returns garbage or i dont know

a new update for cli-progress just came out, so it could be a new bug if he is using latest version or his terminal, cmd, whatever returns a different value as col number

**Comment by snobu** [comment]
Same ffmpeg build, a fresh npm install, still no problem for me.

**Comment by kylon** [comment]
ffmpeg is not the problem, it was initially because he had no ffmpeg, now it fails on progress bar instantiation

**Comment by snobu** [comment]
`"_id": "cli-progress@3.7.0"` and `3.8.0` both of them work for me. My assumption was the nightly ffmpeg build changed the output format cli-progress relies on, but that's not the case.

**Comment by snobu** [comment]
https://github.com/ashwani4java, did you try cloning in a new directory and starting over?

**Comment by snobu** [comment]
We just found out destreamer won't run in Cygwin/MinGW shell. Is this your case? If so please use cmd.exe or PowerShell instead.
