### ISSUE TITLE
Missing required argument: videoUrls

### ISSUE THREAD

**Issue by pasabayramoglu** [snobu/destreamer#30]
thank you.

**Comment by lukaarma** [comment]
As you can see in the README you need to use node ./destreamer.js --username"YOUR_USERNAME" --videoUrls "YOUR_LINK_TO_THE_VIDEO"

**Comment by pasabayramoglu** [comment]
oh thank you. but how can install youtube-dl in$PATH? i installed it already, but i think it must be some specific location

**Comment by lukaarma** [comment]
What platform are you on? (windows, linux or macOs)?

**Comment by pasabayramoglu** [comment]
windows 7. i handle the youtube-dl part i guess, now i'm trying to install ffmpeg into $PATH

**Comment by pasabayramoglu** [comment]
oh great, i handled ffmpeg part as well, let's see if i can handle the rest

**Comment by lukaarma** [comment]
if you managed to get youtube-dl into path, great!
now just do the same with ffmpeg!
