### ISSUE TITLE
FFmpeg returned an error: Did you mean file: ...?

### ISSUE THREAD

**Issue by yylliw** [snobu/destreamer#300]
Hi,
I went through the installation with success (running Kubuntu 20.04), destreamer seems to work (I can log into chromium), but then suddenly stops and I get the following message : 

> [ERROR] FFmpeg returned an error: Did you mean file:https://euno-1.api.microsoftstream.com/api/videos/manifest?api-version=1.0&playbackurl=https://streameuno1su011.azureedge.net/76167dc0-fa2d-416a-a7eb-1132f61fa250/v.ism/manifest(format=m3u8-aapl)?
> [FATAL ERROR] Unknown FFmpeg error

I'm trying to download a Teams's meeting record but the video is available in Stream (from which I copy the link, in that case it is "https://web.microsoftstream.com/video/f8f492dd-077d-4eb8-831a-5673100f2138"), and I tried with a random non-Teams video and still get the same error, so I thought the issue should come from ffmpeg.

I do have one of the lastest release of ffmpeg, but I still tried to install some others just in case. Same results.

I have no clue of where the issue is coming from, nor what is this kind of file ffmep doesn't like. Any help would be greatly appreciated :) Thanks !

**Comment by yylliw** [comment]
I just saw there is a verbose mode, my bad. If it can give anyone some idea, here's what I get : 

> ./destreamer.sh -i "https://web.microsoftstream.com/video/d036af81-9d99-459f-a69f-0eae4966db38" -v
> 
> [VERBOSE] Using ffmpeg version N-100427-g2d02cf7 Copyright (c) 2000-2020 the FFmpeg developers
> 
> Access token still good for 57 minutes.
> 
> [VERBOSE] Session and API info 
>          API Gateway URL: https://euno-1.api.microsoftstream.com/api/
>          API Gateway version: 1.4-private
> 
> Parsing video/group urls
> 
> [VERBOSE] List of GUIDs and corresponding output directory 
>         https://web.microsoftstream.com/video/d036af81-9d99-459f-a69f-0eae4966db38 => videos 
> 
> Fetching videos info... 
> 
> Downloading Video: <some video title>
> 
> [VERBOSE] Extra video info 
>          Video m3u8 playlist URL: https://euno-1.api.microsoftstream.com/api/videos/manifest?api-version=1.0&playbackurl=https://streameuno1su021.azureedge.net/4b94409f-f99d-4125-bbc2-4b136ad27c36/v.ism/manifest(format=m3u8-aapl)
>          Video tumbnail URL: https://euno-1-content.api.microsoftstream.com/api/thumbnails/2/356c6d23-2e58-4002-8748-237dcd349e85/MS0yY3J3bnFpeW13bnphNmJnbmdoZTZ4c3FkZV8xXzMyMHgxODAucG5n?validTill=2020-12-26T00%3a00%3a00.0000000Z&aadUserOId=1f547ecb-a747-4cc2-9735-df618a61e437&encoding=base64&api-version=1.4-private&signature=TAwDEDAxXRcFyA%2bcRNFljz%2bXSOr2pc3%2fx8labDgpAwE%3d
>          Video subtitle URL (may not exist): undefined
>          Video total chunks: 43.43333333333333
> 
> Spawning ffmpeg with access token and HLS URL. This may take a few seconds...
> 
> progress [░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0% 0 0s
> 
> [ERROR] FFmpeg returned an error: Did you mean file:https://euno-1.api.microsoftstream.com/api/videos/manifest?api-version=1.0&playbackurl=https://streameuno1su021.azureedge.net/4b94409f-f99d-4125-bbc2-4b136ad27c36/v.ism/manifest(format=m3u8-aapl)?
> 
> [FATAL ERROR] Unknown FFmpeg error

**Comment by Tanmengxuan** [comment]
I got this error as well on Ubuntu 16.04, npm 6.14.10 and ffmpeg 4.3.1.

> I just saw there is a verbose mode, my bad. If it can give anyone some idea, here's what I get :
> 
> > ./destreamer.sh -i "https://web.microsoftstream.com/video/d036af81-9d99-459f-a69f-0eae4966db38" -v
> > [VERBOSE] Using ffmpeg version N-100427-g2d02cf7 Copyright (c) 2000-2020 the FFmpeg developers
> > Access token still good for 57 minutes.
> > [VERBOSE] Session and API info
> > API Gateway URL: https://euno-1.api.microsoftstream.com/api/
> > API Gateway version: 1.4-private
> > Parsing video/group urls
> > [VERBOSE] List of GUIDs and corresponding output directory
> > https://web.microsoftstream.com/video/d036af81-9d99-459f-a69f-0eae4966db38 => videos
> > Fetching videos info...
> > Downloading Video: 
> > [VERBOSE] Extra video info
> > Video m3u8 playlist URL: https://euno-1.api.microsoftstream.com/api/videos/manifest?api-version=1.0&playbackurl=https://streameuno1su021.azureedge.net/4b94409f-f99d-4125-bbc2-4b136ad27c36/v.ism/manifest(format=m3u8-aapl)
> > Video tumbnail URL: https://euno-1-content.api.microsoftstream.com/api/thumbnails/2/356c6d23-2e58-4002-8748-237dcd349e85/MS0yY3J3bnFpeW13bnphNmJnbmdoZTZ4c3FkZV8xXzMyMHgxODAucG5n?validTill=2020-12-26T00%3a00%3a00.0000000Z&aadUserOId=1f547ecb-a747-4cc2-9735-df618a61e437&encoding=base64&api-version=1.4-private&signature=TAwDEDAxXRcFyA%2bcRNFljz%2bXSOr2pc3%2fx8labDgpAwE%3d
> > Video subtitle URL (may not exist): undefined
> > Video total chunks: 43.43333333333333
> > Spawning ffmpeg with access token and HLS URL. This may take a few seconds...
> > progress [░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0% 0 0s
> > [ERROR] FFmpeg returned an error: Did you mean file:https://euno-1.api.microsoftstream.com/api/videos/manifest?api-version=1.0&playbackurl=https://streameuno1su021.azureedge.net/4b94409f-f99d-4125-bbc2-4b136ad27c36/v.ism/manifest(format=m3u8-aapl)?
> > [FATAL ERROR] Unknown FFmpeg error

**Comment by lukaarma** [comment]
Did it happen again? Did you try any other video?

Sorry for the very late response, I was busy

**Comment by yylliw** [comment]
Yes, the same issue with any video.

No problem, it's already honorable from you to spend time on that.

**Comment by lukaarma** [comment]
@yylliw Could you try to update both ffmpeg and Destreamer to the lastest version possible please?

**Comment by snobu** [comment]
Looks like a nightly built ffmpeg. Get a stable version of ffmpeg. Stable versions are numbered 4.x.x.

**Comment by yylliw** [comment]
Problem solved. Seems to me that the latest stable version of ffmpeg didn't change the result, but updating destreamer to the latest version (v3.0) did. For now I did not encounter any other bug, destreamer is working fine. Sorry for the late response, and thank you very much for your help.
