### ISSUE TITLE
Cannot store/read username/password

### ISSUE THREAD

**Issue by caesar753** [snobu/destreamer#301]
Hello,
i tried to fille automatically username/password fields using the credentials.txt password as in the instructions but it didn't work. 
When I launch destreamer.sh it asks me username and password and then if i want to store it for future usage, if i choose y(es) it crashes me with this error code

> Do you want to save the credentials for the next time? [y/n] y
>
>[ERROR] TypeError: Cannot read property 'writeFile' of undefined
 >   at getUnipiCredentials (/home/caesar753/destreamer-UniPi/build/src/destreamer.js:84:31)
>    at <anonymous>
 >   at process._tickCallback (internal/process/next_tick.js:188:7)]

**Comment by lukaarma** [comment]
This is the wrong repo you are creating an issue on. you should check https://github.com/Guray00/destreamer-unipi
