### ISSUE TITLE
Cannot download more than 2 videos/time from file

### ISSUE THREAD

**Issue by caesar753** [snobu/destreamer#302]
Hello,
i'm trying to download videos from urls stored in a txt file: the first two are downloaded smoothly, when the third url is reached this is the error code i get:

>[ERROR] Error: Request failed with status code 401
  >  at createError (/home/caesar753/destreamer-UniPi/node_modules/axios/lib/core/createError.js:16:15)
   > at settle (/home/caesar753/destreamer-UniPi/node_modules/axios/lib/core/settle.js:17:12)
   > at IncomingMessage.handleStreamEnd (/home/caesar753/destreamer-UniPi/node_modules/axios/lib/adapters/http.js:236:11)
    > at emitNone (events.js:111:20)
    > at IncomingMessage.emit (events.js:208:7)
    >at endReadableNT (_stream_readable.js:1064:12)
    > at _combinedTickCallback (internal/process/next_tick.js:138:11)
    > at process._tickCallback (internal/process/next_tick.js:180:9) `

**Comment by lukaarma** [comment]
You should check with the owner of the correct project here https://github.com/Guray00/destreamer-unipi
