### ISSUE TITLE
destreamer  --  error message 

### ISSUE THREAD

**Issue by ggiuliz** [snobu/destreamer#306]
./destreamer -i url 
error message returned:     

Error: Failed to launch the browser process! spawn /Users/giuliz/destreamer/node_modules/puppeteer/.local-chromium/mac-722234/chrome-mac/Chromium.app/Contents/MacOS/Chromium ENOENT      

  .......could you advice me?

**Comment by lukaarma** [comment]
did you run `npm i; npm run build` before launching that command?

**Comment by ggiuliz** [comment]
Thanks for your answer 


I did , I paste here the lines returned 


giuliz@MacBook-Pro-di-Giuliana ~ % npm install -g npm
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/ini
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules/opener
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/npm/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules/npm
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/npm'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/npm'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/npm'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/giuliz/.npm/_logs/2021-01-09T09_37_01_689Z-debug.log
giuliz@MacBook-Pro-di-Giuliana ~ % npm build run
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/giuliz/run/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/giuliz/run/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/giuliz/.npm/_logs/2021-01-09T09_37_14_334Z-debug.log


So, Then 

giuliz@MacBook-Pro-di-Giuliana ~ % ./destreamer -i https://web.microsoftstream.com/video/51bb7f38-c21c-4652-8b01-95310f8c9472
zsh: permission denied: ./destreamer
giuliz@MacBook-Pro-di-Giuliana ~ % 



(I’m running the commands as root/administrator, there are no other users accounts on my Mac ) 

Thanks!!

**Comment by snobu** [comment]
```
sudo npm i - g npm
npm install
npm build
```

Try that. Note the sudo.

**Comment by ggiuliz** [comment]
Thanks!!!

So now it returns this:

zsh: permission denied: ./destreamer


(I’m logged in on teams, stream opened in safari and in chromium) 

🙏

**Comment by snobu** [comment]
Do a

chmod +x ./destreamer

**Comment by ggiuliz** [comment]
Thanks

Same message

zsh: permission denied: ./destreamer

**Comment by snobu** [comment]
It should be destreamer.sh, not sure what you're trying to execute, please look at the README carefully.

**Comment by ggiuliz** [comment]
Ok, thanks for your help
