### ISSUE TITLE
How to make it run on a Raspberry PI (with functioning workaround)

### ISSUE THREAD

**Issue by ldx63** [snobu/destreamer#311]
On Raspberry PI running RaspberryOS (formerly Raspbian) the Chromium downloaded by Destreamer can't run, since RPI has ARM architecture (I guess that the downloaded Chromium is the X86 architecture). I suggest to try to download the "right" Chromium compiled for ARM during installation, if possible.

Anyway, in the meanwhile i got it running on RPI by this workaround:

* change the correct instruction in "browser:" section in src/destreamer.ts:
    executablePath: '/usr/bin/chromium-browser',

* launch the "npm run build" command afterwards.

This will make Destreamer use the correct ARM Chromium already installed in RaspberryOS.

It's running right now on my RPI 3B+. :-)

Thank you, and keep up the good work.
Aldo

**Comment by snobu** [comment]
Thank you for this. Will add a note to the README.

**Comment by JamesRivers** [comment]
thanks, @ldx63  I was having this issue on the new pi 4 - your post I have implemented...

plus also note that chromium-browser was under root:root and not my local account. 

however, I am still hitting the following - 

Launching headless Chrome to perform the OpenID Connect dance...

[ERROR] Error: Failed to launch the browser process!
cannot open path of the current working directory: Permission denied

 thanks to @snobu  for the app...

**Comment by JamesRivers** [comment]
@snobu @ldx63  resolved - do not run from an NFS connection ...
