### ISSUE TITLE
Issue with npm run build

### ISSUE THREAD

**Issue by Paxonite** [snobu/destreamer#312]
This is a similar problem to Ooodoctor's a few posts back, but I have no idea what went wrong. Also, like them, I am not familair with this stuff, so sorry about that. I also followed the same video as them. 

In running npm run build I get this error message:
![erroe](https://user-images.githubusercontent.com/10555015/105132691-57989880-5ab9-11eb-98fa-d4d3bfa0dec6.png)

And the logs they mention say this:

> 0 info it worked if it ends with ok
> 1 verbose cli [
> 1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'run',
> 1 verbose cli   'build'
> 1 verbose cli ]
> 2 info using npm@6.14.10
> 3 info using node@v14.15.4
> 4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
> 5 info lifecycle destreamer@2.1.0~prebuild: destreamer@2.1.0
> 6 info lifecycle destreamer@2.1.0~build: destreamer@2.1.0
> 7 verbose lifecycle destreamer@2.1.0~build: unsafe-perm in lifecycle true
> 8 verbose lifecycle destreamer@2.1.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\truchuynh\Desktop\destreamer-master\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\truchuynh\AppData\Local\Programs\Python\Python38\Scripts\;C:\Users\truchuynh\AppData\Local\Programs\Python\Python38\;C:\Users\truchuynh\AppData\Local\Microsoft\WindowsApps;C:\Users\truchuynh\AppData\Roaming\npm
> 9 verbose lifecycle destreamer@2.1.0~build: CWD: C:\Users\truchuynh\Desktop\destreamer-master
> 10 silly lifecycle destreamer@2.1.0~build: Args: [
> 10 silly lifecycle   '/d /s /c',
> 10 silly lifecycle   'echo Transpiling TypeScript to JavaScript... && node node_modules/typescript/bin/tsc && echo Destreamer was built successfully.'
> 10 silly lifecycle ]
> 11 silly lifecycle destreamer@2.1.0~build: Returned: code: 2  signal: null
> 12 info lifecycle destreamer@2.1.0~build: Failed to exec build script
> 13 verbose stack Error: destreamer@2.1.0 build: `echo Transpiling TypeScript to JavaScript... && node node_modules/typescript/bin/tsc && echo Destreamer was built successfully.`
> 13 verbose stack Exit status 2
> 13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
> 13 verbose stack     at EventEmitter.emit (events.js:315:20)
> 13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
> 13 verbose stack     at ChildProcess.emit (events.js:315:20)
> 13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
> 14 verbose pkgid destreamer@2.1.0
> 15 verbose cwd C:\Users\truchuynh\Desktop\destreamer-master
> 16 verbose Windows_NT 10.0.18363
> 17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
> 18 verbose node v14.15.4
> 19 verbose npm  v6.14.10
> 20 error code ELIFECYCLE
> 21 error errno 2
> 22 error destreamer@2.1.0 build: `echo Transpiling TypeScript to JavaScript... && node node_modules/typescript/bin/tsc && echo Destreamer was built successfully.`
> 22 error Exit status 2
> 23 error Failed at the destreamer@2.1.0 build script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 2, true ]

I'm not sure what the problem is, but any help is appreciated!

#OS:

#Launch command used:

#<details>
#<summary>Verbose  log</summary>
  
```
#PASTE VERBOSE LOG HERE
```
</details>

**Comment by lukaarma** [comment]
Could you try to download/clone a fresh copy of Destreamer from Github and try again, it seems that a file is missing.

Sorr for the late response.
