### ISSUE TITLE
Message "More?" on Windows

### ISSUE THREAD

**Issue by wantolinez4** [snobu/destreamer#317]
OS:

Launch command used:

<details>
<summary>Verbose  log</summary>
  
```
PASTE VERBOSE LOG HERE
```
</details>

Hi Everyone, I'm new using GITHUB.

When I run destreamer on Windows using this command:

**destreamer.cmd -i ^https://web.microsoftstream.com/video/581efe5a-21b7-4b37-bed7-xxxxxxxxxxxx^**

I get the message:

**More?**

What am I doing wrong? Thanks in advance

**Comment by snobu** [comment]
What's up with that `^` (caret) symbol there? You don't need to quote the URL, but if you must, use double quotes `"https://..."`.

**Comment by wantolinez4** [comment]
Hi, thanks for your quick answer. 

Now I have this error:

![image](https://user-images.githubusercontent.com/20325438/106228743-ff008400-61b9-11eb-87ef-48a5e4e7a0f9.png)

How can I solve this? Thanks in advance for your help!

**Comment by lukaarma** [comment]
It happens every time you run it? Or was it a one time deal?

**Comment by wantolinez4** [comment]
Every time that I run it

**Comment by wantolinez4** [comment]
When I run only "destreamer.cmd"

![image](https://user-images.githubusercontent.com/20325438/106626826-15099e00-6546-11eb-8182-1db32baf34f3.png)

**Comment by wantolinez4** [comment]
When I do every step

![image](https://user-images.githubusercontent.com/20325438/106627937-46cf3480-6547-11eb-9261-253079f05e37.png)

**Comment by lukaarma** [comment]
could you please tun the last step like this 
`destreamer.cmd -i "https://web.microsoftstream.com/video/581efe5a-21b7-4b37-bed7-xxxxxxxxxxxx" -v`

**Comment by wantolinez4** [comment]
Doesn't work :(

![image](https://user-images.githubusercontent.com/20325438/106629193-94986c80-6548-11eb-973f-345a9cff83e9.png)

**Comment by lukaarma** [comment]
@snobu please help... I'm really scratching my head on this one

**Comment by snobu** [comment]
Judging by this -
https://nodejs.org/api/process.html#process_exit_codes

> **Exit Code 4**: Internal JavaScript Evaluation Failure: The JavaScript source code internal in the Node.js bootstrapping process failed to return a function value when evaluated. This is extremely rare, and generally can only happen during development of Node.js itself.

There may be something wrong with your Node installation. Make sure you're using the latest Node or at least version 10+, or try reinstalling altogether.

**Comment by wantolinez4** [comment]
Now I get another error :(

![image](https://user-images.githubusercontent.com/20325438/106758251-4d20e780-65ff-11eb-922b-e4059e7603e7.png)

**Comment by lukaarma** [comment]
It seems that you directory structure is not how it should be and it's not finding files to build correctly.
I suggest that you wipe the folder from disk and clone/download a new clean copy of Destreamer and `npm i; npm run build` that one.

**Comment by wantolinez4** [comment]
I erased the folder and install again, but now I get this message when I write `npm run build`

![image](https://user-images.githubusercontent.com/20325438/107149361-2bd53980-6926-11eb-8735-90a218fe095f.png)

**Comment by wantolinez4** [comment]
Is there a way to undo the `clone` instruction? To star the process from the beginning

**Comment by lukaarma** [comment]
you can delete the folder you originally created (or move to another folder) if you want to start with a fresh clone instruction

**Comment by wantolinez4** [comment]
I changed the directory, but I still get the same error:

![image](https://user-images.githubusercontent.com/20325438/107599391-5822db80-6bee-11eb-8d59-1a017ab3753c.png)

**Comment by lukaarma** [comment]
Sorry for the delayed response, update your ffmpeg to a more recent release (2019 or up) and all should be good
