### ISSUE TITLE
Destreamer.cmd command not working after installing Bash terminal (WSL)

### ISSUE THREAD

**Issue by ajay1806** [snobu/destreamer#319]
OS: WINDOWS 10

Launch command used: destreamer.cmd -i "URL" -o path

<details>
<summary>Verbose  log</summary>
  
```
PASTE VERBOSE LOG HERE
```
</details>

**Comment by ajay1806** [comment]
Ealier before installing bash terminal, i was able to download the videos from MS Stream

**Comment by snobu** [comment]
WSL is not Bash Terminal it's a fully functional Linux system alongside Windows. If you installed destreamer on Windows, use it on Windows via cmd.exe or PowerShell. If you want to use it in WSL see the README file for caveats.

**Comment by ajay1806** [comment]
Thanks for the reply. I re-downloaded the destreamer zip file and followed the readme. This works with me :)
