### ISSUE TITLE
Chromium crashes on launch

### ISSUE THREAD

**Issue by flaviuc** [snobu/destreamer#32]
chromium crashing on Windows x64... tried to change puppeteer and chromium versions but no luck.
what else can I do?

**Comment by flaviuc** [comment]
![CHROMIIUM](https://user-images.githubusercontent.com/29480845/78024476-1c2db180-7361-11ea-9ac7-af0ef3fae216.png)
![PS](https://user-images.githubusercontent.com/29480845/78024483-1d5ede80-7361-11ea-8cf3-a48bf8c15712.png)

**Comment by snobu** [comment]
Try changing this line in `destreamer.ts` and rebuild -

https://github.com/snobu/destreamer/blob/161585844f5ae8bf351611acca0d01fe13525056/destreamer.ts#L97

change to

```typescript
    const page = await browser.newPage();
```

**Comment by snobu** [comment]
One more thing, you can specify your own Chromium (or Chrome) binary by passing it into the pupeteer constructor:

```
const browser = await puppeteer.launch({executablePath: '/path/to/Chrome_or_Chromium'});
```

**Comment by flaviuc** [comment]
hi again I tried both... even with the "regular" chrome but somehow it still crashes the same way. even tried to hardcode the URL it goes to, but that's not it, it crashes even before... maybe I just need to find the right combination of puppeteer and Chromium that works (like in issue 4).

**Comment by snobu** [comment]
I wonder if antivirus software or something similar could prevent puppeteer connecting to the dev tools API in the browser.

**Comment by flaviuc** [comment]
good question I added the project folder, node.exe, powershell.exe and chrome.exe to exclusion list but still the same... could well be I guess

**Comment by flaviuc** [comment]
ok, got a bit further... I added the startup args in launch.json, started the process from VS Code as debugger this time it got through the login phase but then crashed again, no breakpoint.
![Untitled picture](https://user-images.githubusercontent.com/29480845/78038980-2d34ed80-7376-11ea-95ef-86bffc01392d.png)

**Comment by flaviuc** [comment]
setting some breakpoints I believe it crashes in this line 

    await browser.waitForTarget(target => target.url().includes('microsoftstream.com/'), { timeout: 180000 });

**Comment by flaviuc** [comment]
also the initial crash is due to me starting PS as administrator... VSCode is not started as admin

**Comment by snobu** [comment]
Try it from non-elevated PowerShell or cmd.exe. Never tested from an elevated shell.

**Comment by flaviuc** [comment]
happy to report it works now from PS. From VSCode it still crashes I don't mind that. Thanks for the help!
