### ISSUE TITLE
REQUEST: Extensions to be enabled before load

### ISSUE THREAD

**Issue by xxcbzxx** [snobu/destreamer#320]
Would need Windows 10 Accounts extension.

**Comment by lukaarma** [comment]
You can plug in the browser you use daily, like Chrome or Firefox, where you already have the extension installed. See [here](https://github.com/snobu/destreamer#can-i-plug-in-my-own-browser) for details

**Comment by xxcbzxx** [comment]
I tried, but it loads into chromium instead, 
changed: 
 executablePath: getPuppeteerChromiumPath(), 
to
 executablePath: 'C:\Program Files\Google\Chrome\Application\chrome.exe'

but loads into a new profile of chrome not the default profile, which does not have the "Windows 10 Accounts" Extension, 

I could not install the extension  

Thanks
David

**Comment by xxcbzxx** [comment]
Also I've changed that executablePath:  'C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\MicrosoftEdge.exe' 
it still opens as a new chromium browser with no extensions or profile associated.

**Comment by xxcbzxx** [comment]
[WARNING] .token_cache not found.

Launching headless Chrome to perform the OpenID Connect dance...

[ERROR] Error: Failed to launch the browser process! spawn C:Program FilesGoogleChromeApplicationchrome.exe ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (C:\Users\David Lay\destreamer\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:193:20)
    at ChildProcess.<anonymous> (C:\Users\David Lay\destreamer\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:185:85)
    at ChildProcess.emit (node:events:376:20)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:12)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:80:21)

**Comment by xxcbzxx** [comment]
Added 
`ignoreDefaultArgs: true ,
`
under `executablePath: getPuppeteerChromiumPath(),`

**Comment by lukaarma** [comment]
Ok, sorry if I wasn't able to help, happy that you solved :D
