### ISSUE TITLE
Termux instalation (without root, android 11)

### ISSUE THREAD

**Issue by jayzeppelin** [snobu/destreamer#323]
Check this error from installing...
![Screenshot_20210207-204657_Termux](https://user-images.githubusercontent.com/35917828/107157762-3b846a80-6986-11eb-9725-5c132082213d.jpg)

**Comment by lukaarma** [comment]
Without root you won't be able to install Destreamer because it requires some level of permission that the standard user does not have, in this case one package is creating a symlink and it can't.
Not Destreamer's fault, closing
