### ISSUE TITLE
[FATAL ERROR] The FFmpeg version currently installed is too old!

### ISSUE THREAD

**Issue by DavideCerqua** [snobu/destreamer#324]
OS: Win10

Launch command used: .\destreamer.ps1 -i https://msit.microsoftstream.com/video/ff24a1ff-0400-b564-25cc-f1eb68e9eed2

'ffmpeg' is not recognized as an internal or external command,
operable program or batch file.

[FATAL ERROR] The FFmpeg version currently installed is too old!
Destreamer requires a fairly recent release of FFmpeg to download videos
  
Please provide steps update FFmpeg version in destreamer

Kind regards,

**Comment by DavideCerqua** [comment]
I copied binary .exe file in the root folder, it is working now

**Comment by DavideCerqua** [comment]
I copied binary .exe file in the root folder, it is working now

**Comment by alvin-naiju** [comment]
> I copied binary .exe file in the root folder, it is working now

Hello, I am having the same issue as you. I do not see a "binary.exe" file in the folder. Can you clarify what you meant? Also, what is the root folder? I am a novice.

**Comment by henriquebrisola** [comment]
@alvin-naiju download the ffmpeg from here https://github.com/GyanD/codexffmpeg/releases/tag/2023-03-23-git-30cea1d39b
inside the zip there will be the .exe which you can copy and then run the destreamer
