### ISSUE TITLE
Unnkown error: exit code 4

### ISSUE THREAD

**Issue by btarm** [snobu/destreamer#325]
Whether I pass links through terminal or a text file, I get "[FATAL ERROR] Unknown error: exit code 4". I can run "--help" normally. "npm install" and "npm run build" passed without any errors. "--verbose" does not provide anything other than the aforementioned error code.

macOS: 11.2
destreamer: 2.1.0
npm: 7.5.3
node: 15.4.0

**Comment by Erik-Ilavsky** [comment]
same problem with 
debian 10.4
npm 6.14.4
node v12.16.3

**Comment by ctyeong** [comment]
Same with 

Ubuntu 18.04
npm 7.5.1
node v15.8

**Comment by lukaarma** [comment]
I'm sorry but I've not been able to reproduce this error, I'll keep trying because I'm not sure what else you could do
The only things that comes to mind is to clean everything (node, Destreamer) and reinstall from 0

**Comment by ctyeong** [comment]
Could there be anything related to the fact that the video I'd like to download is the one only open to a particular group?

**Comment by snobu** [comment]
No, no API call gets made, either because it can't reach the network (are you using a proxy?) or some other reason that Node fails to catch when it exists.

**Comment by lukaarma** [comment]
@snobu we are catching the error code seeing as 
> I get "[FATAL ERROR] Unknown error: exit code 4".

is the error we print for an unknown code on exit.

**Comment by snobu** [comment]
Yes but there's no other message being returned from Node, right? Other than the exit code. Or is it and we drop it?

**Comment by lukaarma** [comment]
> Yes but there's no other message being returned from Node, right? Other than the exit code. Or is it and we drop it?

The [callback ](https://nodejs.org/api/process.html#process_event_exit) is passed only the exit code.
My diagnosis is that FFmpeg is failing it's check (error number 4 in our [ERROR_CODE](https://github.com/snobu/destreamer/blob/c81b16c8f399174cc110f2aede987f9c9bdbdbe9/src/Errors.ts#L5)) but the ERRORS object is not yet loaded somehow and our code cannot link the error code to the correct message. I've had similar timing errors in Ubuntu before that were not present in Windows

If they confirm my theory with an outdated FFmpeg version we just need to make the ERROR_CODE enum start at an higher number and we're done, if not we need to dig deeper

**Comment by snobu** [comment]
@ctyeong what is your ffmpeg version?

**Comment by Erik-Ilavsky** [comment]
i had problem ffmpeg version 4.1.4-1~deb10u1, but after upgrade to ffmpeg version 4.3.1 it's working. 
But is there is another problem with -f return 404, with sequential loop with -i is working (possible MS rate limit ?), i will report it.

**Comment by Erik-Ilavsky** [comment]
> But is there is another problem with -f return 404, with sequential loop with -i is working (possible MS rate limit ?), i will report it.

downloading is working until first HTTP error 404 is occured, but process return code is 0

**Comment by diego200052** [comment]
I solved the problem updating the version of ffmpeg to 4.3.1 or above.

**Comment by diego200052** [comment]
I was on 4.1.2 ffmpeg version and I got the error

**Comment by btarm** [comment]
Went from ffmpeg 4.2.1 to 4.3.2 and the problem was solved. Thanks!

**Comment by lukaarma** [comment]
I found the bug @snobu, it was so stupid...will be fixed in the update I'll push
