### ISSUE TITLE
Error 4048

### ISSUE THREAD

**Issue by mohamed-elwakil** [snobu/destreamer#327]
I get the following error message. Any idea how to solve it?

Created directory: videos

[WARNING] .token_cache not found.

Launching headless Chrome to perform the OpenID Connect dance...
Navigating to login page...
We are logged in.
Wrote access token to token cache.
At this point Chromium's job is done, shutting it down...

Fresh access token dropped into .token_cachen

[Error: EPERM: operation not permitted, unlink 'C:\Users\IEUser\AppData\Local\Temp\puppeteer_dev_chrome_profile-U6hYvV\CrashpadMetrics-active.pma'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'C:\\Users\\IEUser\\AppData\\Local\\Temp\\puppeteer_dev_chrome_profile-U6hYvV\\CrashpadMetrics-active.pma'
}

**Comment by snobu** [comment]
Looks like puppeteer isn't starting up for you. Try to plugin your own Chromium based browser instead. See the README for instructions.

**Comment by steinerj** [comment]
@mohamed-elwakil Had same issue here in a Windows env. Just run it again and it should work. 

Likely a puppeteer issue with Win environments and symlinking.

**Comment by riyan-ahmed** [comment]
@steinerj Yup, had the same issue and running it again, as you said, made it work.
