### ISSUE TITLE
I cannot open destreamer.sh

### ISSUE THREAD

**Issue by Snoteleks** [snobu/destreamer#328]
Whenever I double click on the file "destreamer.sh", a black window shows up before closing itself shortly after. I've followed every step correctly in "How to build", it's the "Usage" part that I can't figure out. Please help. Thank you.

Edit: forgot to add, I also tried to plug "./destreamer.sh", "/destreamer.sh", and "destreamer.sh" to the regular cmd black window that appears when I search for "cmd" in the Windows 10 search bar. The system doesn't recognize it as a valid command.

**Comment by lukaarma** [comment]
You have to be in the Destreamer folder where all the files are (use cd to move between folders, plenty of tutorials if you need to learn that) and if you are using CMD you have to use destreamer.cmd not .ah

Hope this helps :)

**Comment by Noah-It-All** [comment]
yep run it from cmd or powershell, if your on windows use .cmd instead of sh

**Comment by Snoteleks** [comment]
I tried opening destreamer.cmd, and the same thing happens... won't open for more than a milisecond then close itself!

**Comment by snobu** [comment]
You don't open it. You open `cmd.exe` and then you type in the download command - see README for samples.

**Comment by Snoteleks** [comment]
I opened cmd.exe and typed the download command, and it said:

"destreamer.cmd" is not recognized as an internal or external command, operable program or batch file

**Comment by Noah-It-All** [comment]
did you remember to do `.\destreamer.cmd` or did you just write `destreamer.cmd` because for it to work you would need to use `.\destreamer.cmd`

**Comment by Snoteleks** [comment]
firstly, when I do .\destreamer.cmd or ./destreamer.cmd  it tells me the same thing: it is not recognized as an internal or external command, operable program or batch file

secondly, I am in the folder while running the commands, but the only place I can write is in the black "cmd.exe" windows. If I open any file named "destreamer (which are in the folder) directly by double-clicking on them, they close themselves immediately

I have looked at the readme.md but please have patience with me because I'm not good at this stuff, I really do need y'all's help

**Comment by Noah-It-All** [comment]
I am truly sorry if I sounded impatient it wasn't at you I was working on an assignment at the time! Try opening the folder where you saved the files in file explorer then type cmd in the hot bar (i put in an image of the hotbar)
![image](https://user-images.githubusercontent.com/66562321/109190183-d476fc00-7762-11eb-83b9-054c78f944d4.png)

**Comment by Noah-It-All** [comment]
then run the commands `npm install` and when that is done do `npm run build` after that try `./destreamer.cmd
` again

**Comment by Noah-It-All** [comment]
to download the video you need use the command `./destreamer.cmd -i "the video url goes here"`

**Comment by snobu** [comment]
You don't need the `.\` in cmd.exe.
```
C:\blahblah\destreamer\>destreamer.cmd -i "the video url goes here"
```

**Comment by Noah-It-All** [comment]
Either way it works

**Comment by Snoteleks** [comment]
It finally recognized the command! Except..... (sorry it's in Spanish)

![image](https://user-images.githubusercontent.com/79539003/109275493-1ceef200-7815-11eb-817d-ff0a1b50af5a.png)

(I tried every possible combination and only .\destreamer.cmd was recognized lol)
So yeah basically ffmpeg isn't recognized even though I downloaded the ffmpeg file and put it in the same folder as the README, like the instructions said. It says the file is too old but ??? i followed the same link on the README to https://www.ffmpeg.org/download.html and that's the earliest download.... right?

Btw thank you for your patience you did not sound impatient at all i was just worried

**Comment by Snoteleks** [comment]
hello I tried again with the FFmpeg 4.3.2 "4:3" that was literally released 6 DAYS AGO and is "the latest version" and it still tells me the version is too old :( i plugged in the same command as before

![image](https://user-images.githubusercontent.com/79539003/109281251-5e36d000-781c-11eb-9618-af94395a4077.png)

**Comment by Noah-It-All** [comment]
[https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2021-02-26-12-32/ffmpeg-n4.3.2-win64-gpl-4.3.zip](download this) extract it then drag everything from the bin folder and drag it to the destreamer folder

**Comment by Snoteleks** [comment]
oh my GOD IT WORKED it finally worked im so happy, thank you all so much, i cannot stress enough how important your help has been

**Comment by Snoteleks** [comment]
quick question...... how do i convert the MKV videos to MP4

**Comment by Noah-It-All** [comment]
when you run the command use `.\destreamer.cmd -i "video url goes here" --format "mp4"`  so just add `--format "mp4"` to whatever command you use

**Comment by Snoteleks** [comment]
wow it works, this is truly amazing, thank you for your help

**Comment by Noah-It-All** [comment]
no problem! if thats all could you close the issue? Have a nice day and if you ever need help with something just open an issue and @ me!

**Comment by Snoteleks** [comment]
yes ofc thank u
