### ISSUE TITLE
RangeError: Invalid array length

### ISSUE THREAD

**Issue by weixu0834** [snobu/destreamer#329]
OS: Windows 10 

Launch command used: $ ./destreamer.sh -i "https://web.microsoftstream.com/video/a40f2c61-f458-46a6-a025-452dc814043e"

I download compiled  ffmpeg.exe, and put these three exe into project's root file.
I use cmd command also shows same error and by the way, I pull down the polimi version of this code.

<details>
<summary>Verbose  log</summary>
  
```
![image](https://user-images.githubusercontent.com/26054604/108974049-03886180-76c0-11eb-8b13-f3ffed8addbb.png)

PASTE VERBOSE LOG HERE
```
</details>

**Comment by weixu0834** [comment]
![image](https://user-images.githubusercontent.com/26054604/108974049-03886180-76c0-11eb-8b13-f3ffed8addbb.png)

**Comment by lukaarma** [comment]
I'll take a better look this evening, in the mean time could you run it with the --verbosse flag?

**Comment by weixu0834** [comment]
> I'll take a better look this evening, in the mean time could you run it with the --verbosse flag?

it seems same error
Access token still good for 59 minutes.

Fetching metadata...
RangeError: Invalid array length
    at Object.parse (E:\个人文件\Study\POLIMI\SEMESTER4\destreamer\node_modules\cli-progress\lib\options.js:48:38)
    at new SingleBar (E:\个人文件\Study\POLIMI\SEMESTER4\destreamer\node_modules\cli-progress\lib\single-bar.js:8:24)
    at downloadVideo (E:\个人文件\Study\POLIMI\SEMESTER4\destreamer\build\src\destreamer.js:138:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by weixu0834** [comment]
> I'll take a better look this evening, in the mean time could you run it with the --verbosse flag?

I using windows own cmd shell and try to avoid Chinese characters thus can be solved.

**Comment by snobu** [comment]
You are using CygWin or some other variant of a half-baked Linux shell on Windows. Please use either cmd.exe or PowerShell and everything will be well.
