### ISSUE TITLE
./destreamer.sh --help erroe 

### ISSUE THREAD

**Issue by stathis-coder** [snobu/destreamer#334]
When I try to use any destreamer commands (for example" ./destreamer.sh --help") i always get the same error message, the error message is " '.' is not recognized as an internal or external command,
operable program or batch file." Could you please help me understand how to fix this problem?

**Comment by BachoSeven** [comment]
I suppose you're on windows, so you probably need to use `destreamer.ps1` the script instead of the `.sh` one. I also think(but cannot check right now) that you do not need to specify the relative path on windows (i.e. the `./` part of the command you wrote), or if it is required you should use a backslash, meaning the final command will be `.\destreamer.ps1 --help`, for instance.

**Comment by stathis-coder** [comment]
yes you are correct i am on windows i tried the back slash and ".ps1" and no the error message is "'.\destreamer.ps1' is not recognized as an internal or external command,
operable program or batch file.", i believe maby i did something wrong in the setup, i did afterall have some problems with ffmpeg because i couldn't figure out how to execute the install of ffmpeg. Do you mayebe have a suggestion on how to install ffmpeg.(thank you for your kind disponibility)

**Comment by BachoSeven** [comment]
This has nothing to do with `ffmpeg`(for which you can get binaries at https://github.com/BtbN/FFmpeg-Builds, for instance [this](https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2021-03-06-12-33/ffmpeg-N-101404-g17127f81c5-win64-gpl.zip) ones). For your issue, make sure you are in the right directory(use `cd` to navigate to the folder where you downloaded this repo; i.e.`cd C:\\Users\myuser\Downloads\destreamer` or somethings).

**Comment by snobu** [comment]
For clarity, if you're on Windows, just open PowerShell and use` .\destreamer.ps1` to launch this project.
