### ISSUE TITLE
resolution/quality

### ISSUE THREAD

**Issue by w-kok** [snobu/destreamer#336]
What quality is downloaded? 
Can the resolution be set?

OS:

Launch command used:

<details>
<summary>Verbose  log</summary>
  
```
PASTE VERBOSE LOG HERE
```
</details>

**Comment by snobu** [comment]
Please check the README. This is well documented there. We download best available quality by default.

**Comment by lukaarma** [comment]
P.S: the aria2c branch has the ability to "chose" the quality...it's quite far from what I would like but it works :D
