### ISSUE TITLE
How to resume a download?

### ISSUE THREAD

**Issue by apandada1** [snobu/destreamer#339]
OS: Linux Mint 20

Sometimes, a large download stops midway due to internet connectivity issues. Is there any way to resume a download from a given time (e.g. download 63 minutes onward) and then join the new content with the file (partially) downloaded previously?

This is probably not a duplicate of https://github.com/snobu/destreamer/issues/267, I want to resume downloading a single video.

**Comment by lukaarma** [comment]
There isn't a way to resume a download since we le ffmpeg handle all the download and it does not support resuming a download.
It may be possible to implement in the new experimental branch but I don't have the time to do so.
