### ISSUE TITLE
Ability to set a custom name without templates restriction

### ISSUE THREAD

**Issue by goldmont** [snobu/destreamer#344]
OS: Ubuntu 20.04

Launch command used:
./destreamer.sh --format mp4 -o out -i "my_url" -t "Lesson 5"

Hi there,

I'm not able to set a custom template name like the one above. I must set at least one of the "magic sequences" to make it work.

For example:
"Lesson 5" -> This is not a valid title template. Thus, destreamer refuses to use my custom file name and simply fallbacks to the default one.

"Lesson 5 {author}" -> This one is a valid template. Destreamer accepts my custom title template.

I don't understand this behaviour. Why I can't set a custom name?

**Comment by goldmont** [comment]
[This](https://github.com/snobu/destreamer/blob/master/src/CommandLineParser.ts#L178) line is the problem. You are looking for at least one match. Otherwise you set manually the default template [here](https://github.com/snobu/destreamer/blob/master/src/CommandLineParser.ts#L200)

**Comment by snobu** [comment]
If you send a PR to amend the regex we'd be happy to merge it.

**Comment by goldmont** [comment]
You don't have to modify current regex. We only need to verify that there is a match in order to ensure that all the "magic sequences" are correctly spelled. Code from [line #197](https://github.com/snobu/destreamer/blob/master/src/CommandLineParser.ts#L197) to [line #201](https://github.com/snobu/destreamer/blob/master/src/CommandLineParser.ts#L201) no longer exists. The key part of the formatting process is [here](https://github.com/snobu/destreamer/blob/master/src/VideoUtils.ts#L142). Already fixed and tested. I'm going to make a pull request.
