### ISSUE TITLE
Cannot plug browser without first logging in with Chromium

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [snobu/destreamer#347]
How to reproduce:
1. Clone Github project
2. Plug browser
3. Attempt to download video

Solution:
1. Clone Github project
2. Log in using the Chromium browser (default)
2. Plug browser
3. Download video

I cannot see the error that occurs because the prompt closes in 0.1 seconds.

**Comment by lukaarma** [comment]
What do you mean by "the prompt closes in 0.1 second"? Did you try to run this in a cmd/powershell terminal?

**Comment by lukaarma** [comment]
can I please ask you to share the command your are using? I'm confused as Destreamer output should all be in the cmd window that you are using to launch it

**Comment by asdsadsaasd12312132** [comment]
I only plugged my browser because the Chromium one was not working, but for some reason, it is working now, so this issue is no longer important.
