### ISSUE TITLE
Possible to record a stream while it is live?

### ISSUE THREAD

**Issue by Deep0d0** [snobu/destreamer#348]
Hello, 

I sometimes have an issue where the stream gets privated before I have time to save it, so if there is a way to record while it is live, that would be great.

Also I read somewhere that Stream uses HLS, but I can't seem to find an HLS m3u8 playlist to give to a tool like Streamlink etc.

Any help would be great.

**Comment by snobu** [comment]
This should work if the URL of the live stream matches htttps://web.microsoftstream.com/<something>.
