### ISSUE TITLE
Error : Failed to launch the browser 

### ISSUE THREAD

**Issue by FabianPuche** [snobu/destreamer#349]
OS: Windows
![Capture](https://user-images.githubusercontent.com/43663828/112413932-6c93e100-8d21-11eb-8a95-e491a3a7c3ab.PNG)

I followed the README but i m actually stuck and I can t use destream. A friend installed it and it s working properly for him with almost same installation execept he is using another browser

**Comment by snobu** [comment]
Looks like Chromium failed to install from npm.
I would suggest starting over, clone in a shorter path like `C:\destreamer` since Windows has a long running problem with very long paths. See where that gets you. Should work.

**Comment by FabianPuche** [comment]
Thanks a lot ! It worked for me
