### ISSUE TITLE
destreamer v3.0 (aria2c as download manager)  simultaneous download

### ISSUE THREAD

**Issue by Kgf123** [snobu/destreamer#373]
Can you guys make the audio and video of a file download simultaneously and then decode and merge them in destreamer v3.0 (aria2c as download manager). They download one after the other. Downloading them simultaneously would make them go faster.
![image](https://user-images.githubusercontent.com/79869936/115669398-d8d82380-a365-11eb-9bee-2bf82c0a0b29.png)
It first downloads video then audio.

**Comment by snobu** [comment]
Both of those downloads (video and audio tracks) are multi-threaded, downloading the audio simultaneously will not increase download performance.

**Comment by Kgf123** [comment]
Ok. Thanks.
