### ISSUE TITLE
destreamer v3.0 (aria2c as download manager): temp folder for download

### ISSUE THREAD

**Issue by hanjo** [snobu/destreamer#374]
Hi,

I'd like to propose a command switch that allows to set the temporary folder for the aria2c download manager. Right now, those temp files are stored in the same folder as the output file, which usually is not a problem, unless that path is some cloud destination, such as OneDrive. In that case the client is starting to upload all those smart files into the Cloud, only to delete them again once destreamer has finished.

**Comment by snobu** [comment]
Thanks for this. Tracked via https://github.com/snobu/destreamer/projects/2#card-59603704
