### ISSUE TITLE
Video Tutorial

### ISSUE THREAD

**Issue by chiragdkothari** [snobu/destreamer#38]
Hello, 
Thanks for this awesome code ... works well ... could please add a video tutorial ?

**Comment by snobu** [comment]
I believe it's too early for that since the project is still under dramatic change. However if you believe it would be useful and you'd like to record that i'm more than happy to link to your video from the README.

**Comment by chiragdkothari** [comment]
here is one ... its in italian tho .. but i think it can help 
https://www.youtube.com/watch?v=AZkcyAOF00Y&gl
