### ISSUE TITLE
[FATAL ERROR] Download didn't progress

### ISSUE THREAD

**Issue by cnchehon** [snobu/destreamer#397]
Download didn't progress

![snipaste_20210720_141318](https://user-images.githubusercontent.com/69850183/126271129-37295acb-70bc-4984-9648-7e536f663b89.png)

**Comment by snobu** [comment]
Use a newer ffmpeg version. Also please run in CMD.exe or PowerShell, not in CygWin.

**Comment by cnchehon** [comment]
I've runed it in cad, but it seems not work, still no progress.
![snipaste_20210723_012650](https://user-images.githubusercontent.com/69850183/126682880-6d4d89a9-46c0-4de7-a92b-9292114191bc.png)

**Comment by snobu** [comment]
What ffmpeg version are you using. Try 4.3.1 or newer.

ffmpeg --version

**Comment by wbhinspector** [comment]
I have the same issue. OS: windows 10
ffmpeg version 4.4
progress [░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0% 0 0s

[ERROR] FFmpeg returned an error: 
[FATAL ERROR] Unknown FFmpeg error
Downloading Video: xxxxxxxxxxxxxxxxxx

[FATAL ERROR] Unknown FFmpeg error nd HLS URL. This may take a few seconds...

ffmpeg version 4.4-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
libavutil      56. 70.100 / 56. 70.100
libavcodec     58.134.100 / 58.134.100
libavformat    58. 76.100 / 58. 76.100
libavdevice    58. 13.100 / 58. 13.100
libavfilter     7.110.100 /  7.110.100
libswscale      5.  9.100 /  5.  9.100
libswresample   3.  9.100 /  3.  9.100
libpostproc    55.  9.100 / 55.  9.100

**Comment by snobu** [comment]
Try to get a different ffmpeg binary, something that doesn't come from www.gyan.dev

**Comment by wbhinspector** [comment]
> Try to get a different ffmpeg binary, something that doesn't come from [www.gyan.dev](http://www.gyan.dev)

thanks, it works now.
