### ISSUE TITLE
Chromium crashes at npm start

### ISSUE THREAD

**Issue by bigbob55555** [snobu/destreamer#4]
When I try to run the program, chromium crashes like this: 
![image](https://user-images.githubusercontent.com/56517247/66719986-f584ba00-edc4-11e9-9ab4-30cb5f76a885.png)

Here's what the command prompt looks like:
```
C:\destreamer-master>npm start https://web.microsoftstream.com/video/745f450f-7454-4399-83bf-460ba2b6956f

> destreamer-node@1.0.0 start C:\destreamer-master
> node ./destreamer.js "https://web.microsoftstream.com/video/745f450f-7454-4399-83bf-460ba2b6956f"


Using youtube-dl version 2019.08.13
Launching headless Chrome to perform the OpenID Connect dance...
(node:4524) UnhandledPromiseRejectionWarning: Error: Protocol error (Performance.enable): Target closed.
    at C:\destreamer-master\node_modules\puppeteer\lib\Connection.js:183:56
    at new Promise (<anonymous>)
    at CDPSession.send (C:\destreamer-master\node_modules\puppeteer\lib\Connection.js:182:12)
    at Page._initialize (C:\destreamer-master\node_modules\puppeteer\lib\Page.js:137:20)
    at Function.create (C:\destreamer-master\node_modules\puppeteer\lib\Page.js:47:16)
    at C:\destreamer-master\node_modules\puppeteer\lib\Target.js:74:32
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Browser._createPageInContext (C:\destreamer-master\node_modules\puppeteer\lib\Browser.js:177:18)
    at async rentVideoForLater (C:\destreamer-master\destreamer.js:45:18)
  -- ASYNC --
    at Target.<anonymous> (C:\destreamer-master\node_modules\puppeteer\lib\helper.js:111:15)
    at Browser._createPageInContext (C:\destreamer-master\node_modules\puppeteer\lib\Browser.js:177:31)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async rentVideoForLater (C:\destreamer-master\destreamer.js:45:18)
  -- ASYNC --
    at Browser.<anonymous> (C:\destreamer-master\node_modules\puppeteer\lib\helper.js:111:15)
    at rentVideoForLater (C:\destreamer-master\destreamer.js:45:32)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:4524) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4524) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
Any help is much appreciated.

**Comment by snobu** [comment]
Looks like `puppeteer`  (the thing that drives the browser interaction) doesn't work with that version with Chromium for whatever this error suggests ` Error: Protocol error (Performance.enable):`.

Try adding `executablePath` and point to Chrome instead.

```
const browser = await puppeteer.launch({
        executablePath: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe'
...
```

You don't need to have Chrome installed, it should be downloaded by `puppeteer` when you do `npm install`, somewhere in `node_modules\puppeteer\.local-chromium\win64-686378\chrome-win`, so just use `chrome.exe` from that location.

I should probably make this the default. I believe it now launches whatever it finds globally installed on that system.

**Comment by bigbob55555** [comment]
Okay perfect, changing puppeteer version number in package.json ("puppeteer": "1.20.0") solved the problem!

**Comment by snobu** [comment]
Thanks for reporting this issue. I'll fix the version number in both dev and master branches. Cheers!

**Comment by wpitallo** [comment]
I am getting this same issue using puppeteer 2.0.0

**Comment by bigbob55555** [comment]
did something change? it's all of a sudden giving me the same chromium crash screen now again. using "puppeteer": "^1.20.0" which was working previously

**Comment by snobu** [comment]
Remove node_modules and do a fresh `npm install`. It would be that Microsoft Stream has changed the id tags for the Azure Media Player elements this project is trying to hook to. If that's the case we need better logic than attempting to pick up page elements by name.

**Comment by wpitallo** [comment]
@snobu thanks. I tried this and it did not work. I ended up installing the latest chromium distribution (think it was 81) and and then added the path manually to .launch() and and that seems to work.

**Comment by bigbob55555** [comment]
> @snobu thanks. I tried this and it did not work. I ended up installing the latest chromium distribution (think it was 81) and and then added the path manually to .launch() and and that seems to work.

Did you download the latest version from here (https://download-chromium.appspot.com/)? I tried doing that and it's still giving the same error from before.
