### ISSUE TITLE
Session terminating after accessToken expires

### ISSUE THREAD

**Issue by lukaarma** [snobu/destreamer#43]
Right now to make the execution a bit less annoying the login happens only at the beginning and if too much time the token expires, so if the queue is too long it may stop working mid download.

To fix this we can check before every download how much time remains before the token expires, I don't have the time right now.

**Comment by snobu** [comment]
`/refreshtoken` may hold the answer here. We could exchange our access token for a fresh token by calling that endpoint at the start of the next video download (array position 1, since 0 already has our cached access token).

Did a little experiment and it works, i'll push an implementation soon.

**Comment by snobu** [comment]
```
curl 'https://euwe-1.api.microsoftstream.com/api/refreshtoken?api-version=1.3-private'  \
    -H 'Authorization: Bearer eyJ0eXAi....Rpxg' 

< set-cookie: Authorization=eyJUb2tl....
```

Nothing to see here, just a note to myself.

**Comment by snobu** [comment]
Partial implementation via https://github.com/snobu/destreamer/pull/62

**Comment by el3ctrician** [comment]
i started to work on this but on an older version... how can i help to get the implementation from partial to full ? 

Thanks

**Comment by snobu** [comment]
It's fully implemented in the master branch with one caveat. See Found a bug section in README.

**Comment by snobu** [comment]
Closing as completed. We'll open a new issue for the remaining problem of refreshing tokens on a separate execution thread.
