### ISSUE TITLE
Implement Mocha tests

### ISSUE THREAD

**Issue by lukaarma** [snobu/destreamer#46]
We need to implement Mocha tests in the tokencache branch

@kylon do you want to take a look since last time you did a great job? (and I know absolutely nothing about them :D )

**Comment by snobu** [comment]
@kylon just port them over from `dev`. Or i can do it later today. There are many other changes than we need to merge in, we're trying to keep track of them here under the Projects tab.

**Comment by kylon** [comment]
ok, are there new tests?
so we port changes from dev to tokencache and not the other way around?

**Comment by snobu** [comment]
Let's close this issue after we complete this card:
https://github.com/snobu/destreamer/projects/1#card-36071755

**Comment by lukaarma** [comment]
#47 and #48 implemented those tests, closing
