### ISSUE TITLE
 ENOENT: no such file or directory

### ISSUE THREAD

**Issue by samuel-esp** [snobu/destreamer#58]
I have created a list.txt file containing all my urls: 

-one line per url
-every url is delimited with marks (""). 

then i proced with the command line
node destreamer.js --username "loginemail" --outputDirectory "mydirectorypath" \ --videoUrls "mylist.txtpath"

the program times out with the following error

no such file or directory, open 'mylist.txtpath'

**Comment by kylon** [comment]
do not add quotes to urls.

the error is quite specific, your file is not found, wrong path? or wrong file name?

**Comment by snobu** [comment]
`mylist.txtpath`, is that a typo? File should end in `.txt`. You also don't need the doublequotes, just one URL per line.

**Comment by samuel-esp** [comment]
"mylist.txtpath" is a file path containing my txt file ending with .txt, i previously tried without quotes and nothing changes

**Comment by kylon** [comment]
can you write your path with example values?
also try to define videoUrls as first argument, you can also use the alias -V

last thing, are you using the latest version?

**Comment by samuel-esp** [comment]
node destreamer.js --username "email@email.it" --outputDirectory "C:\Users\myname\Desktop\destreamer-dev\destinationfolder" ^ --videoUrls "C:\Users\myname\Desktop\destreamer-dev\list.txt"

yes I installed the repository 1 hour ago, nodejs is not the latest but the reccomended, destremers works like a charm except for the .txt

**Comment by snobu** [comment]
Remove that backslash, it only works in bash and confuses the Windows terminal.

**Comment by kylon** [comment]
if you are in the same directory of destreamer, just write --videoUrls list.txt

ps: all these quotes should be superfluous

ok, i have the same problem in powershell, i ll look into this

**Comment by samuel-esp** [comment]
Alright, I removed the backslash, tried not to specify the path but just writing list.txt (since I'm in the same directory) but nothing changes

**Comment by kylon** [comment]
i'm sure issue found, it is windows itself....as always :D 

please rename your list.txt to list in your destreamer folder
i suppose you have the "hide file extensions" on, which is default (windows is dumb)

and run --videoUrls list.txt (yes, add .txt here)

**Comment by samuel-esp** [comment]
Yeah man it works! I used macOS and Linux for a while and didn't remember windows was that dumb with extension names, thank you guys!
