### ISSUE TITLE
[Feature Proposal] Resuming progress from list of urls

### ISSUE THREAD

**Issue by gianlucarizzo** [snobu/destreamer#60]
I think it would be helpful to add some kind of "already downloaded" check when you provide a file with urls and a download folder which already contains data.

Could it be useful?

**Comment by kylon** [comment]
well, i think this is not feasible, i'm pretty sure we don't have some kind of unique data to map your files with streams videos and more important, it would slow down destreamer.

what if you have hundred of videos in your folder and 10 or more urls, we cannot scan your entire hdd just to find out that the video you are trying to download is there.

moreover, the video could have been tampered by the user, so the user knows that the video is there but destreamer cannot find a match.
this is confusing or better: "bad user experience"

@snobu can probably tell you more

**Comment by samuel-esp** [comment]
@kylon wouldn't be possibile to just delete the current line from the current .txt when the download succeeds?

**Comment by kylon** [comment]
yes, we can probably add an option or something for that

**Comment by snobu** [comment]
We could introduce an `--skip-if-exists` argument, if passed we check if the file exists on disk and if it does we move on to the next file in list.

This should be implemented after we release v2.0 (tokencache branch). We have enough work items on our plate, let's not dilute quality with non critical features.

**Comment by gianlucarizzo** [comment]
While writing i was thinking of some kind of hash function of the url to be saved somewhere in the file (filename? metadata?), but now i realize that Stream urls have a unique UUID for the video, so it could be used for the check.
I think that this should not hit performance so hard, and even a huge folder could be processed in a little time.

@samuel-esp that would be great too. Maybe that flag would would keep the original file and create a "progress" file (with a naming convention) that indicates what is left.

Even though i would consider the UUID solution too, wich i personally find good too.

What do you think?

**Comment by snobu** [comment]
Feels like this can easily be a bash/PowerShell script. Destreamer has never been designed to be a mass downloader or a download manager, it's adhering to the UNIX philosophy of do one thing and do it well, although i have to admit we're doing quite a few things now and not too shabby :)

**Comment by kylon** [comment]
filename is not realiable and creating some kind of index is out of destrimer scope

when i say unique, i mean that it is something the user cannot delete or modify.
everything you can modify is not reliable

**Comment by snobu** [comment]
@gianlucarizzo, thank you for your proposal, however i'm closing the issue as out of scope for now. As the project evolves we may reevaluate the implementation of some kind of download state.
