### ISSUE TITLE
Enhance txt file input

### ISSUE THREAD

**Issue by lukaarma** [snobu/destreamer#69]
We could take example from aria2c and allow options for each url in the txt file, like different output directories and so on

**Comment by kylon** [comment]
different output dir is already there (--outputDirectories)

**Comment by lukaarma** [comment]
I know but it would be more intuitive and easier to use for the average user using options in the file in my opinion

**Comment by snobu** [comment]
Not sure about his one @lukaarma, could be useful for some but i don't think it's our main goal here to put that much structure into our output.

If this comes up as a regular request then let's revisit the idea.
