### ISSUE TITLE
Could not see any action after "Running in an elevated shell" console output

### ISSUE THREAD

**Issue by lkumarm448** [snobu/destreamer#71]
When trying to download a video from MS WebStream using destreamer.js, I am just seeing single line output as shown in the screenshot below, ie., Running in an elevated shell. I don't see any other command/browser windows getting opened. I tried to execute the command from a normal CMD as well as from a CMD with runas Administrator option. Still no success. Please help me.

![image](https://user-images.githubusercontent.com/19576009/79643698-d296f080-81c1-11ea-8295-8e3cae0c5473.png)

**Comment by snobu** [comment]
destreamer cannot run in an elevated (Administrator) shell. Open a regular terminal window. I'll fix that error right now to tell you more.
