### ISSUE TITLE
Failing to build with NPM.

### ISSUE THREAD

**Issue by Sylviath** [snobu/destreamer#72]
Hi, sorry if this sounds like a very dumb question (I rarely use github) but I can't seem to build destreamer. Executing `npm install` returns me with walls of warning such as:

`npm WARN tar ENOENT: no such file or directory, open 'C:\Users\xx\Downloads\destreamer-master\node_modules\.staging\es-abstract-6e8ea733\2015\IsConcatSpreadable.js'`

I am using node 13.13 with built-in npm (I have no idea how to figure out). I'll attach the log file if deemed necessary. Thanks!

**Comment by Sylviath** [comment]
I forgot to check the closed issues. Will reopen if I failed. Sorry!

**Comment by kylon** [comment]
if you have a node_modules directory, delete this directory and try again

**Comment by Sylviath** [comment]
Unfortunately, I've tried that solution (deleting node_modules within root directory) and it didn't work. Also tried the `npm cache clean --force`, and the system wide installation.

**Comment by snobu** [comment]
What OS are you on? What npm version?

**Comment by kylon** [comment]
> What OS are you on? What npm version? npm --version or npm version
windows

could it be a problem with package.json?
try to download the whole repo again

**Comment by snobu** [comment]
@Sylviath try removing both node_modules and package-lock.json and give it another go. Never seen that error and Google is giving me confusing results.

**Comment by kosme1234** [comment]
I'm very new to Github, but I am having the same problem with Sylviath.
After putting in npm install, I have a long list that comes up that looks like this: "npm WARN tar ENOENT: no such file or directory, open 'C:\Projects\destreamer\node_modules\.staging\rxjs-d9e3b7d7\operators\map.js'"

My npm ver is 6.14.4
My node ve is v13.13.0

And I tried this again after deleting the node_modules directory... T.T

**Comment by Sylviath** [comment]
Big thanks for the replies. I'm running on Windows 10. npm version 6.14.4, node.js 13.13.0.

> running npm install inside destreamer directory?

Yes, I see them recognizing the package.json if anything.

> try to download the whole repo again

> Try it in a different folder.

Yeah I was thinking of the possibility. Turned off Windows Firewall, turned off Windows Defender real-time security, put the fresh download on C:/ and did another `npm install` with no avail.

[2020-04-20T12_05_30_634Z-debug.log](https://github.com/snobu/destreamer/files/4503380/2020-04-20T12_05_30_634Z-debug.log)

> try removing both `node_modules` and `package-lock.json`

Tried that immediately after the last attempt. Failed.

[2020-04-20T12_06_59_486Z-debug.log](https://github.com/snobu/destreamer/files/4503381/2020-04-20T12_06_59_486Z-debug.log)

It seems to me that this may not be a problem from destreamer, but my npm and/or node.js instead. Thanks.

**Comment by snobu** [comment]
Do you have git installed or did you download a zip of this repo?
I think one of the dependencies needs git to install, judging by this log snippet -
```
962 error enoent Error while executing:
962 error enoent undefined ls-remote -h -t ssh://git@github.com/notmasteryet/jpgjs.git
962 error enoent
962 error enoent
962 error enoent spawn git ENOENT
```

Install Git from here. We probably need to list that as a dependency as well if this is the case.
https://git-scm.com/download/win

**Comment by kylon** [comment]
yeah, git is required by destreamer packages on all oses, now the error makes sense

**Comment by Sylviath** [comment]
> yeah, git is required by destreamer packages on all oses, now the error makes sense

Perfect. I moved laptop and I TOTALLY forgot this one has no git in it. Downloaded git and ran `npm install` via the GIT CMD, worked. Thanks a bunch, I'll close the issue if @kosme1234 is done with his problem, maybe.

**Comment by snobu** [comment]
@kosme1234, please install git as well and try again.
I've updated the README build guide to include the git dependency.
Thanks for reporting this one!

**Comment by kosme1234** [comment]
YES IT WORKS!! WOOOHOOO Thank you!! Git is what I was missing
