### ISSUE TITLE
Mocha tests fail in GitHub Action

### ISSUE THREAD

**Issue by snobu** [snobu/destreamer#73]
Not sure if this is something GitHub Actions does wrong since those tests work very well on my Mac and Windows box..

```
> destreamer@2.0.0 test /home/runner/work/destreamer/destreamer
> mocha build/test



  1) "before all" hook in "{root}"
  2) "after all" hook in "{root}"

  0 passing (2s)
  2 failing

  1) "before all" hook in "{root}":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()"    
     is called; if returning a Promise, ensure it resolves.
  

  2) "after all" hook in "{root}":
     TypeError: Cannot read property 'close' of undefined
      at Context.after (build/test/test.js:28:19)



##[error]The operation was canceled.
```

That's from our CI GitHub Action (which now fails). Any ideas?

**Comment by kylon** [comment]
it seems that puppeteer does not run, can you get some meaningful message in before or puppeteer?

**Comment by snobu** [comment]
Fails randomly - https://github.com/snobu/destreamer/actions
Sometimes it does come up, i think it's a Puppeteer on Docker thing but not sure where to start.

**Comment by snobu** [comment]
It's not. Sometimes the whole matrix (Node 8, 10, 12, 13) finishes with all greens. This could be a transient Actions failure. Let's wait it out.

**Comment by snobu** [comment]
Fixed somewhere down the line, allagedly the beforeAsync and afterAsync calls in mocha don't go very well with GitHub Actions so i removed them since they were unnecessary.
