### ISSUE TITLE
Parsing video URLs with additional query parameters

### ISSUE THREAD

**Issue by constructor-s** [snobu/destreamer#74]
First of all, congrats on releasing 2.0! 

I have a minor but potentially important improvement for the logic for parsing video GUID from the URL. I don't know about you but when I copy the video URL it is in the form of: `https://web.microsoftstream.com/video/<videoId>?channelId=<channelId>`

Right now the parsing logic at https://github.com/snobu/destreamer/blob/087850821cb12241cdfeb914f6ce9ce82e07d198/src/destreamer.ts#L108 does not account for the additional query parameters after `?`. 

I am making a quick pull request. 

It worked fine for me even though I didn't change a similar logic logic at https://github.com/snobu/destreamer/blob/087850821cb12241cdfeb914f6ce9ce82e07d198/src/destreamer.ts#L46

**Comment by snobu** [comment]
Thank you for your kind words! @kylon, i believe that's some of your code, would you mind taking a look at the PR?

**Comment by kylon** [comment]
i think this is @lukaarma code, i did not write that function, anyway i ve just made a review

**Comment by constructor-s** [comment]
Merged in 318026895b8dace61629f1b8ce2a52245bc581e4
