### ISSUE TITLE
TypeError: process.off is not a function

### ISSUE THREAD

**Issue by MarioVilas** [snobu/destreamer#76]
When downloading a video, after the download is completed I get the following error:
```
Download finished: videos/<whatever>.mp4
TypeError: process.off is not a function
    at downloadVideo (/home/mario/destreamer/build/src/destreamer.js:186:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
The video downloads correctly so it doesn't seem like a big issue, but I thought you may want to know.

**Comment by snobu** [comment]
Thanks for this bug report! Looking into it right now.

**Comment by snobu** [comment]
@MarioVilas, what's your Node version please? `node --version`.

**Comment by snobu** [comment]
I'm assuming 8.x which we now have a fix for (https://github.com/snobu/destreamer/pull/79).

**Comment by MarioVilas** [comment]
Hi! You assumed correctly, running 8.10.0 here.

**Comment by MarioVilas** [comment]
I can confirm the patch works on my machine now. Thanks! :)
