### ISSUE TITLE
Error messages = Invalid DTS, Invalid timestamps

### ISSUE THREAD

**Issue by brendanefro** [snobu/destreamer#8]
Hello! This project looks awesome but unfortunately isn't working for me on windows or linux for a video i'm trying to download. 

The microsoft streams video gives the error message:
Error code 0x20400003

and then the terminal just keeps giving off errors like this: 
`[mp4 @ 0000017ceca76780] Invalid DTS: 885060 PTS: 881820 in output stream 0:0, replacing by guess
[mpegts @ 0000017cec6e7000] Invalid timestamps stream=0, pts=7367850, dts=7371090, size=6535
[mpegts @ 0000017cec6e7000] Invalid timestamps stream=0, pts=7371090, dts=7373790, size=4845
[hls @ 0000017cec59c880] Invalid timestamps stream=0, pts=7367850, dts=7371090, size=6535
[mp4 @ 0000017ceca76780] Invalid DTS: 891090 PTS: 887850 in output stream 0:0, replacing by guess
[hls @ 0000017cec59c880] Invalid timestamps stream=0, pts=7371090, dts=7373790, size=4845
[mp4 @ 0000017ceca76780] Invalid DTS: 893790 PTS: 891090 in output stream 0:0, replacing by guess`

**Comment by snobu** [comment]
Is that a recent ffmpeg version you are using?

**Comment by brendanefro** [comment]
Hi, thank you for your quick reply! Yes it is, I installed all the prereqs yesteday when I attempted to download the video.

One other thing is, when the chromium window opens up the video doesn't play (despite working normally from chromium any other time) and instead gives an error message saying:

"There’s a problem with the browser.
Please try a different browser to play this video."

with the Error code 0x20400003

I don't know if this is normal?

**Comment by brendanefro** [comment]
It seems to be related to the chromium window that it opens up. The chromium installed on my machine seems to play the videos just fine but the chromium window that destreamer opens seems to be a different version that wont play the video (even in a new tab)

**Comment by brendanefro** [comment]
Update: despite the error messages constantly appearing it still seems to download (after a couple of hours) but doesn't download the sound with it

**Comment by snobu** [comment]
My ffmpeg skill and knowledge is pretty basic, you would probably have more success addressing this via a ffmpeg specific forum or StackOverflow. Nothing specific to the project itself (destreamer) since all we do here is pass a key URL with a cookie down to Youtube-dl which then calls into ffmpeg.

**Comment by snobu** [comment]
Closing for now. Feel free to reopen if this turns out to be a broader issue not isolated to one or two videos.

**Comment by brendanefro** [comment]
Hey just wanted to say the new version of destreamer has fixed my issue and it now downloads with sound! Thank you!
