### ISSUE TITLE
Error during runtime: Unrecognized URL format / URL is not defined

### ISSUE THREAD

**Issue by Pakox** [snobu/destreamer#80]
Hi all,
Tried to use destreamer 2.0.0 on Ubuntu 18.04.
I'm completely new to TypeScript so not quite sure why is this error showing up.
```
_____ub@____-ub-vm:~/destreamer$ ./destreamer.sh -i "https://web.microsoftstream.com/video/aa54_1a7-____-____-____-____________" -v
Using ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers

Video URLs:
[ 'https://web.microsoftstream.com/video/aa54_1a7-____-____-____-____________' ]

Access token still good for 46 minutes.

Unrecognized URL format in https://web.microsoftstream.com/video/aa54_1a7-____-____-____-____________: URL is not defined
```

It seems to be coming from: https://github.com/snobu/destreamer/blob/087850821cb12241cdfeb914f6ce9ce82e07d198/src/destreamer.ts#L102-L117 

Is there any possible mistake I made, or any try I can do?

**Comment by snobu** [comment]
Try to upgrade from Node 8.0 to 10, 12 or 13, or make the changes highlighted in this PR (https://github.com/snobu/destreamer/pull/79).

**Comment by Pakox** [comment]
Oops..  was too anxious to ask, didn't notice the version of `nodejs`
It works perfectly now after I upgraded to Node.js to version 13.
Thank you a lot for helping me.

**Comment by snobu** [comment]
Thanks for your report, feedback is always appreciated over here.
