### ISSUE TITLE
'RangeError: Invalid array length' when running in MinGW shell

### ISSUE THREAD

**Issue by MohamedYahia2011** [snobu/destreamer#83]
Using ffmpeg version git-2020-04-20-cacdac8 Copyright (c) 2000-2020 the FFmpeg developers

Access token still good for 59 minutes.

Fetching metadata...
RangeError: Invalid array length
    at Object.parse (C:\Users\Mohamed Yahia\Desktop\jkhklj\destreamer\node_modules\cli-progress\lib\options.js:48:38)
    at new SingleBar (C:\Users\Mohamed Yahia\Desktop\jkhklj\destreamer\node_modules\cli-progress\lib\single-bar.js:8:24)
    at downloadVideo (C:\Users\Mohamed Yahia\Desktop\jkhklj\destreamer\build\src\destreamer.js:120:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Unhandled error!
Timeout or fatal error, please check your downloads directory and try again

any help ?

**Comment by snobu** [comment]
Are you using cygwin/MinGW by any chance?

**Comment by MohamedYahia2011** [comment]
yes, i'm using MinGW .. what do you recommend ?

**Comment by snobu** [comment]
Please use cmd.exe or PowerShell for destreamer. The README has a note aboit this too.

**Comment by snobu** [comment]
We have a progress bar that needs to know the number of columns of your terminal so it can scale accordingly. For reasons we don't yet understand this does not work in MinGW.

If you would like to debug this we're more than happy to accept a pull request with a fix.

**Comment by MohamedYahia2011** [comment]
Thank you so much for making this and for the replies, have a nice one

**Comment by snobu** [comment]
So i've tried both Cygwin and MINGW32 (the shells both bring to Windows) and i cannot reproduce the problem. Could you please let me know what's the binary that launches your shell? (the one that doesn't work for destreamer). Thanks!

**Comment by MohamedYahia2011** [comment]
i'm using Git Bash shell >> (Git for Windows MinGW)
sorry for the late reply

**Comment by snobu** [comment]
This is now fixed, if we can't detect the number of columns we fall back to printing a line of text indicating progress.
