### ISSUE TITLE
Video quality

### ISSUE THREAD

**Issue by FraH90** [snobu/destreamer#86]
I've noticed that on the new branch (2.0) you've discarded youtube-dl in favor of a full ffmpeg approach.

I've noticed also that video downloaded with the new version (2.0) weights a lot less than videos downloaded with the previous version of destreamer.
A 2 hours video with the previous version was about 400mb, now it's 170mb circa.

I'm wondering so if that means that video quality is bad, compared to the previous version, of it is applied another compression algorithm for the video.

So I'm wondering, now we can't decide for the output video quality, right? Having dropped youtube-dl and given that command line parameters related to output quality were passed to youtube-dl

Obviously that's not an issue, just want to know if videos downloaded with the 2.0 version have same "quality" of the previous version, and if not what I can do to download them with the same previous quality with this release.
Thanks :)

**Comment by snobu** [comment]
Your concern is valid and right now i have nothing definitive to report. We're investigating switching to aria2c for multi-threaded HLS download so if that happens we'll need to look at how aria is handling quality.

As soon as we're stable in that regard we'll look closer at exposing quality input parameters.

Back to the studio.
