### ISSUE TITLE
Univerisity account on microsoftstream

### ISSUE THREAD

**Issue by RobCata** [snobu/destreamer#87]
Hi, can I use the university account? Given that for login he asks for the university email first and then the tax code and pin

**Comment by joao44289** [comment]
I have used my university account with no problems so far.

**Comment by RobCata** [comment]
How did you do?

**Comment by kylon** [comment]
yes, you can use any account

destreamer will launch its own browser where you can insert your login data

**Comment by RobCata** [comment]
> 
> 
> yes, you can use any account
> 
> destreamer will launch its own browser where you can insert your login data
Yes, but how? I installed all the "prereqs" and did everything in the "How to build" section.
But when I go to start the commands "./destreamer.sh -i" https://web.microsoftstream.com/video/VIDEO-1 ""
or "./destreamer.sh -u user@example.com -i" https://web.microsoftstream.com/video/VIDEO-1 "" does not work, no browser opens ...

**Comment by RobCata** [comment]
Yes, but how? I installed all the "prereqs" and did everything in the "How to build" section.
But when I go to start the commands "./destreamer.sh -i" https://web.microsoftstream.com/video/VIDEO-1 ""
or "./destreamer.sh -u user@example.com -i" https://web.microsoftstream.com/video/VIDEO-1 "" does not work, no browser opens ...

**Comment by snobu** [comment]
That happens in WSL (Windows Subsystem for Linux) so if you're using that just switch to regular cmd.exe or PowerShell.

**Comment by RobCata** [comment]
Im using PowerShell, snobu can I contact you privately?
