### ISSUE TITLE
I have to login every time

### ISSUE THREAD

**Issue by MacInTheNet** [snobu/destreamer#9]
Hi, I don't know if it's a real problem, I don't care... I just signed up on GitHub because I wanted to thank you!
I'm using your code on a Mac (I don't know anything about coding!!!) and it works perfectly after I installed through brew everything I had to install!
I also passed it 4 URLs together and it got everything correctly!
I didn't modify anything in your file and I have to login every time I run the code even if I download one video after another  but I don't care :)
Thank you again!

p.s. I just noticed it doesn't download by default the best version of the video (1080p) but sometimes it chooses a worse resolution. Is there a way to set the resolution in the command I run?
I have to check before if that resolution exists of course.

**Comment by snobu** [comment]
Right now there's no token cache which is something that i should really implement. I also take PRs should that be something you want to code yourself, this is a committee driven project :)

As soon as [this PR](https://github.com/snobu/destreamer/pull/12) gets merged you will be able to pick the quality. All credits [@angelobpool](https://github.com/angelobpool) for that feature.
