### ISSUE TITLE
How to use destreamer behind corporate proxy on windows 10

### ISSUE THREAD

**Issue by jbaznik** [snobu/destreamer#91]
I install global-agent from https://github.com/gajus/global-agent

npm install global-agent
set GLOBAL_AGENT_HTTP_PROXY=http://127.0.0.1:3128/

edit vim destreamer.js file

const { bootstrap: bootstrapGlobalAgent } = require('global-agent');
bootstrapGlobalAgent();

I get this
Error: connect ETIMEDOUT
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',

  response: undefined,
  isAxiosError: true,
  toJSON: [Function]
}

Unhandled error!
Timeout or fatal error, please check your downloads directory and try again

Has anyone have idea what to do?

**Comment by snobu** [comment]
No idea really, but if you find a straightforward way to do it i'd be happy to add it to the README.
