### ISSUE TITLE
Video quality selection

### ISSUE THREAD

**Issue by ahmedhamdy90** [snobu/destreamer#92]
First of all, thank you for the great utility especially in this time of distance education.

I wanted to ask about a feature of selecting video quality because the script is downloading a low quality for now?

**Comment by lukaarma** [comment]
I'm looking into it, hopefully I'll be able to push a new branch in a couple of days

**Comment by snobu** [comment]
It is not, please see this -
https://github.com/snobu/destreamer/issues/88#issuecomment-619438989

It defaults to the best available HLS bitrate. If it doesn't, make sure you're using a recent ffmpeg build (year 2020-ish).

**Comment by ahmedhamdy90** [comment]
> It is not, please see this -
> [#88 (comment)](https://github.com/snobu/destreamer/issues/88#issuecomment-619438989)
> 
> It defaults to the best available HLS bitrate. If you're seeing low quality results and the video in your browser looks in fact much better, make sure you're using a recent ffmpeg build (year 2020-ish).

I already using the latest FFmpeg, but still, the video quality is not good at all.
