### ISSUE TITLE
live stream download

### ISSUE THREAD

**Issue by gelmanovic** [snobu/destreamer#97]
Would it be possible to somehow download a microsoft teams meeting (which is what eventually generates a microsoft stream recording) right away when it is first streamed?
You should be getting my point: there are professors who won't allow recording of the class so this also would be useful.

**Comment by kylon** [comment]
use OBS or any other screen recording app and attach your audio output

please don't ask instructions here

**Comment by gelmanovic** [comment]
Yeah I used to do so but din't come up with a proper video codec setting for low size outputs. Whereas destreamers gets a lossless source with way lower output size.
Thanks anyway.

**Comment by snobu** [comment]
We have no way to hook the video stream in MS Teams and no plans for that either. You're on your own i'm afraid.
